### ISSUE TITLE
When i use tensorboard --logdir=path , says an error: 0xf0 in position 9: invalid continuation byte

### ISSUE THREAD

**Issue by bearpear** [tensorflow/tensorboard#1068]
- TensorBoard version (from pip package, also printed out when running `tensorboard`)
1.6.0

 - OS Platform and version 
Windows 8.1

 - Python version (e.g. 2.7, 3.5)
3.6.2
   - Screenshot
 [<img src="https://image.ibb.co/iyJ1ec/Ads_zg.png">](url)

**Comment by nfelt** [comment]
This sounds like the same issue that was reported in #682.  Are you using a machine with unicode (non-ASCII) characters in its hostname?

Could you please run the following command:

```
python -c "import socket; print(socket.getfqdn()); print(socket.gethostbyaddr(socket.gethostname()))"
```

If it prints out the same error, then this is an underlying issue with python and/or your hostname; there won't be much that TensorBoard can do about it.

**Comment by SrushtiRS** [comment]
Hello @nfelt,

I also faced the same issue while trying to visualize the word2vec embeddings using projector in TensorBoard.
working with
Win 10
Python 3.6
Tensorflow-gpu: 1.12.0
TensorBoard: 1.12.2

please let me know if I need to provide any more information.

I have referenced the issue #682 but couldn't get the code to work even after changing the PC name.

This is the error stack.
`E0503 11:32:30.326298 Thread-3 _internal.py:122] Error on request:
Traceback (most recent call last):
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\werkzeug\serving.py", line 302, in run_wsgi
    execute(self.server.app)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\werkzeug\serving.py", line 290, in execute
    application_iter = app(environ, start_response)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorboard\backend\application.py", line 307, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\werkzeug\wrappers\base_request.py", line 235, in application
    resp = f(*args[:-2] + (request,))
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorboard\plugins\projector\projector_plugin.py", line 514, in _serve_metadata
    for line in f:
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 220, in __next__
    return self.next()
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 214, in next
    retval = self.readline()
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 184, in readline
    return self._prepare_value(self._read_buf.ReadLineAsString())
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 100, in _prepare_value
    return compat.as_str_any(val)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\util\compat.py", line 107, in as_str_any
    return as_str(value)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\util\compat.py", line 80, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte
E0503 11:32:30.326298   584 _internal.py:122] Error on request:
Traceback (most recent call last):
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\werkzeug\serving.py", line 302, in run_wsgi
    execute(self.server.app)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\werkzeug\serving.py", line 290, in execute
    application_iter = app(environ, start_response)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorboard\backend\application.py", line 307, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\werkzeug\wrappers\base_request.py", line 235, in application
    resp = f(*args[:-2] + (request,))
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorboard\plugins\projector\projector_plugin.py", line 514, in _serve_metadata
    for line in f:
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 220, in __next__
    return self.next()
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 214, in next
    retval = self.readline()
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 184, in readline
    return self._prepare_value(self._read_buf.ReadLineAsString())
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 100, in _prepare_value
    return compat.as_str_any(val)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\util\compat.py", line 107, in as_str_any
    return as_str(value)
  File "c:\users\arthu\miniconda3\envs\py36\lib\site-packages\tensorflow\python\util\compat.py", line 80, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte`

**Comment by nfelt** [comment]
@SrushtiRS I don't think this is quite the same issue, actually.  It looks like one of the embedding metadata files you're using isn't encoded using UTF-8.  I'd check to make sure all text files within the log directory you're using are UTF-8 encoded.

**Comment by SrushtiRS** [comment]
Yes indeed! that was the problem.
I was writing the metadata file without specifying encoding.

Could you please tell me how you traced the problem though, I kept thinking it was a hostname issue

**Comment by nfelt** [comment]
Sure - the stacktrace shows that it's coming the TF `file_io` module, called from `_serve_metadata()` in the projector plugin, which indicates that the encoding problem was with reading a projector metadata file.

The actual final error about UnicodeDecodeError looks similar to the issue the poster above had which I think probably is related to decoding a hostname, but in general a unicode error can happen anywhere bytes are being decoded, so the context of where it's coming from matters.

**Comment by nfelt** [comment]
Closing out this issue since it sounds like it's been resolved for you and we haven't heard back from the OP.

**Comment by SrushtiRS** [comment]
That makes sense.
Thanks a ton for helping me resolve this!

**Comment by z-x-x136** [comment]
(pytorch) E:\PYTHON\人工智能\PyTorch深度学习\learn_torch\transforms使用>python -c "import socket; print(socket.getfqdn()); print(socket.gethostbyaddr(socket.gethostname()))"
Zeng
('Zeng', [], ['fe80::c07c:7bda:69ea:4a86'])

but,
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 14: invalid start byte
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.15.1 at http://localhost:6006/ (Press CTRL+C to quit)
