### ISSUE TITLE
Tensorbaord 1.7 error with TensorFlow 1.8, and how to install tensorboard 1.8?

### ISSUE THREAD

**Issue by YantianZha** [tensorflow/tensorboard#1149]
- TensorBoard version: 1.7.0
 - TensorFlow version: tensorflow-gpu-1.8.0rc0
 - OS Platform and version: Linux Ubuntu 16.04
 - Python version: 2.7
 
Hello,
I'm having a problem of using tensorboard 1.7 to visualize the events generated by tensorflow 1.8. The error is at bottom. I suspect a reason is I should use tensorboard 1.8 instead of 1.7. That said, I cannot find a way to install the tensorboard 1.8 separately. I know tensorflow is dependent on tensorboard, so I did a reinstallation of tensorflow 1.8 (after removing the tensorboard). But the installation of tensorflow 1.8 actually comes with installing tensorboard 1.7. So reinstalling tensorflow 1.8 still cannot resolve the problem. Thanks for helping!

Command: tensorboard --logdir=./
Error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 360, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 334, in reload_multiplexer
    multiplexer.Reload()
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 195, in Reload
    accumulator.Reload()
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 185, in Reload
    for event in self._generator.Load():
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/directory_watcher.py", line 88, in Load
    for event in self._LoadInternal():
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/directory_watcher.py", line 112, in _LoadInternal
    for event in self._loader.Load():
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/event_file_loader.py", line 53, in Load
    self._reader.GetNext(status)
TypeError: GetNext() takes exactly 1 argument (2 given)

**Comment by YantianZha** [comment]
Right now I temporarily resolved the problem by replacing the "tensorboard/backend/event_processing/event_file_loader.py" with the latest version (https://github.com/tensorflow/tensorboard/edit/master/tensorboard/backend/event_processing/event_file_loader.py).

**Comment by nfelt** [comment]
Duplicate of #1111

**Comment by YouZengLi** [comment]
![screenshot from 2018-08-30 10-25-06](https://user-images.githubusercontent.com/19741535/44825861-13ce3b80-ac3f-11e8-8719-2fbfcbe52983.png)

**Comment by YouZengLi** [comment]
@YantianZha  Thank you, your method can solve my problem.
