### ISSUE TITLE
Tensorboard gives `CUDA_ERROR_OUT_OF_MEMORY`?

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorboard#1194]
I'm currently training so I'm hogging my GPU for memory. Why would Tensorboard give an OOM? What does/should it use CUDA for?

On ubuntu 16.04, tensorflow-gpu-1.7

```
tzaman@tzaman:~/experiments/ln01$ tensorboard --logdir=.
2018-05-17 19:44:27.501649: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-05-17 19:44:32.427365: E tensorflow/core/common_runtime/direct_session.cc:167] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12652838912
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 11, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/main.py", line 36, in run_main
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/main.py", line 45, in main
    default.get_assets_zip_provider())
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/program.py", line 166, in main
    tb = create_tb_app(plugins, assets_zip_provider)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/program.py", line 200, in create_tb_app
    window_title=FLAGS.window_title)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 124, in standard_tensorboard_wsgi
    plugin_instances = [constructor(context) for constructor in plugins]
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/beholder/beholder_plugin.py", line 47, in __init__
    self.most_recent_frame = im_util.get_image_relative_to_script('no-data.png')
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/beholder/im_util.py", line 277, in get_image_relative_to_script
    return read_image(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/beholder/im_util.py", line 265, in read_image
    return np.array(decode_png(image_file.read()))
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/beholder/im_util.py", line 182, in __call__
    self._lazily_initialize()
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/beholder/im_util.py", line 160, in _lazily_initialize
    self._session = tf.Session(graph=graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1509, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 638, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
```

**Comment by TimZaman** [comment]
Closing for now. After some cleanups of tb and tf it seems things have restored their sanity on my end.

**Comment by nfelt** [comment]
Duplicate of #1107

**Comment by nfelt** [comment]
This sounds like #1107 which recently had a mitigating PR go in.  The nightly release should pick up that PR soon, so if you see the issue again you could try installing `tb-nightly` and using that.
