### ISSUE TITLE
Cannot set name of tf.keras.models

### ISSUE THREAD

**Issue by Dapid** [tensorflow/tensorboard#1368]
The following example fails with an Attribute error on Python 3.6:

```
EMBEDDED = True
if EMBEDDED:
    from tensorflow.keras.layers import Input, Dense
    from tensorflow.keras.models import Model
else:
    from keras.layers import Input, Dense
    from keras.models import Model

inp = Input((32,))
x = Dense(1)(inp)
model = Model(inp, x)
model.name = 'mymodel'
```
Setting EMBEDDED to False it uses the independent Keras library, and it works.

Here is the full traceback:
```
Traceback (most recent call last):
  File "/home/david/.PyCharm2018.2/config/scratches/scratch_17.py", line 13, in <module>
    model.name = 'mymodel'
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 432, in __setattr__
    super(Network, self).__setattr__(name, value)
AttributeError: can't set attribute
```

Versions:
Tensorflow: 1.10.0
Keras: 2.2.0

**Comment by stephanwlee** [comment]
@Dapid Skimming through the code, it does not look like the issue pertains to TensorBoard. Did you mean to raise an issue to Tensorflow/Tensorflow instead? Thanks!

**Comment by Dapid** [comment]
You are absolutely right, I filed it in the wrong repo, sorry!
