### ISSUE TITLE
What-If is not support GZIP-compressed TFRecord

### ISSUE THREAD

**Issue by ornew** [tensorflow/tensorboard#1452]
- TensorBoard version: 1.11.0a0
- OS Platform and version: macOS High Sierra
- Python version: 2.7
 
I get the following error occurred (and infinite loading):

```
E0921 23:51:35.055788 Thread-5 _internal.py:87] Error on request:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_ornew/c3f3524115bcb8d4f5cdb704ea3abfbd/external/org_pocoo_werkzeug/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/private/var/tmp/_bazel_ornew/c3f3524115bcb8d4f5cdb704ea3abfbd/external/org_pocoo_werkzeug/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/Users/ornew/src/github.com/tensorflow/tensorboard/tensorboard/backend/application.py", line 298, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/private/var/tmp/_bazel_ornew/c3f3524115bcb8d4f5cdb704ea3abfbd/external/org_pocoo_werkzeug/werkzeug/wrappers.py", line 291, in application
    return f(*args[:-2] + (request,))(*args[-2:])
  File "/Users/ornew/src/github.com/tensorflow/tensorboard/tensorboard/plugins/interactive_inference/interactive_inference_plugin.py", line 132, in _examples_from_path_handler
    examples_path, examples_count, parse_examples=False)
  File "/Users/ornew/src/github.com/tensorflow/tensorboard/tensorboard/plugins/interactive_inference/utils/platform_utils.py", line 95, in example_protos_from_path
    append_examples_from_iterable(record_iterator, examples)
  File "/Users/ornew/src/github.com/tensorflow/tensorboard/tensorboard/plugins/interactive_inference/utils/platform_utils.py", line 83, in append_examples_from_iterable
    for i, value in enumerate(iterable):
  File "/Users/ornew/opt/brew/lib/python2.7/site-packages/tensorflow/python/lib/io/tf_record.py", line 81, in tf_record_iterator
    reader.GetNext()
  File "/Users/ornew/opt/brew/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 470, in GetNext
    return _pywrap_tensorflow_internal.PyRecordReader_GetNext(self)
DataLossError: corrupted record at 0
E0921 23:51:35.055788 123145350647808 _internal.py:87] Error on request:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_ornew/c3f3524115bcb8d4f5cdb704ea3abfbd/external/org_pocoo_werkzeug/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/private/var/tmp/_bazel_ornew/c3f3524115bcb8d4f5cdb704ea3abfbd/external/org_pocoo_werkzeug/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/Users/ornew/src/github.com/tensorflow/tensorboard/tensorboard/backend/application.py", line 298, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/private/var/tmp/_bazel_ornew/c3f3524115bcb8d4f5cdb704ea3abfbd/external/org_pocoo_werkzeug/werkzeug/wrappers.py", line 291, in application
    return f(*args[:-2] + (request,))(*args[-2:])
  File "/Users/ornew/src/github.com/tensorflow/tensorboard/tensorboard/plugins/interactive_inference/interactive_inference_plugin.py", line 132, in _examples_from_path_handler
    examples_path, examples_count, parse_examples=False)
  File "/Users/ornew/src/github.com/tensorflow/tensorboard/tensorboard/plugins/interactive_inference/utils/platform_utils.py", line 95, in example_protos_from_path
    append_examples_from_iterable(record_iterator, examples)
  File "/Users/ornew/src/github.com/tensorflow/tensorboard/tensorboard/plugins/interactive_inference/utils/platform_utils.py", line 83, in append_examples_from_iterable
    for i, value in enumerate(iterable):
  File "/Users/ornew/opt/brew/lib/python2.7/site-packages/tensorflow/python/lib/io/tf_record.py", line 81, in tf_record_iterator
    reader.GetNext()
  File "/Users/ornew/opt/brew/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 470, in GetNext
    return _pywrap_tensorflow_internal.PyRecordReader_GetNext(self)
DataLossError: corrupted record at 0
```

I'm using **GZIP-compressed TFRecord**. This errors is happen because the TFRecord option has not compression type option.

I think that this is an excellent tool. Please implement the compression support. Thanks.

**Comment by nfelt** [comment]
cc @jameswex

**Comment by jameswex** [comment]
@ornew Thanks for the feedback! We can definitely enable handling of gzip'd tfrecord files. Have you had success using the tool on your model(s) and dataset(s) outside of this issue?
