### ISSUE TITLE
hparams_demo fails

### ISSUE THREAD

**Issue by dvisztempacct** [tensorflow/tensorboard#1564]
- TensorBoard version (from pip package, also printed out when running `tensorboard`)
master 

 - TensorFlow version if different from TensorBoard
1.13.0-dev20181029

 - OS Platform and version (e.g., Linux Ubuntu 16.04)
PopOS/Ubuntu 18.04 (Bionic Beaver)

 - Python version (e.g. 2.7, 3.5)
3.6.6

The hparams demo blows up:

```
$ bazel run //tensorboard/plugins/hparams:hparams_demo
INFO: Analysed target //tensorboard/plugins/hparams:hparams_demo (1 packages loaded).
INFO: Found 1 target...
INFO: From ProtoCompile tensorboard/plugins/hparams/api_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
Target //tensorboard/plugins/hparams:hparams_demo up-to-date:
  bazel-bin/tensorboard/plugins/hparams/hparams_demo
INFO: Elapsed time: 0.372s, Critical Path: 0.08s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 5 total actions
INFO: Build completed successfully, 5 total actions
Saving output to /tmp/hparams_demo.
Traceback (most recent call last):
  File "/home/hdon/.cache/bazel/_bazel_hdon/0e9c8747cc35d934dc6a232cd28e2c66/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/plugins/hparams/hparams_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/hparams/hparams_demo.py", line 219, in <module>
    tf.app.run()
  File "/home/hdon/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/hdon/.cache/bazel/_bazel_hdon/0e9c8747cc35d934dc6a232cd28e2c66/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/plugins/hparams/hparams_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/hparams/hparams_demo.py", line 214, in main
    run_all(LOGDIR, verbose=True)
  File "/home/hdon/.cache/bazel/_bazel_hdon/0e9c8747cc35d934dc6a232cd28e2c66/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/plugins/hparams/hparams_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/hparams/hparams_demo.py", line 200, in run_all
    group_name = fingerprint(hparam_str)
  File "/home/hdon/.cache/bazel/_bazel_hdon/0e9c8747cc35d934dc6a232cd28e2c66/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/plugins/hparams/hparams_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/hparams/hparams_demo.py", line 49, in fingerprint
    m.update(string)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by dvisztempacct** [comment]
I can't figure out how to see the results of the demo in Tensorboard. I can see scalars, but I don't see anything about hparams. Any help would be greatly appreciated!

**Comment by philippHRO** [comment]
I have the same problems. teh HParams tab isn't showing up in Tensorboard.

```
tb-nightly                1.14.0a20190313
tensorboard               1.13.1
tensorflow-estimator-2-0-preview 1.14.0.dev2019031400
tf-nightly-2-0-preview    2.0.0.dev20190313
```
