### ISSUE TITLE
long responding time when reload_interval is 0

### ISSUE THREAD

**Issue by tjsongzw** [tensorflow/tensorboard#166]
Hi,

if `reload_interval` is 0, tensorboard waits for the all files loaded, while in the non-zero situation, the loading process works in another thread and return 'immediately', does it make sense to put the zero one in the another thread as well?

**Comment by dandelionmane** [comment]
Why do you want reload_interval to be 0?

**Comment by tjsongzw** [comment]
the process was, first I would like to have a "meta" service which is responsible for calling up tensorboard servers(something like a multitenant fashion, seems #92 would cover this), here #167, if I go with the default setting(5), I saw another thread loading data in background even though I do `tb-server.shutdown()`, then I say ok, only display already existing data, and put the interval to 0, I awaited an unexpected longer time there, so I got this concern and the relevant one #167

**Comment by dandelionmane** [comment]
You're welcome to send us a pull request that fixes the behavior when reload_interval is 0. But, if you're able to wait, I would suggest waiting until @jart finishes her work on #92. Her solution will be more robust and scalable, since it will be first-class integrated in TensorBoard.

**Comment by jart** [comment]
Yes TensorBoard as it exists right now isn't really conducive to being run as a production service. My top priority right now is changing that fact.

**Comment by tjsongzw** [comment]
Hi Dandelion, Justine thanks for your responses!

I was trying to make some modifications, and built from source,

```
bazel build tensorboard:tensorboard
bazel run //tensorboard/plugins/scalars:scalars_demo
./bazel-bin/tensorboard/tensorboard --logdir /tmp/scalars_demo
```

then came across,

```
❯ ./bazel-bin/tensorboard/tensorboard --logdir /tmp/scalars_demo
Starting TensorBoard 0.1.3 at http://unix.local:6006
(Press CTRL+C to quit)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/songzw/.anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/songzw/.anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/songzw/Documents/Package/tensorboard/bazel-bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/application.py", line 308, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/Users/songzw/Documents/Package/tensorboard/bazel-bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/application.py", line 282, in reload_multiplexer
    multiplexer.Reload()
  File "/Users/songzw/Documents/Package/tensorboard/bazel-bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/event_processing/event_multiplexer.py", line 189, in Reload
    accumulator.Reload()
  File "/Users/songzw/Documents/Package/tensorboard/bazel-bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/event_processing/event_accumulator.py", line 239, in Reload
    self._ProcessEvent(event)
  File "/Users/songzw/Documents/Package/tensorboard/bazel-bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/event_processing/event_accumulator.py", line 371, in _ProcessEvent
    if value.HasField('metadata'):
  File "/private/var/tmp/_bazel_songzw/3b7db6970a8f89ea02c8b7f0306648fa/execroot/tensorboard/bazel-out/local-fastbuild/bin/tensorboard/tensorboard.runfiles/protobuf/python/google/protobuf/internal/python_message.py", line 810, in HasField
    raise ValueError(error_msg % field_name)
ValueError: Protocol message has no non-repeated submessage field "metadata"
```
looks like a protocol buffer problem

my working environment,
```
❯ python -c 'import google.protobuf; print(google.protobuf.__version__)'
3.3.0
❯ protoc --version
libprotoc 3.2.0
❯ uname -a
Darwin unix.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64 i386 MacBookPro11,1 Darwin
```
any clue?

**Comment by dandelionmane** [comment]
The version of TensorBoard in this repo won't be compatible with mainline TensorFlow until 1.3. For development right now, you need to install the tf nightly build. Look at the tensorflow readme for an up-to-date url.

**Comment by jart** [comment]
I'm going to close this one out because, if it's taking awhile even when `reload_interval` is 0, it might be due to the log dirs being huge. There's `du -sh /tmp/logdir` and `tensorboard --inspect` to help you learn more.

I've been working lately on the new summaries API, where I'm going to be implementing support for fancier congestion control that will give you more power over how summaries get logged. That's going to take a while. Until then, the best thing to do is use those troubleshooting steps and try to limit summary data, if it becomes problematic.

**Comment by tjsongzw** [comment]
Hi Justine, Dandelion, got it! Thanks!
