### ISSUE TITLE
Tensoboard not launching tensorflow.python.framework.errors_impl.PermissionDeniedError:

### ISSUE THREAD

**Issue by storopoli** [tensorflow/tensorboard#1680]
Hello!

I am trying to launch tensorboard without success. I am running a MBP with Mojave and anaconda latest version. Tried already to wipe out TensorFlow installation and running it in a clean new environment. Installed using conda install tensorflow.

I am getting this error, can you guys help me out to fix it.

```
TensorBoard 1.12.0 at http://duda-mbp.hbs.edu:6006 (Press CTRL+C to quit)
Exception in thread Reloader:
Traceback (most recent call last):
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorboard/backend/application.py", line 386, in _reload
    multiplexer.AddRunsFromDirectory(path, name)
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 181, in AddRunsFromDirectory
    for subdir in io_wrapper.GetLogdirSubdirectories(path):
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorboard/backend/event_processing/io_wrapper.py", line 194, in <genexpr>
    subdir
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorboard/backend/event_processing/io_wrapper.py", line 151, in ListRecursivelyViaWalking
    for dir_path, _, filenames in tf.gfile.Walk(top):
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 535, in walk
    for subitem in walk(os.path.join(top, subdir), in_order):
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 535, in walk
    for subitem in walk(os.path.join(top, subdir), in_order):
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 535, in walk
    for subitem in walk(os.path.join(top, subdir), in_order):
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 516, in walk
    listing = list_directory(top)
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 494, in list_directory
    compat.as_bytes(dirname), status)
  File "/Users/storopoli/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /Users/storopoli/Library/Application Support/CallHistoryTransactions; Operation not permitted
```

**Comment by nfelt** [comment]
This looks like a permissions error with the directory /Users/storopoli/Library/Application Support/CallHistoryTransactions.  I'm guessing it's due to the Mojave private directory feature: https://www.howtogeek.com/361707/how-macos-mojaves-privacy-protection-works/

If you can avoid running with a logdir that contains a privacy-protected directory, that should help.  You might also be able to whitelist the tensorboard binary for access to that data.

**Comment by storopoli** [comment]
I'm trying to whitelist it. But to no avail.
```
codesign -dr - /Users/storopoli/Library/Application\ Support/CallHistoryTransactions
```

Is this right?

**Comment by storopoli** [comment]
No use of adding the binaries.
But I've managed to do run it specifying the exact directory of the notebook.
```
tensorboard --logdir /Users/storopoli/Documents/Jupyter_Notebooks/tensorflow
```

Thank you so much

**Comment by nfelt** [comment]
Sure.  I'll reframe this issue as TensorBoard needing better behavior around mojave's protected directories.
