### ISSUE TITLE
Fix fun new Bazel 0.21 incompatibilities

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#1710]
’Tis the season to forcibly roll out a new Bazel version with
incompatible changes to our dependencies, requiring a transitive
upgrade:

    $ bazel version 2>/dev/null | grep label
    Build label: 0.21.0
    $ bazel query 'deps(//tensorboard)' 2>&1 | cat
    INFO: Invocation ID: e16749ec-4a81-4291-aefb-7afadf078f2b
    Loading: 0 packages loaded
    ERROR: /usr/local/google/home/wchargin/.bazel-output-base/external/com_google_protobuf/BUILD:591:1: Traceback (most recent call last):
            File "/usr/local/google/home/wchargin/.bazel-output-base/external/com_google_protobuf/BUILD", line 591
                    internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
            File "/usr/local/google/home/wchargin/.bazel-output-base/external/com_google_protobuf/protobuf.bzl", line 269, in internal_gen_well_known_p
    rotos_java
                    Label(("%s//protobuf_java" % REPOSITOR...))
            File "/usr/local/google/home/wchargin/.bazel-output-base/external/com_google_protobuf/protobuf.bzl", line 269, in Label
                    REPOSITORY_NAME
    The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skyla
    rk/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
    ERROR: Evaluation of query "deps(//tensorboard)" failed: errors were encountered while computing transitive closure
    Loading: 3 packages loaded

**Comment by wchargin** [comment]
This appears to induce not just broken builds but also failing tests:

    $ gpg --verify --multifile ~/Downloads/bazel-0.{20,21}.0-linux-x86_64.sig
    gpg: assuming signed data in '/usr/local/google/home/wchargin/Downloads/bazel-0.20.0-linux-x86_64'
    gpg: Signature made Fri 30 Nov 2018 06:52:40 AM PST
    gpg:                using RSA key 71A1D0EFCFEB6281FD0437C93D5919B448457EE0
    gpg: Good signature from "Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>" [full]
    gpg: assuming signed data in '/usr/local/google/home/wchargin/Downloads/bazel-0.21.0-linux-x86_64'
    gpg: Signature made Wed 19 Dec 2018 05:58:23 AM PST
    gpg:                using RSA key 71A1D0EFCFEB6281FD0437C93D5919B448457EE0
    gpg: Good signature from "Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>" [full]

    wchargin@apotheosis[@1545347795][^0][tensorflow-nightly-20181220-py2][927fa1b0]:~/git/tensorboard
    $ ~/Downloads/bazel-0.21.0-linux-x86_64 test --incompatible_package_name_is_a_function=false //tensorboard/util:util_test
    INFO: Invocation ID: b1bfcef1-6b87-46da-8687-d96fa14a5686
    INFO: Analysed target //tensorboard/util:util_test (29 packages loaded, 952 targets configured).
    INFO: Found 1 test target...
    INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/any_pb2.py:
    external/com_google_protobuf/python: warning: directory does not exist.
    INFO: From ProtoCompile tensorboard/compat/proto/allocation_description_pb2.py:
    external/com_google_protobuf/python: warning: directory does not exist.
    FAIL: //tensorboard/util:util_test (see /usr/local/google/home/wchargin/.bazel-output-base/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/testlogs/tensorboard/util/util_test/test.log)
    INFO: From Testing //tensorboard/util:util_test:
    ==================== Test output for //tensorboard/util:util_test:
    Traceback (most recent call last):
      File "/usr/local/google/home/wchargin/.bazel-output-base/sandbox/linux-sandbox/170/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/util/util_test.runfiles/org_tensorflow_tensorboard/tensorboard/util/util_test.py", line 24, in <module>
        import tensorflow as tf
    ImportError: No module named tensorflow
    ================================================================================
    Target //tensorboard/util:util_test up-to-date:
      bazel-bin/tensorboard/util/util_test
    INFO: Elapsed time: 167.737s, Critical Path: 30.54s
    INFO: 170 processes: 170 linux-sandbox.
    INFO: Build completed, 1 test FAILED, 180 total actions
    //tensorboard/util:util_test                                             FAILED in 0.2s
      /usr/local/google/home/wchargin/.bazel-output-base/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/testlogs/tensorboard/util/util_test/test.log

    INFO: Build completed, 1 test FAILED, 180 total actions

    wchargin@apotheosis[@1545347968][^3][tensorflow-nightly-20181220-py2][927fa1b0]:~/git/tensorboard
    $ ~/Downloads/bazel-0.20.0-linux-x86_64 test --incompatible_package_name_is_a_function=false //tensorboard/util:util_test
    Starting local Bazel server and connecting to it...
    INFO: Invocation ID: 8e331d4a-6e37-4b9c-9845-c05937d3298b
    INFO: Analysed target //tensorboard/util:util_test (27 packages loaded, 941 targets configured).
    INFO: Found 1 test target...
    INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/any_pb2.py:
    external/com_google_protobuf/python: warning: directory does not exist.
    INFO: From ProtoCompile tensorboard/compat/proto/allocation_description_pb2.py:
    external/com_google_protobuf/python: warning: directory does not exist.
    Target //tensorboard/util:util_test up-to-date:
      bazel-bin/tensorboard/util/util_test
    INFO: Elapsed time: 171.890s, Critical Path: 43.33s
    INFO: 170 processes: 170 linux-sandbox.
    INFO: Build completed successfully, 180 total actions
    //tensorboard/util:util_test                                             PASSED in 1.1s

    INFO: Build completed successfully, 180 total actions

    wchargin@apotheosis[@1545348412][^0][tensorflow-nightly-20181220-py2][927fa1b0]:~/git/tensorboard
    $ python -c 'import tensorflow as tf; print(tf.version.VERSION)'
    1.13.0-dev20181220

**Comment by wchargin** [comment]
This was due to the action_env change in Bazel 0.21, whereby `PATH` was
not forwarded to the test environment, thus breaking virtualenv setups.
This change was reverted in Bazel 0.22.
