### ISSUE TITLE
Error launching TensorBoard on Windows due to `%s` strftime specifier

### ISSUE THREAD

**Issue by Origamichen** [tensorflow/tensorboard#1895]
TensorBoard version: 1.13.0
Tensorflow version: tensorflow-gpu 1.13.0rc2
OS Platform and version: Windows10 1803
Python version: 3.7

Hi,
Here's a minor error occurs when I run tensorboard 1.13.0. It is fixed by changing **line 50** in tensorboard/manager.py
`serialize=lambda dt: int(dt.strftime("%s")),` to `serialize=lambda dt: int(dt.strftime("%S")),`
The "%s" is changed to "%S". 

> Traceback (most recent call last):
  File "d:\programme\anaconda\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programme\anaconda\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Workspace\Python\TensorflowVenv\TfEnv\Scripts\tensorboard.exe\__main__.py", line 9, in <module>
  File "d:\workspace\python\tensorflowvenv\tfenv\lib\site-packages\tensorboard\main.py", line 57, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "d:\workspace\python\tensorflowvenv\tfenv\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "d:\workspace\python\tensorflowvenv\tfenv\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "d:\workspace\python\tensorflowvenv\tfenv\lib\site-packages\tensorboard\program.py", line 228, in main
    self._register_info(server)
  File "d:\workspace\python\tensorflowvenv\tfenv\lib\site-packages\tensorboard\program.py", line 274, in _register_info
    manager.write_info_file(info)
  File "d:\workspace\python\tensorflowvenv\tfenv\lib\site-packages\tensorboard\manager.py", line 268, in write_info_file
    payload = "%s\n" % _info_to_string(tensorboard_info)
  File "d:\workspace\python\tensorflowvenv\tfenv\lib\site-packages\tensorboard\manager.py", line 128, in _info_to_string
    for k in _TENSORBOARD_INFO_FIELDS
  File "d:\workspace\python\tensorflowvenv\tfenv\lib\site-packages\tensorboard\manager.py", line 128, in <dictcomp>
    for k in _TENSORBOARD_INFO_FIELDS
  File "d:\workspace\python\tensorflowvenv\tfenv\lib\site-packages\tensorboard\manager.py", line 50, in <lambda>
    serialize=lambda dt: int(dt.strftime("%s")),
ValueError: Invalid format string

**Comment by xieyonglu** [comment]
Find the manger.py file in directory ..\Lib\site-packages\tensorboard，and modify dt.strftime("%s") to dt.strftime("%S")

**Comment by stephanwlee** [comment]
@wchargin can you please TAL? It seems like something we should be able to fix.

**Comment by nfelt** [comment]
Hm, it looks like `%s` isn't actually cross-platform :( https://stackoverflow.com/a/11743262/1179226

The recommended workarounds are truly sad, but I guess we should change it to one of those.

FWIW, changing to `%S` (number of seconds, 0-59) is not a working replacement.  @Origamichen @xieyonglu If you want a temporary workaround it's better to replace it with `dt.strftime("0")` which at least will consistently be the start of the unix Epoch instead of somewhere between 0-60 seconds after it.

**Comment by israfila3** [comment]
you can change the ("strftime("%s") to strftime("%S") ==>  %s to %S") on line 50 in (site-packages\tensorboard\manager.py )

**Comment by wchargin** [comment]
@israfila3: As noted above, that is not a sound replacement. Please see
@nickfelt’s comment if you want an immediate workaround. We plan to
release a TensorBoard 1.13.1 patch shortly (probably today) that will
contain the fix for this.
