### ISSUE TITLE
//tensorboard/plugins/graph:keras_util_test failing at master

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2051]
Can repro at cf76398963491f01ac92 with tf-nightly-20190325-py2.7.

Diff:

```
-   input: "model/func_seq_input"
+   input: "model/[u\'func_seq_input\', 0, 0, {}]"
```

Full traceback:

```
Traceback (most recent call last):
  File "/usr/local/google/home/wchargin/virtualenv/tf-nightly-20190325-py2.7/local/lib/python2.7/site-packages/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/usr/local/google/home/wchargin/virtualenv/tf-nightly-20190325-py2.7/local/lib/python2.7/site-packages/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "/usr/local/google/home/wchargin/.bazel-output-base/sandbox/linux-sandbox/26/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/plugins/graph/keras_util_test.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/graph/keras_util_test.py", line 769, in test_keras_model_to_graph_def_functional_sequential_model
    self.assertGraphDefToModel(expected_proto, model)
  File "/usr/local/google/home/wchargin/.bazel-output-base/sandbox/linux-sandbox/26/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/plugins/graph/keras_util_test.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/graph/keras_util_test.py", line 36, in assertGraphDefToModel
    expected_proto, keras_util.keras_model_to_graph_def(model_config))
  File "/usr/local/google/home/wchargin/virtualenv/tf-nightly-20190325-py2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 1657, in assertProtoEquals
    self._AssertProtoEquals(expected_message, message, msg=msg)
  File "/usr/local/google/home/wchargin/virtualenv/tf-nightly-20190325-py2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 1634, in _AssertProtoEquals
    compare.assertProtoEqual(self, a, b, normalize_numbers=True, msg=msg)
  File "/usr/local/google/home/wchargin/virtualenv/tf-nightly-20190325-py2.7/local/lib/python2.7/site-packages/tensorflow/python/util/protobuf/compare.py", line 113, in assertProtoEqual
    self.assertMultiLineEqual(a_str, b_str, msg=msg)
  File "/usr/local/google/home/wchargin/virtualenv/tf-nightly-20190325-py2.7/local/lib/python2.7/site-packages/absl/testing/absltest.py", line 979, in assertMultiLineEqual
    raise self.failureException(''.join(failure_message))
AssertionError: 
  node {
    name: "model/func_seq_input"
    attr {
      key: "dtype"
      value {
        type: DT_FLOAT
      }
    }
    attr {
      key: "keras_class"
      value {
        s: "InputLayer"
      }
    }
  }
  node {
    name: "model/sequential/dense"
-   input: "model/func_seq_input"
+   input: "model/[u\'func_seq_input\', 0, 0, {}]"
?                 ++++              +++++++++++++
    attr {
      key: "dtype"
      value {
        type: DT_FLOAT
      }
    }
    attr {
      key: "keras_class"
      value {
        s: "Dense"
      }
    }
  }
  node {
    name: "model/sequential/my_relu"
    input: "model/sequential/dense"
    attr {
      key: "dtype"
      value {
        type: DT_FLOAT
      }
    }
    attr {
      key: "keras_class"
      value {
        s: "Activation"
      }
    }
  }
  node {
    name: "model/dense_1"
    input: "model/sequential/my_relu"
    attr {
      key: "dtype"
      value {
        type: DT_FLOAT
      }
    }
    attr {
      key: "keras_class"
      value {
        s: "Dense"
      }
    }
  }
```

**Comment by wchargin** [comment]
From `git log `v1.12.0-10848-g76e879d1c1..v1.12.0-10950-g840022b021`,
the root cause seems to be 90f1ed7cd3ae167b60c1b0acc6f45af454c8d592,
whose Google-internal version <http://cl/239834276> includes a change to
`keras_util.py` that has not yet been synced out. Making this change
fixes the test.
