### ISSUE TITLE
Beholder: how does Resize.initialize_graph even work

### ISSUE THREAD

**Issue by comzyh** [tensorflow/tensorboard#2073]
tensorflow and tensorboard versions:
```
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1
tensorflow-tensorboard==0.4.0
```

 - OS Platform and version: ubuntu 18.04.2
 - Python version Python 3.6
 
I notice that in Resizer.initialize_graph, you use two placeholders **without** shape as parameters of tf.image.resize
https://github.com/tensorflow/tensorboard/blob/c8b2f5761fd8e9eba6d1c70fae965fe2f970cd2d/tensorboard/plugins/beholder/im_util.py#L119-L124

but in tensorflow code, resize_image always try to get the shape of the tensor.

https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/python/ops/image_ops_impl.py#L1019-L1042

```python
    if images.get_shape().ndims is None:
      raise ValueError('\'images\' contains no shape.')
```

Once I use beholder, I always get an error 

```
Traceback (most recent call last):
  File "test_beholder.py", line 14, in <module>
    beholder.update(session=sess, arrays=[array])
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorboard/plugins/beholder/beholder.py", line 174, in update
    final_image = self._update_frame(session, arrays, frame, new_config)
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorboard/plugins/beholder/beholder.py", line 131, in _update_frame
    final_image = self._get_final_image(session, config, arrays, frame)
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorboard/plugins/beholder/beholder.py", line 112, in _get_final_image
    final_image = self.visualizer.build_frame(arrays)
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorboard/plugins/beholder/visualizer.py", line 300, in build_frame
    sections = self._arrays_to_sections(arrays)
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorboard/plugins/beholder/visualizer.py", line 221, in _arrays_to_sections
    image_width)
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorboard/util/op_evaluator.py", line 103, in __call__
    self._lazily_initialize()
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorboard/util/op_evaluator.py", line 79, in _lazily_initialize
    self.initialize_graph()
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorboard/plugins/beholder/im_util.py", line 124, in initialize_graph
    method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorflow/python/ops/image_ops_impl.py", line 960, in resize_images
    name=None)
  File "/home/comzyh/.local/lib/python3.6/site-packages/tensorflow/python/ops/image_ops_impl.py", line 1022, in resize_images_v2
    raise ValueError('\'images\' contains no shape.')
ValueError: 'images' contains no shape.
```

here is minimum reproduce:

```python
import tensorflow as tf
import numpy as np
from tensorboard.plugins.beholder import Beholder
import time

if __name__ == '__main__':
    beholder = Beholder('/tmp/test_beholder')
    array = np.array([[0, 1], [1, 0]])
    with tf.Session() as sess:
        var1 = tf.Variable([0, 0], trainable=True)
        init_op = tf.global_variables_initializer()
        sess.run([init_op])
        time.sleep(1)
        beholder.update(session=sess, arrays=[array])
```

**Comment by wchargin** [comment]
Hi @comzyh! Thanks for the bug report, and thanks for the clear repro
script. You’re right: this is broken as of #1734. The `tf.image.resize`
function used to allow dynamically shaped images, and the version
exposed under `tf.compat.v1.image.resize_nearest_neighbor` still does,
but the new `tf.image.resize` does not.

@stephanwlee, should we revert this part of #1734 and add a test case in
the style of @comzyh’s MWE?

**Comment by wchargin** [comment]
(You can verify that this is the problem by noting that both your MWE
and the `beholder_demo.py` in the TensorBoard repository work in a fresh
virtualenv with `tensorflow==1.13.0rc2` but not `tensorflow==1.13.1`,
and that if you subsequently patch `im_util.py` in your virtualenv’s
site packages to revert the patch in #2073 then both scripts do work.)

**Comment by stephanwlee** [comment]
Dang, it looks like the implementation of the API changed in a breaking way. Let's revert #1734 and address this issue. @wchargin would you have time to do that? I am a bit swamped :(

**Comment by nfelt** [comment]
FYI there's a somewhat related b/112771514 internally.
