### ISSUE TITLE
When I used tensorboard as tensorboard --logdir=logs ,it told me that

### ISSUE THREAD

**Issue by ZZM37** [tensorflow/tensorboard#2086]
When I used tensorboard as tensorboard --logdir=logs ,it told me that
`D:\workspace\python\Human-Detection_by_tiny_YoLo_v3>tensorboard --logdir=logs
Traceback (most recent call last):
  File "d:\software\run\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\software\run\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\software\run\python\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "d:\software\run\python\lib\site-packages\tensorboard\main.py", line 44, in <module>
    from tensorboard import default
  File "d:\software\run\python\lib\site-packages\tensorboard\default.py", line 36, in <module>
    from tensorboard.plugins.beholder import beholder_plugin
  File "d:\software\run\python\lib\site-packages\tensorboard\plugins\beholder\__init__.py", line 15, in <module>
    from tensorboard.plugins.beholder.beholder import Beholder
  File "d:\software\run\python\lib\site-packages\tensorboard\plugins\beholder\beholder.py", line 199, in <module>
    class BeholderHook(tf.estimator.SessionRunHook):
AttributeError: module 'tensorflow.estimator' has no attribute 'SessionRunHook'`
 - TensorBoard 1.9.0
 - tensorflow-gpu1.9.0
 - win10
 - Python3.6

**Comment by amanp592** [comment]
@ZZM37 which ide do you use? anaconda or pycharm??

**Comment by ZZM37** [comment]
does it matter?I use sublime text3

**Comment by hgadig** [comment]
The reason could be due to the use of older version of tensorboard and tensorflow. Could you please try with the latest versions of both Tensorflow and Tensorboard and see if  you are running into the same error.

**Comment by wchargin** [comment]
Hi @ZZM37! The expression `tf.estimator.SessionRunHook` doesn’t actually
appear in TensorBoard 1.9.0 at all—it was `tf.train.SessionRunHook`
until #1706, which first appeared in TensorBoard 1.13.0.

It sounds like you may have multiple versions of TensorBoard installed
in the same environment (which won’t work out very well). Could you
please run `pip freeze` to list the packages in your environment?

**Comment by ZZM37** [comment]
thanks all of you!I delete tensorboard in site-packages,and reinstall tensorboard1.9.0. I don't know why but it does work!
