### ISSUE TITLE
Cannot launch tensorboard from console due to numpy issue

### ISSUE THREAD

**Issue by tolandwehr** [tensorflow/tensorboard#2092]
- TensorBoard version: 1.13.1
 - TensorFlow version: 2.0.0-alpha0
 - OS Platform and version (e.g., Linux Ubuntu 16.04):Win10
 - Python version (e.g. 2.7, 3.5):3.6

 
I'd like to make use of TensorBoard.I already saved training and validation data in the same directory as the rest of the project data using the **tensorflow.keras.callbacks** library.

When calling it via Anaconda prompt on a Win10-OS , the following happens: 

```
(tensorflow) C:\Users\alias>tensorboard --logdir=logs\
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "c:\users\alias\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alias\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\alias\AppData\Local\Programs\Python\Python36\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "c:\users\alias\appdata\local\programs\python\python36\lib\site-packages\tensorboard\main.py", line 28, in <module>
    import tensorflow as tf
  File "C:\Users\alias\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio
  File "C:\Users\alias\AppData\Roaming\Python\Python36\site-packages\tensorflow\_api\v2\audio\__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\Users\alias\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\alias\AppData\Roaming\Python\Python36\site-packages\tensorflow\core\framework\graph_pb2.py", line 15, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "C:\Users\alias\AppData\Roaming\Python\Python36\site-packages\tensorflow\core\framework\node_def_pb2.py", line 15, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\alias\AppData\Roaming\Python\Python36\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 15, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\alias\AppData\Roaming\Python\Python36\site-packages\tensorflow\core\framework\tensor_pb2.py", line 15, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\alias\AppData\Roaming\Python\Python36\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

(tensorflow) C:\Users\alias>

```

Already pip reinstalled numpy, didn't work out.

 Would be glad about some help/hints to same/similar issues.

Thanks in advance!

**Comment by wchargin** [comment]
Hi @tolandwehr! Thanks for the report. It looks like you’re running into
[this numpy issue][np] and/or [this TensorFlow issue][tf] (or something
like it)—but other people report the numpy issue as being resolved by
reinstalling numpy, which you’ve already tried. I also note that you
have the TensorFlow 2.0 preview but TensorBoard 1.13, which is a bit
strange—installing the 2.0 preview should automatically pull in the
TensorBoard 1.14.0a20190319 preview, too.

Probably the easiest solution is to blow away the virtualenv and create
a new one from scratch. If that’s not an option, then please post the
output of the following commands so that we can narrow down the problem:

[np]: https://github.com/numpy/numpy/issues/11871
[tf]: https://github.com/tensorflow/tensorflow/issues/25016

  - `python -c 'print(__import__("numpy").__version__)'`
  - `python -c 'print(__import__("tensorflow").__version__)'`
  - `python -c 'print(__import__("tensorboard.version").version.VERSION)'`
  - `pip freeze`

**Comment by tolandwehr** [comment]
@wchargin 
Thanks for the reply. Carried out the commands

```

(tensorflow) C:\Users\alias>python -c 'print(__import__("numpy").__version__)'

(tensorflow) C:\Users\alias>python -c 'print(__import__("tensorflow").__version__)'

(tensorflow) C:\Users\alias>python -c 'print(__import__("tensorboard.version").version.VERSION)'

(tensorflow) C:\Users\alias>pip freeze
Could not parse requirement: -umpy
Could not parse requirement: -ensorflow-gpu
absl-py==0.7.1
anaconda-client==1.6.14
asn1crypto==0.24.0
astor==0.7.1
backcall==0.1.0
bezier==0.8.0
bkcharts==0.2
bleach==2.1.3
bokeh==1.0.0
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.3
clyent==1.2.2
color==0.1
colorama==0.3.9
colorcet==0.9.1
cryptography==2.6.1
cycler==0.10.0
Cython==0.28.4
dash==0.26.0
dash-core-components==0.27.2
dash-html-components==0.11.0
dash-renderer==0.13.2
dask==0.18.1
datashader==0.6.6
datashape==0.5.2
decorator==4.3.0
distributed==1.22.1
entrypoints==0.2.3
enum34==1.1.6
et-xmlfile==1.0.1
Flask==1.0.2
Flask-Compress==1.4.0
gast==0.2.0
geojson==2.4.1
geomet==0.2.0.post2
google-pasta==0.1.4
grpcio==1.13.0
h5py==2.8.0
HeapDict==1.0.0
holoviews==1.10.8
html2text==2018.1.9
html5lib==1.0.1
idna==2.7
imbalanced-learn==0.3.3
imblearn==0.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
itsdangerous==0.24
jdcal==1.4
jedi==0.12.0
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-core==4.4.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
llvmlite==0.25.0
lml==0.0.1
locket==0.2.0
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==3.0.3
mistune==0.8.3
mkl-random==1.0.2
mock==2.0.0
msgpack==0.5.6
multipledispatch==0.6.0
nb-anacondacloud==1.4.0
nb-conda==2.2.0
nb-conda-kernels==2.1.0
nbconvert==5.3.1
nbformat==4.4.0
nbpresent==3.0.2
networkx==2.1
notebook==5.5.0
numba==0.40.1
numpy==1.16.2
olefile==0.45.1
openpyxl==2.5.5
packaging==17.1
pandas==0.23.4
pandocfilters==1.4.2
param==1.7.0
parso==0.2.1
partd==0.3.8
pbr==5.1.3
pickleshare==0.7.4
Pillow==5.2.0
plotly==3.1.1
prompt-toolkit==1.0.15
protobuf==3.7.1
psutil==5.4.7
pycparser==2.18
pyct==0.4.5
pyexcel==0.5.8
pyexcel-io==0.5.7
Pygments==2.2.0
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
python-dateutil==2.7.3
pytz==2018.5
pyviz-comms==0.6.0
PyWavelets==0.5.2
pywinpty==0.5.4
PyYAML==3.12
pyzmq==17.0.0
RegscorePy==1.1
requests==2.19.1
retrying==1.3.3
scikit-learn==0.19.2
scipy==1.1.0
seaborn==0.9.0
Send2Trash==1.5.0
sentinelsat==0.12.2
simplegeneric==0.8.1
six==1.11.0
sklearn==0.0
sortedcontainers==2.0.4
statsmodels==0.9.0
tb-nightly==1.14.0a20190301
tblib==1.3.2
tensorboard==1.13.1
tensorflow-estimator==1.13.0
tensorflow-gpu==2.0.0a0
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
texttable==1.4.0
tf-estimator-nightly==1.14.0.dev2019030115
toolz==0.9.0
tornado==5.0.2
tqdm==4.28.1
traitlets==4.3.2
transforms3d==0.3.1
urllib3==1.23
utm==0.4.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.2.1
win-inet-pton==1.0.1
wincertstore==0.2
xarray==0.10.8
xlrd==1.1.0
zict==0.1.3

(tensorflow) C:\Users\alias>

```

Not sure whether I did that right regarding the first three commands.

**Comment by wchargin** [comment]
I note that you have both `tensorboard` and `tb-nightly` installed:

```
tensorboard==1.13.1
tb-nightly==1.14.0a20190301
```

Each of these packages provides a different version of TensorBoard, but
Pip doesn’t really know how to handle them properly if they’re _both_
present. Please **uninstall them both** and then **reinstall** the same
version of `tb-nightly`:

```
pip uninstall -y tensorboard
pip install tb-nightly==1.14.0a20190301
```

> Not sure whether I did that right regarding the first three commands.

My bad, sorry—forgot that you were on Windows. You’ll need to swap the
quotes:

```
python -c "print(__import__('numpy').__version__)"
python -c "print(__import__('tensorflow').__version__)"
python -c "print(__import__('tensorboard.version').version.VERSION)"
```

**Comment by tolandwehr** [comment]
@wchargin Sry for the late reply. I had to do some extensive travels for work and come back to the issue right now.

```
(Tensorflow) C:\Users\alias>python -c "print(__import__('numpy').__version__)"
1.16.2

(Tensorflow) C:\Users\alias>python -c "print(__import__('tensorflow').__version__)"
2.0.0-alpha0

(Tensorflow) C:\Users\alias>python -c "print(__import__('tensorboard.version').version.VERSION)"
1.14.0a20190301
```
Pip deleting tensorboard and tb-nightly and then reinstalling tb-nightly transforms the error. It keeps on being the same regardless whether it's version posted above or the newest version:

```
(Tensorflow) C:\Users\alias>tensorboard --logdir=logs\
TensorBoard 1.14.0a20190319 at http://LAPTOP-4E1BJCAV:6006 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\alias\Anaconda3\envs\Tensorflow\Scripts\tensorboard.exe\__main__.py", line 9, in <module>
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\main.py", line 58, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\program.py", line 228, in main
    self._register_info(server)
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\program.py", line 274, in _register_info
    manager.write_info_file(info)
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\manager.py", line 269, in write_info_file
    payload = "%s\n" % _info_to_string(tensorboard_info)
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\manager.py", line 129, in _info_to_string
    for k in _TENSORBOARD_INFO_FIELDS
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\manager.py", line 129, in <dictcomp>
    for k in _TENSORBOARD_INFO_FIELDS
  File "c:\users\alias\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\manager.py", line 51, in <lambda>
    (dt - datetime.datetime.fromtimestamp(0)).total_seconds()),
OSError: [Errno 22] Invalid argument
```

**Comment by wchargin** [comment]
Okay, great. This is known (#2017) and it’s a bug in Python itself that
only occurs on Windows in Python versions 3.6.0 through 3.6.6 inclusive.
We have a patch (#2054) to work around it even on those versions, but
haven’t yet released a new version of TensorBoard with that patch. In
the meantime, please upgrade your Python to 3.6.7 or later.

See also: https://github.com/tensorflow/tensorboard/issues/1976#issuecomment-473502428

I expect this to resolve the issue, so I’m closing it—please post back
if you continue to see problems.
