### ISSUE TITLE
Broken at nightly 2.0 preview due to `raise_exception_on_not_ok_status`

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2115]
Can’t run TensorBoard with current `tf-nightly-2.0-preview`:

```
$ virtualenv -q -p python2.7 ./ve
$ . ./ve/bin/activate
(ve) $ pip install -q tf-nightly-2.0-preview 2>/dev/null
(ve) $ python -c 'print(__import__("tensorflow").__version__)'
2.0.0-dev20190416
(ve) $ tensorboard --logdir ~/tensorboard_data/images_demo/ --port 2929
W0416 11:59:16.271439 139681431492352 deprecation_wrapper.py:76] From /tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/plugins/interactive_inference/utils/platform_utils.py:70: The name train.Example is deprecated. Please use train.Example instead.

W0416 11:59:16.275100 139680972359424 deprecation_wrapper.py:76] From /tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/io_wrapper.py:178: The name io.gfile.exists is deprecated. Please use io.gfile.exists instead.

W0416 11:59:16.276161 139680972359424 deprecation_wrapper.py:76] From /tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/io_wrapper.py:182: The name io.gfile.isdir is deprecated. Please use io.gfile.isdir instead.

W0416 11:59:16.276598 139680972359424 deprecation_wrapper.py:76] From /tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/io_wrapper.py:157: The name io.gfile.walk is deprecated. Please use io.gfile.walk instead.

W0416 11:59:16.277268 139680972359424 deprecation_wrapper.py:76] From /tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/io_wrapper.py:59: The name compat.as_str_any is deprecated. Please use compat.as_str_any instead.

W0416 11:59:16.278485 139680972359424 deprecation_wrapper.py:76] From /tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/io_wrapper.py:65: The name io.gfile.listdir is deprecated. Please use io.gfile.listdir instead.

W0416 11:59:16.278996 139680972359424 deprecation_wrapper.py:76] From /tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/directory_watcher.py:91: The name errors.OpError is deprecated. Please use errors.OpError instead.

Exception in thread Reloader:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/application.py", line 390, in _reload
    multiplexer.Reload()
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 240, in Reload
    Worker()
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 218, in Worker
    accumulator.Reload()
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 177, in Reload
    for event in self._generator.Load():
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 89, in Load
    for event in self._LoadInternal():
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 109, in _LoadInternal
    self._InitializeLoader()
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 168, in _InitializeLoader
    self._SetPath(path)
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 192, in _SetPath
    self._loader = self._loader_factory(path)
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 41, in __init__
    with tf.errors.raise_exception_on_not_ok_status() as status:
  File "/tmp/tmp.PISDTVYzAQ/ve/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation_wrapper.py", line 79, in __getattr__
    return getattr(self._dw_wrapped_module, name)
AttributeError: 'module' object has no attribute 'raise_exception_on_not_ok_status'

TensorBoard 1.14.0a20190416 at http://HOSTNAME:2929 (Press CTRL+C to quit)
```

Hitting the server at that port gives 500s with the same error, and
fails to load any plugins that depend on the multiplexer. The projector
still works.

**Comment by wchargin** [comment]
Probably related:
<https://github.com/tensorflow/tensorflow/commit/ea3f474c5ff94152f72b5417eff2046111bb77e3>

**Comment by nfelt** [comment]
Hmm, Travis is still green.  Is this due to caching or is there no test that actually covers this failure?

**Comment by wchargin** [comment]
The smoke test doesn’t catch it because it points at an empty
(nonexistent) logdir, which never hits the bad path because there are no
event files to load.

**Comment by nfelt** [comment]
But this should be covered by event_file_loader_test.py shouldn't it?  I think I'll try clearing the travis cache for master and rerunning.

**Comment by nfelt** [comment]
Confirmed that it failed when re-run with a fresh cache.

**Comment by wchargin** [comment]
Self-assigning because this is blocking some work that I want to do; if
someone else wants to take this, let me know and I can use an older
nightly for now.

**Comment by wchargin** [comment]
This is, unfortunately, not entirely trivial. Using `tf.compat.v1` fixes
the problem in builds that depend on TensorFlow, but the notf tests are
(rightly) failing because our stub does not provide `.compat.v1.errors`;
it only provides an empty `.compat.v1` module.

I propose a new lazy-loaded module `tensorboard.compat.tf1`, which would
be analogous to the existing `tf2` module except that it guards against
the version either being `/1\..*/` or `"stub"`, because the stub itself
implements a TF 1.x API. @nfelt, does this sound sane to you?

This is actually a special case of a larger problem: any module that
uses `from tensorboard.compat import tf` and then dereferences any
symbol like `tf.compat.v1.*` will fail when the stub is in use.
Currently, this is just two files:

```
$ comm -12 \
> <(git grep --name-only 'from tensorboard.compat import tf$' '*.py' | sort) \
> <(git grep --name-only 'tf.compat.v[12]' | sort)
tensorboard/backend/event_processing/db_import_multiplexer.py
tensorboard/plugins/projector/projector_plugin.py
```

I don’t intend to fix those in this same change; I merely intend to not
break the existing notf tests.

**Comment by nfelt** [comment]
I think we could just change the stub `__init__.py` to assign `errors` to `compat.v1.errors`, the same way that `pywrap_tensorflow` worked before it was made unnecessary by #2096.  Using the existing stub framework seems a little better to me than creating yet more lazy-loaded modules.

The larger solution to the larger problem is https://github.com/tensorflow/tensorboard/issues/1718, and for this specific issue, https://github.com/tensorflow/tensorboard/issues/1711.

**Comment by wchargin** [comment]
Yes, that also works, and makes sense to me. Thanks for the suggestion.
