### ISSUE TITLE
What If Tool for Tensorflow 2.0

### ISSUE THREAD

**Issue by ncoop57** [tensorflow/tensorboard#2330]
Currently using `tensorflow 2.0.0a0` and attempting to run the WIT walk through for the Jupyter Notebook, however, I run into the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-d2513a2af1ac> in <module>
     15 config_builder = WitConfigBuilder(test_examples).set_estimator_and_feature_spec(
     16     classifier, feature_spec).set_label_vocab(['Under 50K', 'Over 50K'])
---> 17 WitWidget(config_builder, height=tool_height_in_px)

/usr/local/lib/python3.5/dist-packages/witwidget/notebook/jupyter/wit.py in __init__(self, config_builder, height)
     57     """
     58     widgets.DOMWidget.__init__(self, layout=Layout(height='%ipx' % height))
---> 59     base.WitWidgetBase.__init__(self, config_builder)
     60 
     61     # Ensure the visualization takes all available width.

/usr/local/lib/python3.5/dist-packages/witwidget/notebook/base.py in __init__(self, config_builder)
     37       config_builder: WitConfigBuilder object containing settings for WIT.
     38     """
---> 39     tf.logging.set_verbosity(tf.logging.WARN)
     40     config = config_builder.build()
     41     copied_config = dict(config)

AttributeError: module 'tensorflow' has no attribute 'logging'

```

from running the following code snippet:

```
num_datapoints = 2000  #@param {type: "number"}
tool_height_in_px = 1000  #@param {type: "number"}

from witwidget.notebook.visualization import WitConfigBuilder
from witwidget.notebook.visualization import WitWidget

# Load up the test dataset
test_csv_path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test'
test_df = pd.read_csv(test_csv_path, names=csv_columns, skipinitialspace=True,
  skiprows=1)
make_label_column_numeric(test_df, label_column, lambda val: val == '>50K.')
test_examples = df_to_examples(test_df[0:num_datapoints])

# Setup the tool with the test examples and the trained classifier
config_builder = WitConfigBuilder(test_examples).set_estimator_and_feature_spec(
    classifier, feature_spec).set_label_vocab(['Under 50K', 'Over 50K'])
WitWidget(config_builder, height=tool_height_in_px)
```

and I believe the issue to be due to the `witwidget` 1.1 version is not compatible with tensorflow 2.0 since many of the namespaces have changed including the logging namespace.

I would very much like it to have a what if tool version compatible with Tensorflow 2.0.

**Comment by stephanwlee** [comment]
@ncoop57, thanks for creating the issue. I've faced similar issue when using `path to example`.

```sh
AttributeError: 'module' object has no attribute 'FixedLenFeature'
E0607 09:28:28.109704 139820741883648 _internal.py:87] Error on request:
Traceback (most recent call last):
  File "somedir/.cache/bazel/_bazel_stephanlee/021ba8cd11bc8fbb31c4641df016a190/external/org_pocoo_werkzeug/werkzeug/serving.py", line 205, in run_wsgi                       
    execute(self.server.app)
  File "somedir/.cache/bazel/_bazel_stephanlee/021ba8cd11bc8fbb31c4641df016a190/external/org_pocoo_werkzeug/werkzeug/serving.py", line 193, in execute                        
    application_iter = app(environ, start_response)
  File "somedir/tensorflow/tensorboard/tensorboard/backend/application.py", line 349, in __call__                                                                             
    return self.data_applications[clean_path](environ, start_response)
  File "somedir/.cache/bazel/_bazel_stephanlee/021ba8cd11bc8fbb31c4641df016a190/external/org_pocoo_werkzeug/werkzeug/wrappers.py", line 291, in application                   
    return f(*args[:-2] + (request,))(*args[-2:])
  File "somedir/tensorflow/tensorboard/tensorboard/plugins/interactive_inference/interactive_inference_plugin.py", line 153, in _examples_from_path_handler                   
    self.generate_sprite(example_strings)
  File "somedir/tensorflow/tensorboard/tensorboard/plugins/interactive_inference/interactive_inference_plugin.py", line 125, in generate_sprite                               
    if (len(self.examples) and self.image_feature_name in feature_list) else
  File "somedir/tensorflow/tensorboard/tensorboard/plugins/interactive_inference/utils/inference_utils.py", line 696, in create_sprite_image                                  
    tf.FixedLenFeature((), tf.string, default_value=''),
AttributeError: 'module' object has no attribute 'FixedLenFeature'
```
