### ISSUE TITLE
TensorBoard doesn’t build with Bazel 0.27 (and once it builds it doesn’t run)

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2355]
New incompatible flags:

```
$ ~/Downloads/bazel-0.27.0-linux-x86_64 build //tensorboard 2>&1
Loading: 0 packages loaded
Analyzing: target //tensorboard:tensorboard (0 packages loaded, 0 targets configured)
INFO: Call stack for the definition of repository 'org_pocoo_werkzeug' which is a http_archive (rule definition at /HOMEDIR/.bazel-output-base/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /HOMEDIR/git/tensorboard/third_party/python.bzl:69:5
 - /HOMEDIR/git/tensorboard/third_party/workspace.bzl:32:3
 - /HOMEDIR/git/tensorboard/WORKSPACE:70:1
ERROR: /HOMEDIR/.bazel-output-base/external/com_google_protobuf/protobuf.bzl:130:19: Traceback (most recent call last):
	File "/HOMEDIR/.bazel-output-base/external/com_google_protobuf/protobuf.bzl", line 125
		rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
	File "/HOMEDIR/.bazel-output-base/external/com_google_protobuf/protobuf.bzl", line 130, in rule
		attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
ERROR: /HOMEDIR/git/tensorboard/tensorboard/BUILD:168:1: error loading package 'tensorboard/plugins/histogram': in /HOMEDIR/git/tensorboard/tensorboard/defs/protos.bzl: Extension file 'protobuf.bzl' has errors and referenced by '//tensorboard:default'
ERROR: Analysis of target '//tensorboard:tensorboard' failed; build aborted: error loading package 'tensorboard/plugins/histogram': in /HOMEDIR/git/tensorboard/tensorboard/defs/protos.bzl: Extension file 'protobuf.bzl' has errors
INFO: Elapsed time: 0.139s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 4 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 4 targets configured)
```

The following flags suffice to get the build to work:

```
--incompatible_depset_is_not_iterable=false \
--incompatible_disable_deprecated_attr_params=false \
--incompatible_new_actions_api=false \
--incompatible_no_support_tools_in_action_inputs=false \
;
```

You need to additionally add

```
--incompatible_use_python_toolchains=false
```

for Python virtualenv imports to resolve at runtime.

It’s not obvious to me why `depset_is_not_iterable` is back, given that
we fixed those already, but I’ll look into it.

**Comment by wchargin** [comment]
Update: All the statics have been fixed, but the semantics are still
broken due to Python toolchains as described above. As of 0.28.1,
passing `--incompatible_use_python_toolchains=false` does suffice to get
everything working.

I’ve just learned that Bazel supports [workspace-level `.bazelrc`s][rc]
in addition to the standard home directory `.bazelrc`s. Indeed, after

```diff
diff --git a/.bazelrc b/.bazelrc
new file mode 100644
index 00000000..5cc98e94
--- /dev/null
+++ b/.bazelrc
@@ -0,0 +1 @@
+common --incompatible_use_python_toolchains=false
```

I can run `bazel run //tensorboard -- --logdir ~/tensorboard_data` with
no trouble on 0.28.1. (Which also means that there were no breaking
changes in 0.28—nice!) All tests pass, too. Perhaps we should adopt such
a file so that we can remain just a bit closer to stable?

[rc]: https://docs.bazel.build/versions/master/guide.html#where-are-the-bazelrc-files

**Comment by wchargin** [comment]
We now actually do build on 0.27.0 through 0.29.0rc4, so I’m going to
close this even though we rely on a `.bazelrc`.
