### ISSUE TITLE
Deleted Runs Still Show on UI

### ISSUE THREAD

**Issue by Queuecumber** [tensorflow/tensorboard#2435]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 393931f9685bd7e0f3898d7dcdf28819fef54c43

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='Puget-189551-3', release='4.15.0-50-generic', version='#54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/home/max/code/summary/venv'

--- check: installed_packages
INFO: installed: tb-nightly==1.15.0a20190708
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '1.15.0a20190708'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "diagnose_tensorboard.py", line 419, in main
    suggestions.extend(check())
  File "diagnose_tensorboard.py", line 77, in wrapper
    result = fn()
  File "diagnose_tensorboard.py", line 236, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/max/code/summary/venv/bin/tensorboard\n'

--- check: readable_fqdn
INFO: socket.getfqdn(): 'Puget-189551-3'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=109969584, st_dev=66308, st_nlink=2, st_uid=1004, st_gid=1004, st_size=4096, st_atime=1562608884, st_mtime=1563386320, st_ctime=1563386320)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/max/code/summary/venv/lib/python3.6/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.7.1
grpcio==1.22.0
Markdown==3.1.1
numpy==1.16.4
pip==9.0.1
pkg-resources==0.0.0
protobuf==3.8.0
setuptools==41.0.1
six==1.12.0
tb-nightly==1.15.0a20190708
Werkzeug==0.15.4
wheel==0.33.4

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

## Issue description

In previous tensorboard versions when I deleted a run from disk it would disappear from the UI at the next refresh. Since I updated, the deleted runs hang around and tensorboard spams

```
E0717 10:52:07.135258 140442320307968 plugin_event_multiplexer.py:220] Unable to reload accumulator 'from_dataset/Wed Jul 17 10:43:13 2019': [Errno 2] No such file or directory: b'/home/max/code/summary/from_dataset/Wed Jul 17 10:43:13 2019/events.out.tfevents.1563385393.Puget-189551
-3.34281.0' 
``` 

events on the console.

**Comment by lucaslie** [comment]
just upgraded to tensorboard 2.1 and I am suffering from the same issue. I am using tensorboard in connection with pytorch 1.2 (so I don't have tensorflow installed). Any workarounds for this issue? 

So far the only solution I have found is to manually restart tensorboard every time to get rid of deleted folders that contained event files.
