### ISSUE TITLE
Error running extract_pip_package

### ISSUE THREAD

**Issue by linzwatt** [tensorflow/tensorboard#2458]
Hi, I can build tensorboard using `bazel build //tensorboard` and I can run the compiled tb with my local changes. But I cannot get a pip package out, in order to deploy it for the rest of our team to use.

From some other issues/stackoverflow answers you build the pip package with
`bazel run //tensorboard/pip_package/extract_pip_package`

When I run this I get the error below

I have attached the output of `diagnose_tensorboard.py` here as well.

Thanks,

### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 393931f9685bd7e0f3898d7dcdf28819fef54c43

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='ip-172-31-31-96', release='4.4.0-1087-aws', version='#98-Ubuntu SMP Wed Jun 26 05:50:53 UTC 2019', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tb-nightly==1.15.0a20190724
diagnose_tensorboard.py:197: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn("no installation among: %s", sorted(family))
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '1.15.0a0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "diagnose_tensorboard.py", line 419, in main
    suggestions.extend(check())
  File "diagnose_tensorboard.py", line 77, in wrapper
    result = fn()
  File "diagnose_tensorboard.py", line 236, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/ubuntu/.miniconda/envs/tb/bin/tensorboard\n'

--- check: readable_fqdn
INFO: socket.getfqdn(): 'ip-172-31-31-96.us-west-2.compute.internal'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=528947, st_dev=51713, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1564022187, st_mtime=1564022187, st_ctime=1564022187)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (3): ['', '/home/ubuntu/tensorboard', '/home/ubuntu/.miniconda/envs/tb/lib/python3.7/site-packages']; bad_roots (2): ['', '/home/ubuntu/tensorboard']

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.7.1
certifi==2019.6.16
grpcio==1.22.0
Markdown==3.1.1
numpy==1.16.4
pip==19.1.1
protobuf==3.9.0
setuptools==41.0.1
six==1.12.0
tb-nightly==1.15.0a20190724
Werkzeug==0.15.5
wheel==0.33.4

### Suggestion: Avoid `tensorboard` packages without genfiles

Your Python path contains a `tensorboard` package that does not
include generated files. This can happen if your current directory
includes the TensorBoard source tree (e.g., you are in the TensorBoard
Git repository). The following directories from your Python path may
be problematic:

  - current directory
  - '/home/ubuntu/tensorboard' (duplicate underlying directory)
``````
</details>

## Steps to reproduce (required)

[my conda environment](https://github.com/tensorflow/tensorboard/files/3429912/environment.yml.txt)

```
(tb) ubuntu@ip-172-31-31-96:~/tensorboard$ bazel run //tensorboard/pip_package:extract_pip_package --verbose_failures
INFO: Analyzed target //tensorboard/pip_package:extract_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/ubuntu/tensorboard/tensorboard/pip_package/BUILD:8:1: Executing genrule //tensorboard/pip_package:pip_package failed (Exit 127) bash failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/9568d3f5319011cdbd0f80ae149b3174/sandbox/linux-sandbox/981/execroot/org_tensorflow_tensorboard && \
  exec env - \
    LD_LIBRARY_PATH=:/usr/local/cuda-10.1/lib64:/usr/local/cuda/extras/CUPTI/lib64 \
    PATH=/home/ubuntu/.miniconda/envs/tb/bin:/home/ubuntu/.miniconda/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/.miniconda/condabin:/home/ubuntu/.miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-10.1/bin:/home/ubuntu/bin:/usr/local/cuda-10.1/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorboard/pip_package/build_pip_package bazel-out/k8-fastbuild/bin/tensorboard/pip_package/pip_packages.tar.gz')
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
Target //tensorboard/pip_package:extract_pip_package failed to build
INFO: Elapsed time: 0.673s, Critical Path: 0.11s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by rmothukuru** [comment]
OS: Ubuntu
Tensorboard Version: tb-nightly==1.15.0a20190724

**Comment by wchargin** [comment]
Hi @linzwatt! Thanks for the clear report.

Could you modify `tensorboard/pip_package/build_pip_package.sh` to
change line 16 from `set -eu` to `set -eux`, and re-run the Bazel
command and post the output? This should give us some insight into where
exactly the build script is failing.

As a hunch, what does `type -a virtualenv` print on your machine? If I
recall correctly, Conda distributions do not bundle `virtualenv`, nor do
they require that it be installed, but our build script does require and
check that. If you don’t have it installed, try running:

```
sudo apt-get install python3-virtualenv
```

**Comment by wchargin** [comment]
Indeed, I can reproduce this failure on a fresh Ubuntu 18.04 machine
with your Conda environment, having installed `python` but not
`python-virtualenv`. After installing `python-virtualenv`, the build
completes successfully and extracts the Pip packages as desired.

I’ll improve the error handling to be more explicit, both in this case
and the general case.

**Comment by linzwatt** [comment]
Thanks for your help @wchargin virtualenv was not installed as you suspected, I tried installing via apt
```
sudo apt install python3-virtualenv
```
but still got the same error message, and after adding `-x` flag to `set -eu` I saw the more helpful error message mentioning virtualenv

I tried
```
conda install virtualenv
```
instead and it worked this time, was able to build the pip package

Thanks for your help

**Comment by wchargin** [comment]
Great—glad to hear it! Thanks for letting us know.

**Comment by wchargin** [comment]
Follow-up: I’ve adjusted the build script to dump its log on failure
(#2463), so hopefully an issue like this should be easier to debug in
the future. Thanks again for the report@
