### ISSUE TITLE
DB import fails on hparams summaries (no tensor values)

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2479]
Repro:

```python
from tensorboard.plugins.hparams import api as hp
import tensorflow as tf

with tf.summary.create_file_writer("logs").as_default():
  hp.hparams({"optimizer": "adam"})
```

```
$ tensorboard --logdir ./logs --db_import
W0730 15:11:36.556714 140142771451712 db_import_multiplexer.py:75] --db_import does not yet support purging orphaned data
Exception in thread Reloader:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/VIRTUAL_ENV/local/lib/python2.7/site-packages/tensorboard/backend/application.py", line 432, in _reload
    multiplexer.Reload()
  File "/VIRTUAL_ENV/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/db_import_multiplexer.py", line 153, in Reload
    self._event_sink.write_batch(batch)
  File "/VIRTUAL_ENV/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/db_import_multiplexer.py", line 323, in write_batch
    run_name=event_batch.run_name)
  File "/VIRTUAL_ENV/local/lib/python2.7/site-packages/tensorboard/backend/event_processing/sqlite_writer.py", line 206, in write_summaries
    tensor_util.make_ndarray(tensor_proto).tobytes())
  File "/VIRTUAL_ENV/local/lib/python2.7/site-packages/tensorboard/util/tensor_util.py", line 500, in make_ndarray
    tensor_dtype = dtypes.as_dtype(tensor.dtype)
  File "/VIRTUAL_ENV/local/lib/python2.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py", line 690, in as_dtype
    raise TypeError("Cannot convert value %r to a TensorFlow DType." % type_value)
TypeError: Cannot convert value 0 to a TensorFlow DType.

TensorBoard 1.15.0a20190730 at http://HOSTNAME:6007/ (Press CTRL+C to quit)
```

Indeed, manual inspection of the events file shows that it includes a
`Value` proto with metadata but no actual tensor value (and implicitly
[`dtype` 0, which is invalid][dt0]). This is because the HParams plugin
generates these summaries manually, in both [V1 summary ops][v1] and [V2
summary ops][v2].

[dt0]: https://github.com/tensorflow/tensorflow/blob/8e0e14bb0cad9d3f0d71b4cc7bfd487f3ae5e9a4/tensorflow/core/framework/types.proto#L13-L15
[v1]: https://github.com/tensorflow/tensorboard/blob/fbfaa250d724c387edc6aa3bb5fdb0175eed16b4/tensorboard/plugins/hparams/summary.py#L190
[v2]: https://github.com/tensorflow/tensorboard/blob/fbfaa250d724c387edc6aa3bb5fdb0175eed16b4/tensorboard/plugins/hparams/summary_v2.py#L250

Versions:

```
pip: tb-nightly==1.15.0a20190730
pip: tf-nightly-2.0-preview==2.0.0.dev20190730
python: tb.__version__ == 1.15.0a20190730
python: tf.__git_version__ == v1.12.1-7396-g12481e7e74
python: tf.__version__ == 2.0.0-dev20190730
```

**Comment by nfelt** [comment]
Obsolete, DB import mode is no more.
