### ISSUE TITLE
TensorBoard occasionally fails to start up due to error within projector plugin logic.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#269]
Occasionally, TensorBoard fails to start up due to this error (I cannot consistently reproduce it, but this issue has happened to me twice today.). My `~/Desktop/mnist-logs` directory lacks checkpoint files.

```
INFO: Running command line: bazel-bin/tensorboard/tensorboard '--logdir=~/Desktop/mnist-logs' '--port=6070'
E0725 10:47:40.872918 Thread-4 _internal.py:87] Error on request:
Traceback (most recent call last):
  File "/home/usr/agent007/.cache/bazel/_bazel_agent007/c852e2c23bf024b29ce8cb55069dafdc/external/org_pocoo_werkzeug/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/usr/agent007/.cache/bazel/_bazel_agent007/c852e2c23bf024b29ce8cb55069dafdc/external/org_pocoo_werkzeug/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/usr/agent007/Desktop/tensorboard/tensorboard/backend/application.py", line 228, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/home/usr/agent007/.cache/bazel/_bazel_agent007/c852e2c23bf024b29ce8cb55069dafdc/external/org_pocoo_werkzeug/werkzeug/wrappers.py", line 291, in application
    return f(*args[:-2] + (request,))(*args[-2:])
  File "/home/usr/agent007/Desktop/tensorboard/tensorboard/backend/application.py", line 204, in _serve_plugins_listing
    {plugin.plugin_name: plugin.is_active() for plugin in self._plugins},
  File "/home/usr/agent007/Desktop/tensorboard/tensorboard/backend/application.py", line 204, in <dictcomp>
    {plugin.plugin_name: plugin.is_active() for plugin in self._plugins},
  File "/home/usr/agent007/Desktop/tensorboard/tensorboard/plugins/projector/projector_plugin.py", line 253, in is_active
    return bool(self.multiplexer and self.configs)
  File "/home/usr/agent007/Desktop/tensorboard/tensorboard/plugins/projector/projector_plugin.py", line 265, in configs
    _latest_checkpoints_changed(self._configs, run_path_pairs)):
  File "/home/usr/agent007/Desktop/tensorboard/tensorboard/plugins/projector/projector_plugin.py", line 161, in _latest_checkpoints_changed
    if run_name not in configs:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by chihuahua** [comment]
This error might actually happen on a request right after the bazel run, but I need to verify.

**Comment by dandelionmane** [comment]
@dsmilkov please take a look

**Comment by psybuzz** [comment]
I'm unable to reproduce this on a directory without checkpoint files.  Closing this ~4 yr old issue proactively.

Looking at the projector_plugin.py code, the error shown likely happened in the past when the plugin initialized `self._configs = None`.  After https://github.com/tensorflow/tensorboard/pull/1418, the plugin now initializes the member as `self._configs = {}`, so the exact error being reproducible today is less plausible.
