### ISSUE TITLE
Get exception when open tensorboard

### ISSUE THREAD

**Issue by qrtt1** [tensorflow/tensorboard#2720]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 4725c70c7ed724e2d1b9ba5618d7c30b957ee8a4

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='jupyter-qrtt1-40infuseai-2eio', release='4.14.106+', version='#1 SMP Mon Apr 8 22:55:12 PDT 2019', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.0.0
INFO: installed: tensorflow==2.0.0
INFO: installed: tensorflow-estimator==2.0.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.0.0'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '2.0.0'
INFO: tensorflow.__git_version__: 'v2.0.0-rc2-26-g64c3d38'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/opt/conda/bin/tensorboard\n'

--- check: readable_fqdn
INFO: socket.getfqdn(): 'jupyter-qrtt1-40infuseai-2eio'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=3811759, st_dev=133, st_nlink=2, st_uid=1000, st_gid=100, st_size=4096, st_atime=1570123064, st_mtime=1570123059, st_ctime=1570123059)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/opt/conda/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.8.0
alembic==1.2.1
asn1crypto==0.24.0
astor==0.8.0
async-generator==1.10
atari-py==0.1.1
atomicwrites==1.3.0
attrs==19.2.0
backcall==0.1.0
beautifulsoup4==4.7.1
bleach==3.1.0
bokeh==1.0.4
boto==2.49.0
boto3==1.9.241
botocore==1.12.241
bs4==0.0.1
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==0.8.1
conda==4.6.14
conda-package-handling==1.6.0
cryptography==2.7
cycler==0.10.0
Cython==0.29.13
cytoolz==0.10.0
dask==1.1.5
decorator==4.4.0
defusedxml==0.6.0
dill==0.2.9
distributed==1.28.1
docutils==0.15.2
entrypoints==0.3
fastcache==1.1.0
future==0.17.1
gast==0.2.2
gensim==3.1.0
gmpy2==2.1.0b1
google-pasta==0.1.7
graphviz==0.8.2
grpcio==1.16.1
gym==0.9.7
h5py==2.9.0
HeapDict==1.0.1
idna==2.7
imageio==2.4.1
imgaug==0.2.5
importlib-metadata==0.23
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.15.1
jieba==0.39
Jinja2==2.10.1
jmespath==0.9.4
json5==0.8.5
jsonschema==3.0.2
jupyter-client==5.3.3
jupyter-core==4.4.0
jupyter-tensorboard==0.1.10
jupyterhub==0.9.6
jupyterlab==1.0.4
jupyterlab-server==1.0.6
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
llvmlite==0.27.1
locket==0.2.0
lxml==4.2.6
Mako==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.0.3
mistune==0.8.4
more-itertools==7.2.0
mpmath==1.1.0
msgpack==0.6.2
nbconvert==5.6.0
nbformat==4.4.0
nbresuse==0.3.0
networkx==2.3
nltk==3.2.5
notebook==5.7.8
numba==0.42.0
numexpr==2.6.9
numpy==1.16.2
olefile==0.46
opt-einsum==3.1.0
packaging==19.2
pamela==1.0.0
pandas==0.24.2
pandocfilters==1.4.2
parso==0.5.1
partd==1.0.0
patsy==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.0
pip==19.2.3
pluggy==0.13.0
progressbar2==3.38.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.7.1
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
pycosat==0.6.3
pycparser==2.19
pycurl==7.43.0.2
pyglet==1.4.4
Pygments==2.4.2
pyOpenSSL==19.0.0
pyparsing==2.4.2
pyrsistent==0.15.4
PySocks==1.7.1
pytest==5.2.0
python-dateutil==2.8.0
python-editor==1.0.4
python-oauth2==1.1.1
python-utils==2.3.0
pytz==2019.2
PyWavelets==1.0.3
PyYAML==5.1.2
pyzmq==18.1.0
requests==2.19.1
ruamel-yaml==0.15.71
s3transfer==0.2.1
scikit-image==0.14.3
scikit-learn==0.20.4
scipy==1.2.1
seaborn==0.9.0
Send2Trash==1.5.0
setuptools==41.2.0
six==1.12.0
smart-open==1.8.4
sortedcontainers==2.1.0
soupsieve==1.9.4
SQLAlchemy==1.3.8
statsmodels==0.9.0
sympy==1.3
tblib==1.4.0
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.0
tensorforce==0.4.3
tensorlayer==1.11.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
toolz==0.10.0
tornado==6.0.3
tqdm==4.36.1
traitlets==4.3.2
urllib3==1.23
vincent==0.4.4
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
wheel==0.33.6
widgetsnbextension==3.4.2
wrapt==1.10.11
xlrd==1.2.0
zict==1.0.0
zipp==0.6.0

``````

</details>

![image](https://user-images.githubusercontent.com/193223/66154270-aa91d680-e64f-11e9-88e3-a6bf633567a7.png)

## Issue description

cannot open tensorboard 

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 3174, in wrapper
    return method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post
    .new_instance(data["logdir"], reload_interval=reload_interval)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 148, in new_instance
    purge_orphaned_data=purge_orphaned_data)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 46, in create_tb_app
    tensorboard.assets_zip_provider)
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/backend/application.py", line 157, in standard_tensorboard_wsgi
    flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 113, in TensorBoardWSGIApp
    path_to_run = application.parse_event_files_spec(logdir)
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/backend/application.py", line 455, in parse_event_files_spec
    for specification in logdir_spec.split(','):
AttributeError: 'Namespace' object has no attribute 'split'
```

https://github.com/tensorflow/tensorboard/commit/2d6964d37148ab694b56c4b75ffbf163d3c42e6a#diff-7d6c99d40aa50952666cee46b76708a8R60

the code expected to get a str, but it got a Namespace (flags)

**Comment by gowthamkpr** [comment]
Can you please take a look at this [issue](https://stackoverflow.com/questions/28422883/attributeerror-namespace-object-has-no-attribute) and let me know if it helps!

**Comment by qrtt1** [comment]
sorry, i think i am report to the wrong repo. 
got the same problem with https://github.com/lspvic/jupyter_tensorboard/issues/55

**Comment by alexandru-dinu** [comment]
Hi there,

I am facing the same problem. Is there an official solution?

**Comment by alexandru-dinu** [comment]
Any updates on this?

**Comment by nfelt** [comment]
This is an issue with jupyter_tensorboard since they monkey-patch our code, which then broke due to recent internal changes we made.  Please comment on https://github.com/lspvic/jupyter_tensorboard/issues/55 if this is an issue for you.

**Comment by alexandru-dinu** [comment]
Will do. Thank you!

**Comment by qrtt1** [comment]
I have sent a PR https://github.com/lspvic/jupyter_tensorboard/pull/56
