### ISSUE TITLE
There is no ignore outlier options in my tensorboard

### ISSUE THREAD

**Issue by zhanghaoyue** [tensorflow/tensorboard#2790]
Hello I am new to tensorboard and I mainly use pytorch. My specs:
pytorch 1.2
tensorboard 2.0
tensorboard X 1.9

My tensorboard works well, except that in EVENTS panel, there's no ignore outlier options.
There are only two clickable options: Split on underscores and Data download links

![image](https://user-images.githubusercontent.com/11541770/67035389-6af6d000-f0ce-11e9-869e-1e8eba29699f.png)

Is there a config file to turn this on and off? I couldn't find any solution anywhere else..

**Comment by stephanwlee** [comment]
This does not look like a proper TensorBoard. For instance, TensorBoard does not have "Split on underscores" and what not. Can you please run the diagnose_tensorboard.py and report back? (https://github.com/tensorflow/tensorboard/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by zhanghaoyue** [comment]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 4725c70c7ed724e2d1b9ba5618d7c30b957ee8a4

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='xxx', release='4.4.0-150-generic', version='#176-Ubuntu SMP Wed May 29 18:56:26 UTC 2019', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.0.0
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.0.0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "/home/haoyuezhang/stroke_CNN_models/diagnose_tensorboard.py", line 420, in main
    suggestions.extend(check())
  File "/home/haoyuezhang/stroke_CNN_models/diagnose_tensorboard.py", line 77, in wrapper
    result = fn()
  File "/home/haoyuezhang/stroke_CNN_models/diagnose_tensorboard.py", line 237, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/usr/local/bin/tensorboard\n'

--- check: readable_fqdn
INFO: socket.getfqdn(): 'RAD-MII-DEEPMED-L'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/haoyuezhang/.conda/envs/stroke/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.8.1
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-project==0.8.3
asn1crypto==1.0.1
astroid==2.3.1
astropy==3.2.2
atomicwrites==1.3.0
attrs==19.2.0
Babel==2.7.0
backcall==0.1.0
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.8.1
bitarray==1.0.1
bkcharts==0.2
bleach==3.1.0
bokeh==1.3.4
boto==2.49.0
Bottleneck==1.2.1
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
clyent==1.2.2
colorama==0.4.1
contextlib2==0.6.0
cryptography==2.7
cycler==0.10.0
Cython==0.29.13
cytoolz==0.10.0
dask==2.5.2
decorator==4.4.0
defusedxml==0.6.0
distributed==2.5.1
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
Flask==1.1.1
fsspec==0.5.2
gevent==1.4.0
glob2==0.7
gmpy2==2.0.8
greenlet==0.4.15
grpcio==1.24.1
h5py==2.10.0
HeapDict==1.0.1
html5lib==1.0.1
idna==2.8
imageio==2.5.0
imagesize==1.1.0
importlib-metadata==0.23
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.15.1
jeepney==0.4.1
Jinja2==2.10.3
joblib==0.14.0
json5==0.8.5
jsonschema==3.1.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.0
jupyterlab==1.1.4
jupyterlab-server==1.0.6
keyring==19.2.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.2
libarchive-c==2.8
lief==0.9.0
llvmlite==0.29.0
locket==0.2.0
lxml==4.4.1
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
mock==3.0.5
more-itertools==7.2.0
mpmath==1.1.0
msgpack==0.6.2
multipledispatch==0.6.0
nbconvert==5.6.0
nbformat==4.4.0
networkx==2.3
nibabel==2.5.1
nltk==3.4.5
nose==1.3.7
notebook==6.0.1
numba==0.45.1
numexpr==2.7.0
numpy==1.17.2
numpydoc==0.9.1
olefile==0.46
openpyxl==3.0.0
packaging==19.2
pandas==0.25.1
pandocfilters==1.4.2
parso==0.5.1
partd==1.0.0
path.py==12.0.1
pathlib2==2.3.5
patsy==0.5.1
pep8==1.7.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.0
pip==19.2.3
pkginfo==1.5.0.1
pluggy==0.13.0
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.10.0
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.3
pyflakes==2.1.1
Pygments==2.4.2
pylint==2.4.2
pyodbc==4.0.27
pyOpenSSL==19.0.0
pyparsing==2.4.2
pyrsistent==0.15.4
PySocks==1.7.1
pytest==5.0.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.4.0
pytest-openfiles==0.4.0
pytest-remotedata==0.3.2
python-dateutil==2.8.0
pytz==2019.3
PyWavelets==1.0.3
PyYAML==5.1.2
pyzmq==18.1.0
QtAwesome==0.6.0
qtconsole==4.5.5
QtPy==1.9.0
requests==2.22.0
rope==0.14.0
ruamel-yaml==0.15.46
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
SecretStorage==3.1.1
Send2Trash==1.5.0
setuptools==41.4.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.4
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==1.5.0
SQLAlchemy==1.3.9
statsmodels==0.10.1
sympy==1.4
tables==3.5.2
tblib==1.4.0
tensorboard==2.0.0
tensorboardX==1.9
terminado==0.8.2
testpath==0.4.2
toolz==0.10.0
torch==1.2.0
torchvision==0.4.0
tornado==6.0.3
tqdm==4.36.1
traitlets==4.3.3
unicodecsv==0.14.1
urllib3==1.25.6
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
wheel==0.33.6
widgetsnbextension==3.5.1
wrapt==1.11.2
wurlitzer==1.0.3
xlrd==1.2.0
XlsxWriter==1.2.1
xlwt==1.3.0
zict==1.0.0
zipp==0.6.0

``````

</details>

**Comment by wchargin** [comment]
This is a very, very old version of TensorBoard. The “Events” dashboard
was renamed to “Scalars” in 2016:
<https://github.com/tensorflow/tensorboard/commit/f53c5b12a2f6d3b18ce7ed6e69fe9abd07094466>

Can you try uninstalling and reinstalling all versions of TensorFlow and
TensorBoard on your machine? Updating to any version from the last three
years should do it. :-)

**Comment by zhanghaoyue** [comment]
Is tensorflow necessary for tensorboard? cuz now I am using pytorch to prototype and my tensorboard and tensorboardX are most current in apt

**Comment by wchargin** [comment]
You do not need to have TensorFlow installed to use TensorBoard, no.

Yes, I see from your diagnostics that `tensorboard==2.0.0` is reported
by Pip, but I also see that your `which tensorboard` is actually
`/usr/local/bin/tensorboard`, which suggests that you also have a
different copy of TensorBoard involved (otherwise, `which tensorboard`
should be a file under your Conda environment).

> are most current in apt

We don’t generally recommend installing TensorBoard through `apt`, as we
don’t maintain those packages and can’t attest to their freshness. Can
you run `dpkg -S /usr/local/bin/tensorboard` to see where this binary is
coming from? If it’s coming from a Debian package, you probably want to
just uninstall that entirely. If it’s coming from an old Pip
installation (did you maybe `pip install tensorflow` globally back in
2016 or early 2017?) then you’ll need to use Pip to remove it.

**Comment by wchargin** [comment]
It would also be helpful to run `type -a tensorboard` at your shell to
see if other TensorBoards exist (maybe in your Conda env, if your path
precedence is set up atypically?) and whether invoking those does the
right thing.

**Comment by zhanghaoyue** [comment]
got it, somehow in my virtualenv it is not running the version I installed but instead it is running on another one whoever installed on the server long while ago. Thank you for clarify that!

**Comment by wchargin** [comment]
Excellent; glad to hear it. Thanks for letting us know!
