### ISSUE TITLE
Graphs fail to display in Safari

### ISSUE THREAD

**Issue by RickyLiu0w0** [tensorflow/tensorboard#2880]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 4725c70c7ed724e2d1b9ba5618d7c30b957ee8a4

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Darwin', nodename='username.local', release='18.6.0', version='Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019;  machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.0.1
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.0.1'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "test.py", line 420, in main
    suggestions.extend(check())
  File "test.py", line 77, in wrapper
    result = fn()
  File "test.py", line 237, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/Library/Frameworks/Python.framework/Versions/3.7/bin/tensorboard\n'

--- check: stat_tensorboardinfo
INFO: directory: /var/folders/cv/1hs1s_457bq56njnnscxv2lh0000gp/T/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=4311523889, st_dev=16777220, st_nlink=2, st_uid=502, st_gid=20, st_size=64, st_atime=1572828265, st_mtime=1572830305, st_ctime=1572830305)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.8.1
appnope==0.1.0
attrs==19.1.0
backcall==0.1.0
beautifulsoup4==4.8.0
bleach==3.1.0
bs4==0.0.1
cachetools==3.1.1
certifi==2019.3.9
chardet==3.0.4
cycler==0.10.0
decorator==4.4.0
defusedxml==0.5.0
entrypoints==0.3
future==0.18.2
google-auth==1.6.3
google-auth-oauthlib==0.4.1
grpcio==1.24.3
idna==2.8
ipykernel==5.1.0
ipython==7.4.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.3
jieba==0.39
Jinja2==2.10
joblib==0.14.0
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.0
mistune==0.8.4
nbconvert==5.4.1
nbformat==4.4.0
notebook==5.7.6
numpy==1.16.4
oauthlib==3.1.0
pandocfilters==1.4.2
parso==0.3.4
pexpect==4.6.0
pickleshare==0.7.5
Pillow==6.0.0
pip==18.1
prometheus-client==0.6.0
prompt-toolkit==2.0.9
protobuf==3.10.0
ptyprocess==0.6.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
Pygments==2.3.1
pyparsing==2.4.0
pyrsistent==0.14.11
python-dateutil==2.8.0
pyzmq==18.0.1
qtconsole==4.4.3
requests==2.22.0
requests-oauthlib==1.2.0
rsa==4.0
scikit-learn==0.21.3
scipy==1.3.1
Send2Trash==1.5.0
setuptools==41.6.0
six==1.12.0
sklearn==0.0
soupsieve==1.9.3
tensorboard==2.0.1
terminado==0.8.1
testpath==0.4.2
torch==1.2.0
torchvision==0.4.0
tornado==6.0.2
traitlets==4.3.2
urllib3==1.25.3
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
wheel==0.33.6
widgetsnbextension==3.4.2
wordcloud==1.5.0

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

For browser-related issues, please additionally specify:

  - Safari 12.1.1 

![issue_screenshot](https://user-images.githubusercontent.com/50950678/68097302-4a61af00-fef1-11e9-8ce7-11fe94a89314.png)

## Issue description

I use TensorBoard by pytorch. When I did the third step(**Inspect the model using TensorBoard**) of this web([VISUALIZING MODELS, DATA, AND TRAINING WITH TENSORBOARD](https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html#inspect-the-model-using-tensorboard)), I found my tab `GRAPHS` didn't display the net. Is it the problem of browser?

**Comment by xv1nx** [comment]
there is also a browser-related ticket for firefox: https://github.com/tensorflow/tensorboard/issues/2862
