### ISSUE TITLE
sidebar size problem for log names

### ISSUE THREAD

**Issue by amirhfarzaneh** [tensorflow/tensorboard#2917]
## Environment information
`diagnose_tensorboard.py` output:

```
--- check: autoidentify
INFO: diagnose_tensorboard.py version 4725c70c7ed724e2d1b9ba5618d7c30b957ee8a4

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='rogue-gpu', release='4.15.0-66-generic', version='#75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==1.14.0
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '1.14.0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "test.py", line 420, in main
    suggestions.extend(check())
  File "test.py", line 77, in wrapper
    result = fn()
  File "test.py", line 237, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/sshd/amirhf/miniconda3/envs/pytorch/bin/tensorboard\n'

--- check: readable_fqdn
INFO: socket.getfqdn(): 'rogue-gpu'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=1837054, st_dev=2050, st_nlink=2, st_uid=1001, st_gid=27, st_size=4096, st_atime=1573161598, st_mtime=1573502812, st_ctime=1573502812)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/sshd/amirhf/miniconda3/envs/pytorch/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.8.0
astroid==2.2.5
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
blessings==1.7
certifi==2019.9.11
cffi==1.12.3
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
future==0.17.1
gpustat==1.0.0.dev0
grpcio==1.23.0
imbalanced-learn==0.5.0
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jedi==0.15.1
Jinja2==2.10.1
joblib==0.13.2
jsonschema==3.0.2
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.1
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.14
mkl-random==1.0.2
mkl-service==2.0.2
nbconvert==5.5.0
nbformat==4.4.0
notebook==6.0.0
numpy==1.16.4
nvidia-ml-py3==7.352.0
olefile==0.46
pandas==0.25.1
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
pip==19.2.2
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.9.1
psutil==5.6.3
ptvsd==4.3.2
ptyprocess==0.6.0
pycparser==2.19
Pygments==2.4.2
pylint==2.3.1
pyparsing==2.4.2
pyrsistent==0.14.11
python-dateutil==2.8.0
pytorch-ignite==0.2.1
pytz==2019.2
PyYAML==5.1.2
pyzmq==18.1.0
qtconsole==4.5.4
scikit-learn==0.21.2
scipy==1.3.1
Send2Trash==1.5.0
setuptools==41.0.1
six==1.12.0
tensorboard==1.14.0
terminado==0.8.2
testpath==0.4.2
torch==1.2.0
torchsummary==1.5.1
torchvision==0.4.0a0+6b959ee
tornado==6.0.3
tqdm==4.32.1
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.5
wheel==0.33.4
widgetsnbextension==3.5.1
wrapt==1.11.2
```

  - Browsers: Chrome (Version 78.0.3904.97 (Official Build) (64-bit)) / Firefox (70.0.1 (64-bit))

Screenshot:
![Screenshot from 2019-11-11 13-22-55](https://user-images.githubusercontent.com/9829572/68618925-9c717a00-0487-11ea-8cab-b2a4fee3fb9f.JPG)

## Issue description

As seen in the screenshot above the name of my logs doesn't span to the whole sidebar section and I see a large blank space to the right (red arrows). If the name of my log is long, it will make it hard to compare with other logs especially if I have a lot of logs.

**Comment by psybuzz** [comment]
Thanks for the report.  I'm unable to reproduce this, is the sidebar consistently too narrow, even after refreshing the page?

It also looks like your TensorBoard version is relatively older, could you try with a newer version?
```
pip uninstall tensorboard
pip install tensorboard
```

**Comment by amirhfarzaneh** [comment]
Yeah, so the problem is with the earlier version of tensorboard. updating to 2.0.1 fixed this issue. Thank you
