### ISSUE TITLE
Demos (scalars_demo, etc) do not work with eager TF.

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tensorboard#3058]
#2639  Environment information (required)
``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version d515ab103e2b1cfcea2b096187741a0eeb8822ef

--- check: general
INFO: sys.version_info: sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): ('Darwin', 'bileschi-macbookair2.roam.corp.google.com', '18.7.0', 'Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64', 'x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/Users/bileschi/venv/build-tensorboard'

--- check: installed_packages
INFO: installed: tb-nightly==2.2.0a20191219
INFO: installed: tf-nightly==2.1.0.dev20191219
INFO: installed: tf-estimator-nightly==2.0.0.dev2019121909

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.2.0a20191219'

--- check: tensorflow_python_version
WARNING: Falling back to tensorflow client, its recommended to install the cloud tpu client directly with pip install cloud-tpu-client .
INFO: tensorflow.__version__: '2.1.0-dev20191219'
INFO: tensorflow.__git_version__: 'v1.12.1-20960-g565ad47821'

--- check: tensorboard_binary_path
INFO: which tensorboard: '/Users/bileschi/venv/build-tensorboard/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = 0
socket.SOCK_STREAM = 1
socket.AI_ADDRCONFIG = 1024
socket.AI_PASSIVE = 1
Loopback flags: 1024
Loopback infos: [(30, 1, 6, '', ('::1', 0, 0, 0)), (2, 1, 6, '', ('127.0.0.1', 0))]
Wildcard flags: 1
Wildcard infos: [(30, 1, 6, '', ('::', 0, 0, 0)), (2, 1, 6, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'bileschi-macbookair2.roam.corp.google.com'

--- check: stat_tensorboardinfo
INFO: directory: /var/folders/5y/tz6gptbn6l94tvq_gkzt85z40058dy/T/.tensorboard-info
INFO: os.stat(...): posix.stat_result(st_mode=16895, st_ino=8635065067, st_dev=16777220, st_nlink=2, st_uid=172478, st_gid=5000, st_size=64, st_atime=1576781526, st_mtime=1576784144, st_ctime=1576784144)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (2): ['', '/Users/bileschi/venv/build-tensorboard/lib/python2.7/site-packages']; bad_roots (1): ['']

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.9.0
astor==0.8.1
aws-xray-sdk==0.95
backports.ssl-match-hostname==3.7.0.1
backports.tempfile==1.0
backports.weakref==1.0.post1
boto==2.49.0
boto3==1.9.86
botocore==1.12.253
cachetools==3.1.1
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
configparser==4.0.2
cookies==2.2.1
cryptography==2.8
docker==4.1.0
docutils==0.15.2
ecdsa==0.14.1
entrypoints==0.3
enum34==1.1.6
flake8==3.7.8
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.18.2
futures==3.3.0
gast==0.2.2
google-auth==1.10.0
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
grpc==0.3.post19
grpcio==1.26.0
grpcio-testing==1.24.3
h5py==2.10.0
idna==2.8
ipaddress==1.0.23
Jinja2==2.10.3
jmespath==0.9.4
jsondiff==1.1.1
jsonpickle==1.2
Keras-Preprocessing==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
mccabe==0.6.1
mock==3.0.5
moto==1.3.7
msgpack-python==0.5.6
numpy==1.16.5
oauthlib==3.1.0
opt-einsum==2.3.2
pathspec==0.6.0
pip==19.3.1
protobuf==3.11.1
pyaml==19.12.0
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycodestyle==2.5.0
pycparser==2.19
pycryptodome==3.9.4
pyflakes==2.1.1
python-dateutil==2.8.1
python-jose==2.0.2
pytz==2019.3
PyYAML==5.2
requests==2.22.0
requests-oauthlib==1.3.0
responses==0.10.8
rsa==4.0
s3transfer==0.1.13
setuptools==42.0.2
six==1.13.0
tb-nightly==2.2.0a20191219
termcolor==1.1.0
tf-estimator-nightly==2.0.0.dev2019121909
tf-nightly==2.1.0.dev20191219
typing==3.7.4.1
urllib3==1.25.7
virtualenv==16.7.7
websocket-client==0.56.0
Werkzeug==0.16.0
wheel==0.33.6
wrapt==1.11.2
xmltodict==0.12.0
yamllint==1.17.0

``````

## Issue description

` bazel run //tensorboard/plugins/scalar:scalars_demo` fails with 

```
$ bazel run //tensorboard/plugins/scalar:scalars_demo
INFO: Analyzed target //tensorboard/plugins/scalar:scalars_demo (0 packages loaded, 6 targets configured).
INFO: Found 1 target...
Target //tensorboard/plugins/scalar:scalars_demo up-to-date:
  bazel-bin/tensorboard/plugins/scalar/scalars_demo
INFO: Elapsed time: 3.795s, Critical Path: 0.15s
INFO: 0 processes.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
WARNING:tensorflow:Falling back to tensorflow client, its recommended to install the cloud tpu client directly with pip install cloud-tpu-client .
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
Saving output to /tmp/scalars_demo.
--- Running: temperature:t0=270,tA=270,kH=0.001
2019-12-19 14:38:44.006797: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-19 14:38:44.124431: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8172df28e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-12-19 14:38:44.124467: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
W1219 14:38:44.154403 4518094272 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1219 14:38:44.213824 4518094272 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1219 14:38:44.258884 4518094272 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1219 14:38:44.274101 4518094272 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_bileschi/008ae9c3ce5002f6e5f3978c4a072bab/execroot/org_tensorflow_tensorboard/bazel-out/darwin-fastbuild/bin/tensorboard/plugins/scalar/scalars_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/scalar/scalars_demo.py", line 163, in <module>
    app.run(main)
  File "/Users/bileschi/venv/build-tensorboard/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/bileschi/venv/build-tensorboard/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/private/var/tmp/_bazel_bileschi/008ae9c3ce5002f6e5f3978c4a072bab/execroot/org_tensorflow_tensorboard/bazel-out/darwin-fastbuild/bin/tensorboard/plugins/scalar/scalars_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/scalar/scalars_demo.py", line 158, in main
    run_all(LOGDIR, verbose=True)
  File "/private/var/tmp/_bazel_bileschi/008ae9c3ce5002f6e5f3978c4a072bab/execroot/org_tensorflow_tensorboard/bazel-out/darwin-fastbuild/bin/tensorboard/plugins/scalar/scalars_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/scalar/scalars_demo.py", line 152, in run_all
    heat_coefficient,
  File "/private/var/tmp/_bazel_bileschi/008ae9c3ce5002f6e5f3978c4a072bab/execroot/org_tensorflow_tensorboard/bazel-out/darwin-fastbuild/bin/tensorboard/plugins/scalar/scalars_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/scalar/scalars_demo.py", line 108, in run
    summ = tf.compat.v1.summary.merge_all()
  File "/Users/bileschi/venv/build-tensorboard/lib/python2.7/site-packages/tensorflow_core/python/summary/summary.py", line 400, in merge_all
    'Merging tf.summary.* ops is not compatible with eager execution. '
RuntimeError: Merging tf.summary.* ops is not compatible with eager execution. Use tf.contrib.summary instead.
```

**Comment by wchargin** [comment]
Yep, thanks; this is known. Most of the demos were written for TF v1.
Some have v2 equivalents or alternatives.

I suspect that wrapping this in `with tf.compat.v1.Graph().as_default()`
or similar should fix it.

**Comment by AmanPatel599** [comment]
@wchargin i would love to work on this!!
can you guide me a little bit??

**Comment by wchargin** [comment]
We don’t really have bandwidth to provide in-depth guidance on issues
like this, and it looks like there’s already a fix attempt out (#3238).

**Comment by psybuzz** [comment]
Updating this to become an umbrella bug about updating all our demos to TF2's eager style.

Custom Scalars' demo is outdated, but should be rewritten in eager style.  Possibly something like this:
https://gist.github.com/psybuzz/025ac2c1c55947dba1938cd9d5b520f9
using
-  from tensorboard.summary import v1 as summary_lib
-  tf.summary.experimental.write_raw_pb(layout_summary.SerializeToString(), step=0)

**Comment by zeph1yr** [comment]
As @wchargin mentioned, most of the demos were written for TF v1 and a similar fix I use is,
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

**Comment by nfelt** [comment]
I think this has generally been done, earlier this year, when we updated many of the demos to be TF2-compatible. E.g. the custom scalars demo was updated in https://github.com/tensorflow/tensorboard/pull/5011.
