### ISSUE TITLE
Error when running tensorboard with jupyter

### ISSUE THREAD

**Issue by DevDoldol** [tensorflow/tensorboard#3145]
There is an error when running tensorboard. This is a similar error to issue https://github.com/lspvic/jupyter_tensorboard/pull/56, so I tried modifying the file but got the same error. Please help.

**version info** 

jupyter                  1.0.0
jupyter-client           5.3.4
jupyter-console          6.0.0
jupyter-core             4.6.1
jupyter-nbextensions-git 1.0
jupyter-tensorboard      0.1.9
nbconvert                5.6.1
tensorboard              2.0.2
tensorflow               2.0.0
tensorflow-estimator     2.0.1
python 3.6.9

```
test> Executing the command: jupyter notebook
[I 20:52:52.664 NotebookApp] [jupyter_nbextensions_git] enabled 1.0
[I 20:52:54.661 NotebookApp] jupyter_tensorboard extension loaded.
[I 20:52:54.661 NotebookApp] Serving notebooks from local directory: /home/test
[I 20:52:54.661 NotebookApp] The Jupyter Notebook is running at:
[I 20:52:54.661 NotebookApp] http://jupyter-tesseract-1-3-6-4-55c4f95749-j7fkh:8888/jupyter/4/test/
[I 20:52:54.661 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 20:53:20.319 NotebookApp] 302 POST /jupyter/4/test/login?next=%2Fjupyter%2F4%2Ftest%2Ftree%3F (6.2.0.1) 1.48ms
[E 20:53:24.439 NotebookApp] Uncaught exception POST /jupyter/4/test/api/tensorboard (6.2.0.48)
    HTTPServerRequest(protocol='http', host='192.168.100.5', method='POST', uri='/jupyter/4/test/api/tensorboard', version='HTTP/1.1', remote_ip='6.2.0.48')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_tensorboard/api_handlers.py", line 36, in post
        .new_instance(data["logdir"], reload_interval=reload_interval)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_tensorboard/tensorboard_manager.py", line 148, in new_instance
        purge_orphaned_data=purge_orphaned_data)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_tensorboard/tensorboard_manager.py", line 46, in create_tb_app
        tensorboard.assets_zip_provider)
      File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 157, in standard_tensorboard_wsgi
        flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_tensorboard/tensorboard_manager.py", line 113, in TensorBoardWSGIApp
        path_to_run = application.parse_event_files_spec(logdir)
      File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 455, in parse_event_files_spec
        for specification in logdir_spec.split(','):
    AttributeError: 'Namespace' object has no attribute 'split'
[W 20:53:24.440 NotebookApp] Unhandled error
[E 20:53:24.440 NotebookApp] {
      "Host": "192.168.100.5",
      "Connection": "close",
      "X-Request-Id": "5088ff2858b9b3ecd1b8bac2dac5a70b",
      "X-Real-Ip": "6.2.0.1",
      "X-Forwarded-For": "6.2.0.1",
      "X-Forwarded-Host": "192.168.100.5",
      "X-Forwarded-Port": "80",
      "X-Forwarded-Proto": "http",
      "X-Original-Uri": "/jupyter/4/test/api/tensorboard",
      "X-Scheme": "http",
      "Proxy-Body-Size": "0",
      "Content-Length": "13",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://192.168.100.5",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|80cd1342|235ffaee485aa9289620f6ce326d2348|1578483859",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://192.168.100.5/jupyter/4/test/tree?",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
      "Cookie": "project-4-test=\"2|1:0|10:1578570800|14:project-4-test|44:ZmJlYmRlMDBhZTNkNDQ4MmIzZTU4MWIwNDgwOGUxMDU=|b265508c8eef2d06a62c2dcc69e0c9c5d56486920b164273f2a87f940e9989dc\"; sidebar_collapsed=false; vertx-web.session=fef5046900f7d540057d0b16a6d8858d; _xsrf=2|80cd1342|235ffaee485aa9289620f6ce326d2348|1578483859; event_filter=all; globalVal={%22currentProject%22:4%2C%22projectId%22:4}"
    }
[E 20:53:24.440 NotebookApp] 500 POST /jupyter/4/test/api/tensorboard (6.2.0.48) 18.21ms referer=http://192.168.100.5/jupyter/4/test/tree?
```

**Comment by rmothukuru** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by DevDoldol** [comment]
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!


This occurred when TensorBoard was executed from Jupiter Notebook screen after installing Python 3.6, TensorFlow 2.0, and Jupiter in anaconda environment.

**Comment by zeph1yr** [comment]
Are you running Tensorboard on Jupyter notebook with TensorBoard notebook extension? If not here's the guide https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks

**Comment by nfelt** [comment]
This is an issue with jupyter_tensorboard since they monkey-patch our code, which then broke due to internal changes we made in TensorBoard 2.0.  I believe the open issue on their end is https://github.com/lspvic/jupyter_tensorboard/issues/55, but there's nothing to fix on our end.
