### ISSUE TITLE
Error migrating old summary format

### ISSUE THREAD

**Issue by JGSweets** [tensorflow/tensorboard#350]
When starting tensorboard, I get the traceback:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/cve685/Documents/Projects/tensorboard/venv/lib/python2.7/site-packages/tensorboard/backend/application.py", line 325, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/Users/cve685/Documents/Projects/tensorboard/venv/lib/python2.7/site-packages/tensorboard/backend/application.py", line 299, in reload_multiplexer
    multiplexer.Reload()
  File "/Users/cve685/Documents/Projects/tensorboard/venv/lib/python2.7/site-packages/tensorboard/backend/event_processing/event_multiplexer.py", line 196, in Reload
    accumulator.Reload()
  File "/Users/cve685/Documents/Projects/tensorboard/venv/lib/python2.7/site-packages/tensorboard/backend/event_processing/event_accumulator.py", line 209, in Reload
    self._ProcessEvent(event)
  File "/Users/cve685/Documents/Projects/tensorboard/venv/lib/python2.7/site-packages/tensorboard/backend/event_processing/event_accumulator.py", line 355, in _ProcessEvent
    value = data_compat.migrate_value(value)
  File "/Users/cve685/Documents/Projects/tensorboard/venv/lib/python2.7/site-packages/tensorboard/data_compat.py", line 53, in migrate_value
    return handler(value) if handler else value
  File "/Users/cve685/Documents/Projects/tensorboard/venv/lib/python2.7/site-packages/tensorboard/data_compat.py", line 80, in _migrate_image_value
    display_name=value.metadata.display_name or value.tag,
AttributeError: 'Value' object has no attribute 'metadata'
```

As mentioned above, value doesn't have the attribute metadata, however value.tag does exist. The following line will also cause an error:
```
value.metadata.summary_description
```

I also imagine the function _migrate_histogram_value will also have the same issue.

I assume this is because TF used to create the data is 1.2 rather than 1.3

Mentioning if bwards compat is desired for old event files.

**Comment by JGSweets** [comment]
Or rather due to TF 1.2 installed instead of 1.3.
