### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by sabarishkumaran** [tensorflow/tensorboard#3583]
## Environment information (required)
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32

Windows 10 home[64 bit]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version d515ab103e2b1cfcea2b096187741a0eeb8822ef

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
INFO: os.name: nt
INFO: os.uname(): N/A
INFO: sys.getwindowsversion(): sys.getwindowsversion(major=10, minor=0, build=18363, platform=2, service_pack='')

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
WARNING: Could not generate requirement for distribution -pencv-python 3.4.8.29 (c:\users\sabarish kumaran ks\anaconda3\lib\site-packages): Parse error at "'-pencv-p'": Expected W:(abcd...)
INFO: installed: tensorboard==2.1.1
INFO: installed: tensorflow==2.1.0
INFO: installed: tensorflow-estimator==2.1.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.1.1'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "diagnose_tensorboard.py", line 470, in main
    suggestions.extend(check())
  File "diagnose_tensorboard.py", line 78, in wrapper
    result = fn()
  File "diagnose_tensorboard.py", line 253, in tensorflow_python_version
    import tensorflow as tf
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Sabarish Kumaran KS\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

--- check: tensorboard_binary_path
INFO: which tensorboard: b'C:\\Users\\Sabarish Kumaran KS\\Anaconda3\\Scripts\\tensorboard.exe\r\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = 1024
socket.AI_PASSIVE = 1
Loopback flags: 1024
Loopback infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('127.0.0.1', 0))]
Wildcard flags: 1
Wildcard infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'Sabarish'

--- check: stat_tensorboardinfo
INFO: directory: C:\Users\SABARI~1\AppData\Local\Temp\.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['C:\\Users\\Sabarish Kumaran KS\\Anaconda3\\lib\\site-packages']; bad_roots (0): []

--- check: full_pip_freeze
WARNING: Could not generate requirement for distribution -pencv-python 3.4.8.29 (c:\users\sabarish kumaran ks\anaconda3\lib\site-packages): Parse error at "'-pencv-p'": Expected W:(abcd...)
INFO: pip freeze --all:
absl-py==0.9.0
alabaster==0.7.9
anaconda-clean==1.0
anaconda-client==1.5.1
anaconda-navigator==1.8.4
anaconda-project==0.8.3
argcomplete==1.0.0
argh==0.26.2
astor==0.8.1
astroid==1.4.7
astropy==1.2.1
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.1
bitarray==0.8.1
blaze==0.10.1
bleach==1.5.0
bokeh==0.12.2
boto==2.42.0
Bottleneck==1.1.0
bs4==0.0.1
cachetools==4.1.0
certifi==2020.4.5.1
cffi==1.7.0
chardet==3.0.4
chest==0.2.3
click==6.6
cloudpickle==0.2.1
clyent==1.2.2
cmake==3.11.0
colorama==0.3.7
comtypes==1.1.2
conda==4.5.11
conda-build==2.0.2
configobj==5.0.6
constants==0.6.0
contextlib2==0.5.3
cryptography==1.7.1
curses==2.2.1+utf8
cycler==0.10.0
Cython==0.24.1
cytoolz==0.9.0.1
dask==0.11.0
datashape==0.5.2
decorator==4.0.10
deepgaze==0.1
dill==0.2.5
dlib==18.17.100
docutils==0.12
dynd===c328ab7
emot==2.1
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.6
Flask==0.11.1
Flask-Cors==2.1.2
fpdf==1.7.2
gast==0.2.2
gevent==1.1.2
google-auth==1.14.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
greenlet==0.4.10
grpcio==1.28.1
gTTS==2.0.3
gTTS-token==1.1.3
h5py==2.10.0
HeapDict==1.0.0
html5lib==0.9999999
idna==2.9
imagesize==0.7.1
imutils==0.4.6
ipykernel==4.5.0
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
jdcal==1.2
jedi==0.9.0
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
lazy-object-proxy==1.2.1
llvmlite==0.13.0
locket==0.2.0
lxml==3.6.4
mahotas==1.4.9
Markdown==3.2.1
MarkupSafe==0.23
matplotlib==1.5.0
menuinst==1.4.1
mistune==0.7.3
mpmath==0.19
multipledispatch==0.4.8
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.1.0
nbpresent==3.0.2
networkx==1.11
nltk==3.2.1
nose==1.3.7
notebook==4.2.3
numba==0.28.1
numexpr==2.6.5
numpy==1.18.4
oauthlib==3.1.0
odo==0.5.0
opencv-contrib-python==3.4.8.29
opencv-python==3.4.8.29
openpyxl==2.3.2
opt-einsum==3.2.1
pandas==0.18.1
partd==0.3.6
path.py==0.0.0
pathlib2==2.1.0
patsy==0.4.1
pep8==1.7.0
pickleshare==0.7.4
Pillow==3.3.1
pip==20.1
pkginfo==1.3.2
playsound==1.2.2
ply==3.9
prompt-toolkit==1.0.3
protobuf==3.11.3
psutil==4.3.1
py==1.4.31
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAutoGUI==0.9.41
pycosat==0.6.3
pycparser==2.14
pycrypto==2.6.1
pycurl==7.43.0
PyDispatcher==2.0.5
pyflakes==1.3.0
PyGetWindow==0.0.4
Pygments==2.1.3
pylint==1.5.4
PyMsgBox==1.0.6
pyOpenSSL==16.2.0
pyparsing==2.1.4
PyQRCode==1.2.1
PyRect==0.1.4
PyScreeze==0.1.19
pytesseract==0.2.6
pytest==2.9.2
python-dateutil==2.5.3
pytils==0.3
pyttsx==1.1
pyttsx3==2.7
PyTweening==1.0.3
pytz==2016.6.1
pywin32==220
PyYAML==3.12
pyzbar==0.1.7
pyzmq==15.4.0
QtAwesome==0.3.3
qtconsole==4.6.0
QtPy==1.1.2
requests==2.23.0
requests-oauthlib==1.3.0
rope-py3k==0.9.4.post1
rsa==4.0
ruamel-yaml===-VERSION
scikit-image==0.12.3
scikit-learn==0.19.0
scipy==1.4.1
seaborn==0.9.0
selectors==0.0.14
setuptools==46.1.3
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.14.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
sphinx==1.4.6
spyder==2.3.9
SQLAlchemy==1.0.13
statsmodels==0.6.1
sympy==1.0
tables==3.2.2
tensorboard==2.1.1
tensorflow==2.1.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
tesseract==0.1.3
tf-utils==1.0.4
tflearn==0.3.2
tool==0.8.0
toolz==0.8.0
tornado==4.4.1
tqdm==4.40.2
traitlets==4.3.0
unicodecsv==0.14.1
urllib3==1.25.9
user-agent==0.1.9
utils==0.9.0
wcwidth==0.1.7
weblib==0.1.30
Werkzeug==1.0.1
wheel==0.34.2
widgetsnbextension==1.2.6
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.12.1
xlrd==1.0.0
XlsxWriter==0.9.3
xlwings==0.10.0
xlwt==1.1.2

``````

</details>

**Comment by gowthamkpr** [comment]
@sabarishkumaran This issue is not related to tensorboard. This is related to tensorflow itself. Please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/35749#issuecomment-573313402) and let me know if it helps. Thanks!

**Comment by sabarishkumaran** [comment]
@gowthamkpr ya thanks!
