### ISSUE TITLE
could not build from source : build aborted: no such package '@org_mozilla_bleach//'

### ISSUE THREAD

**Issue by ClementRolinat** [tensorflow/tensorboard#3820]
Hello, I am trying to use tensorflow 2.2 with python 2.7, so I tried to build it from source, as tensorflow 2.2 is not available for python 2.7 with pip.

I successfully built tensorflow itself. But when installing the created .whl file with pip, it wants tensorboard 2.2, which is not available with pip for python 2.7 either.

So, I tried to build tensorboard from the git branch 2.2, but the process abort. 

## Environment information (required)
here the result of running diagnose_tensorboard.py, as you can see I have nothing related to tensorflow installed yet.

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version d093788c7c09802e4d35fb50fa3b86cdf5759772

--- check: general
INFO: sys.version_info: sys.version_info(major=2, minor=7, micro=17, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): ('Linux', 'clement-HP-Z800-Workstation', '4.15.0-109-generic', '#110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020', 'x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
WARNING: no installation among: [u'tb-nightly', u'tensorboard', u'tensorflow-tensorboard']
WARNING: no installation among: [u'tensorflow', u'tensorflow-gpu', u'tf-nightly', u'tf-nightly-2.0-preview', u'tf-nightly-gpu', u'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: [u'tensorflow-estimator', u'tensorflow-estimator-2.0-preview', u'tf-estimator-nightly']

--- check: tensorboard_python_version
Traceback (most recent call last):
  File "/home/clement/diagnose_tensorboard.py", line 487, in main
    suggestions.extend(check())
  File "/home/clement/diagnose_tensorboard.py", line 78, in wrapper
    result = fn()
  File "/home/clement/diagnose_tensorboard.py", line 263, in tensorboard_python_version
    from tensorboard import version
ImportError: No module named tensorboard

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "/home/clement/diagnose_tensorboard.py", line 487, in main
    suggestions.extend(check())
  File "/home/clement/diagnose_tensorboard.py", line 78, in wrapper
    result = fn()
  File "/home/clement/diagnose_tensorboard.py", line 270, in tensorflow_python_version
    import tensorflow as tf
ImportError: No module named tensorflow

--- check: tensorboard_binary_path
INFO: which tensorboard: None

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = 0
socket.SOCK_STREAM = 1
socket.AI_ADDRCONFIG = 32
socket.AI_PASSIVE = 1
Loopback flags: 32
Loopback infos: [(10, 1, 6, '', ('::1', 0, 0, 0)), (2, 1, 6, '', ('127.0.0.1', 0))]
Wildcard flags: 1
Wildcard infos: [(2, 1, 6, '', ('0.0.0.0', 0)), (10, 1, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'clement-HP-Z800-Workstation'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['']; bad_roots (1): ['']

--- check: full_pip_freeze
INFO: pip freeze --all:
3to2==1.1.1
absl-py==0.7.0
actionlib==1.12.0
angles==1.9.12
asn1crypto==0.24.0
astor==0.7.1
atari-py==0.1.7
atomicwrites==1.3.0
attrs==18.2.0
autobahn==17.10.1
Automat==0.6.0
backports.functools-lru-cache==1.5
backports.weakref==1.0.post1
beautifulsoup4==4.6.0
bleach==1.5.0
bondpy==1.8.5
bzr==2.8.0.dev1
camera-calibration-parsers==1.11.13
catkin==0.7.26
catkin-pkg==0.4.22
catkin-pkg-modules==0.4.22
catkin-tools==0.6.1
cbor==1.0.0
cea-plugins==0.3.10
certifi==2018.11.29
chardet==3.0.4
Click==7.0
cloudpickle==0.8.0
colorama==0.3.7
configobj==5.0.6
constantly==15.1.0
controller-manager==0.15.1
controller-manager-msgs==0.15.1
controller-manager-tests==0.15.1
coverage==4.5.2
create-driver==2.3.1
create-node==2.3.1
cryptography==2.1.4
cv-bridge==1.13.0
cvxopt==1.2.3
cycler==0.10.0
Cython==0.26.1
defusedxml==0.5.0
diagnostic-analysis==1.9.3
diagnostic-common-diagnostics==1.9.3
diagnostic-updater==1.9.3
dill==0.2.9
docutils==0.14
dynamic-reconfigure==1.6.3
empy==3.3.2
enum34==1.1.6
funcsigs==1.0.2
future==0.18.2
futures==3.2.0
gast==0.2.2
gazebo-plugins==2.8.5
gazebo-ros==2.8.5
gencpp==0.6.5
geneus==2.2.6
genlisp==0.4.16
genmsg==0.5.16
gennodejs==2.0.1
genpy==0.6.12
glob2==0.6
google-pasta==0.1.1
grpcio==1.19.0
-e git+https://github.com/openai/gym.git@17abad35ae82cf01ff4dc962ffd63e3d849d3903#egg=gym
gyp==0.1
h5py==2.9.0
html5lib==0.9999999
httplib2==0.9.2
hyperlink==17.3.1
idna==2.8
incremental==16.10.1
interactive-markers==1.11.5
ipaddress==1.0.17
joblib==0.13.2
joint-state-publisher==1.12.15
joint-state-publisher-gui==1.12.15
kdl-parser-py==1.13.1
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.0.1
kobuki-testsuite==0.7.6
laser-geometry==1.6.5
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
lxml==4.2.1
lz4==0.10.1
Markdown==3.0.1
matplotlib==2.2.3
mercurial==4.5.3
message-filters==1.14.6
mock==3.0.5
more-itertools==5.0.0
moveit-ros-planning-interface==1.0.4
moveit-ros-visualization==1.0.4
mpi4py==3.0.1
msgpack-python==0.5.6
msgpack-rpc-python==0.4
netifaces==0.10.4
nose==1.3.7
numpy==1.16.6
oauth==1.0.1
olefile==0.45.1
openai-ros==1.0.0
opencv-python==4.0.0.21
osrf-pycommon==0.1.9
PAM==0.4.2
pandas==0.24.1
paramiko==2.0.0
pathlib2==2.3.3
pbr==5.1.2
Pillow==5.4.1
pip==20.1.1
Pivy==0.5.0
pluggy==0.8.1
ply==3.11
progressbar2==3.39.2
protobuf==3.7.0
psutil==5.4.2
py==1.7.0
py-ubjson==0.8.5
pyasn1==0.4.2
pyasn1-modules==0.2.1
pyassimp==3.3
pycairo==1.16.2
pycollada==0.4
pycrypto==2.6.1
pycryptodomex==3.4.7
pydot==1.2.3
pyflakes==1.6.0
pyglet==1.3.2
Pygments==2.2.0
pygobject==3.26.1
pygraphviz==1.4rc1
PyNaCl==1.1.2
PyOpenGL==3.1.0
pyOpenSSL==17.5.0
pyparsing==2.3.1
pyserial==3.4
PySide==1.2.2
pytest==4.2.1
pytest-cov==2.6.1
python-dateutil==2.8.0
python-gnupg==0.4.1
python-qt-binding==0.4.3
python-snappy==0.5
python-utils==2.3.0
PyTrie==0.2
pytz==2018.9
pyxdg==0.25
PyYAML==3.13
pyzmq==18.0.0
qrcode==5.3
qt-dotgraph==0.4.1
qt-gui==0.4.1
qt-gui-cpp==0.4.1
qt-gui-py-common==0.4.1
requests==2.21.0
resource-retriever==1.12.6
roman==2.0.0
ros-pytest==0.1.2
ros-vec-env==0.0.0
rosbag==1.14.6
rosboost-cfg==1.14.9
rosclean==1.14.9
roscreate==1.14.9
rosdep-modules==0.19.0
rosdistro==0.8.2
rosdistro-modules==0.8.2
rosgraph==1.14.6
roslaunch==1.14.6
roslib==1.14.9
roslint==0.11.2
roslz4==1.14.6
rosmake==1.14.9
rosmaster==1.14.6
rosmsg==1.14.6
rosnode==1.14.6
rosparam==1.14.6
rospkg==1.2.8
rospkg-modules==1.2.8
rospy==1.14.6
rosservice==1.14.6
rostest==1.14.6
rostopic==1.14.6
rosunit==1.14.9
roswtf==1.14.6
rqt-action==0.4.9
rqt-bag==0.4.12
rqt-bag-plugins==0.4.12
rqt-console==0.4.9
rqt-controller-manager==0.15.1
rqt-dep==0.4.9
rqt-graph==0.4.11
rqt-gui==0.5.2
rqt-gui-py==0.5.2
rqt-image-view==0.4.14
rqt-joint-trajectory-controller==0.15.0
rqt-launch==0.4.8
rqt-logger-level==0.4.8
rqt-moveit==0.5.7
rqt-msg==0.4.8
rqt-nav-view==0.5.7
rqt-plot==0.4.9
rqt-pose-view==0.5.8
rqt-publisher==0.4.8
rqt-py-common==0.5.2
rqt-py-console==0.4.8
rqt-reconfigure==0.5.3
rqt-robot-dashboard==0.5.7
rqt-robot-monitor==0.5.9
rqt-robot-steering==0.5.10
rqt-runtime-monitor==0.5.7
rqt-rviz==0.6.0
rqt-service-caller==0.4.8
rqt-shell==0.4.9
rqt-srv==0.4.8
rqt-tf-tree==0.6.0
rqt-top==0.4.8
rqt-topic==0.4.11
rqt-web==0.4.8
rviz==1.13.13
scandir==1.9.0
scipy==1.2.1
seaborn==0.9.0
SecretStorage==2.3.1
sensor-msgs==1.12.7
service-identity==16.0.0
setuptools==44.1.1
simplejson==3.13.2
six==1.15.0
smach==2.0.1
smach-ros==2.0.1
smclib==1.8.5
srdfdom==0.5.2
-e git+https://github.com/ClementRolinat/stable-baselines.git@1b91ab644cde9d428db727214a951be00ab04f19#egg=stable_baselines
subprocess32==3.5.3
termcolor==1.1.0
tf==1.12.1
tf-conversions==1.12.1
tf2-geometry-msgs==0.6.5
tf2-kdl==0.6.5
tf2-py==0.6.5
tf2-ros==0.6.5
topic-tools==1.14.6
tornado==6.0.2
tqdm==4.31.1
trollius==2.0.1
Twisted==17.9.0
txaio==2.8.1
u-msgpack-python==2.1
urdfdom-py==0.4.3
urllib3==1.24.1
vcstools==0.1.42
virtualenv==15.1.0
wadllib==1.3.2
webencodings==0.5
Werkzeug==0.14.1
wheel==0.34.2
wsaccel==0.6.2
wstool==0.1.17
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xacro==1.13.5
zmq==0.0.0
zope.interface==4.3.2

``````

</details>

## Steps to reproduce (required)

1 - clone the tensorboard repo
2 - go to 2.2 branch
3 - run `bazel build //tensorboard`

the complete error is:

```
INFO: Call stack for the definition of repository 'org_mozilla_bleach' which is a http_archive (rule definition at /home/clement/.cache/bazel/_bazel_clement/ec8b1f6f565a483d6c46d7ceeaec08a8/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/clement/tensorboard/third_party/python.bzl:58:5
 - /home/clement/tensorboard/third_party/python.bzl:58:5
 - /home/clement/tensorboard/third_party/workspace.bzl:33:3
 - /home/clement/tensorboard/WORKSPACE:114:1
ERROR: An error occurred during the fetch of repository 'org_mozilla_bleach':
   java.io.IOException: thread interrupted
INFO: Call stack for the definition of repository 'com_google_javascript_closure_compiler_externs' which is a filegroup_external (rule definition at /home/clement/.cache/bazel/_bazel_clement/ec8b1f6f565a483d6c46d7ceeaec08a8/external/io_bazel_rules_closure/closure/filegroup_external.bzl:186:22):
 - /home/clement/tensorboard/third_party/js.bzl:143:5
 - /home/clement/tensorboard/third_party/js.bzl:143:5
 - /home/clement/tensorboard/third_party/workspace.bzl:35:3
 - /home/clement/tensorboard/WORKSPACE:114:1
ERROR: /home/clement/tensorboard/tensorboard/plugins/text/BUILD:13:1: //tensorboard/plugins/text:text_plugin depends on @org_mozilla_bleach//:org_mozilla_bleach in repository @org_mozilla_bleach which failed to fetch. no such package '@org_mozilla_bleach//': java.io.IOException: thread interrupted
ERROR: Analysis of target '//tensorboard:tensorboard' failed; build aborted: no such package '@org_mozilla_bleach//': java.io.IOException: thread interrupted
INFO: Elapsed time: 20.391s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

Am I doing something wrong ?

**Comment by ericdnielsen** [comment]
TB 2.1.0 was the last version to support Python 2.  You can review the release notes:
https://github.com/tensorflow/tensorboard/blob/master/RELEASE.md

**Comment by ClementRolinat** [comment]
ok, thanks, I will use tf & TB 2.1 instead.

**Comment by rmothukuru** [comment]
@ClementRolinat,
Can you please confirm if we can close this issue as it is resolved. Thanks!

**Comment by ClementRolinat** [comment]
for my use case it is fixed as I won't have to build tensorboard anymore, but the building error related to `no such package '@org_mozilla_bleach//'` is not. But I may have done something wrong to have this error. If no one can reproduce, I guess this issue can be closed.

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved.
