### ISSUE TITLE
Allow async flush in EventFileWriter creation

### ISSUE THREAD

**Issue by cryptopic** [tensorflow/tensorboard#4036]
## Issue

In TensorBoard logging, by default flush is done asynchronously 
https://github.com/tensorflow/tensorboard/blob/67f8ab9c1583a9a14e6c52b2b30fb62234c4afe0/tensorboard/summary/writer/event_file_writer.py#L160-L162

which is nice not only because of perf win, but also people can rely on that any TensorBoard failure will never fail training jobs.

But there's one synchronous flush called from EventFileWriter creation:

https://github.com/tensorflow/tensorboard/blob/67f8ab9c1583a9a14e6c52b2b30fb62234c4afe0/tensorboard/summary/writer/event_file_writer.py#L101

which will be called from [SummaryWriter](https://github.com/pytorch/pytorch/blob/a1a6e1bc9103bf0af7a87bbb2854a3130e38bb03/torch/utils/tensorboard/writer.py#L154
) creation as well. 

This has caused a SEV for us recently, when a filesystem failure caused a lot of training workflows to fail, even when some workflow only created SummaryWriter without explicitly logging anything. People are surprised to find out that:
- Logging code can throw unhandled error
- There're IO in python class initialization

## Question
- What's the motivation to have this explicit flush call, instead of relying on existing implicit flushing?
- What's the risk of bypassing this call (maybe via a flag), I'm not sure how the data (writer creation timestamp) is used in frontend and how bad it is if it's missing

------

Another related problem is, we have many clients that'll create SummaryWriter with same logdir multiple times (e.g. in every logging call or in every trainer), and with this flush callsite, we'll end up creating a lot of empty files even when nothing is eventually logged, which can [slow down data loading](https://github.com/tensorflow/tensorboard/issues/4023). So if this timestamp data turns out to be not essential, then we have big incentive to bypass it completely.

Many thanks!

**Comment by wchargin** [comment]
Hi @cryptopic! Thanks for the report. For clarity, I should note that
the `event_file_writer.py` code that you’re referring to is only used
for the non-TensorFlow writer contributed by @lanpa and @orionr and co.
Some comments inline:

> People are surprised to find out that:
> 
> * Logging code can throw unhandled error
> * There're IO in python class initialization

IMHO it seems somewhat to perform I/O in the initializer of a summary
writer. Creating a `SummaryWriter` is analogous to calling Python’s
`open` builtin, which does throw if the file can’t be opened. Or, for an
example with a class initializer specifically:

```
>>> import tempfile
>>> type(tempfile.TemporaryDirectory)
<class 'type'>
>>> tempfile.TemporaryDirectory(dir="/enoent")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/tempfile.py", line 929, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/usr/lib/python3.7/tempfile.py", line 505, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/enoent/tmpya31842c'
```

Semantically, it seems to me that writing summaries is an important part
of the training process, and if your model were to be silently training
for hours or days but not actually writing any metrics, you might be
pretty dismayed when you found out. So it seems reasonable to me to ask
that code that actually doesn’t care about initialization failures
enclose the constructor call in a `try`-statement to handle the error.
Does this sound reasonable?

For what it’s worth, the fact that this fails when given a directory
that isn’t writable is consistent with the TensorFlow summary writer in
both TF 1.x and TF 2.x. It’s nice to keep that consistency, and I don’t
recall an analogous issue in the TF API causing problems for our users.

> What's the risk of bypassing this call (maybe via a flag), I'm not
> sure how the data (writer creation timestamp) is used in frontend and
> how bad it is if it's missing

I imagine that any flag/behavior change here would keep the `add_event`
and only bypass the `flush`, right? so if data is successfully written
later, the file version and timestamp would be available then. In the
case where the file version is not written but no other data is written,
either, nothing bad should happen (if it does, we should fix that).

> we have many clients that'll create SummaryWriter with same logdir
> multiple times (e.g. in every logging call or in every trainer), and
> with this flush callsite, we'll end up creating a lot of empty files
> even when nothing is eventually logged

Agreed that this isn’t ideal. The TF 1.x writer used to be smart about
this, though the TF 2.x writer also eagerly writes the file version. I’d
be happy to accept a patch that deferred this flush, as long as the
writer still properly fails when the directory isn’t writable.

cc @nfelt re: writer API design

**Comment by cryptopic** [comment]
@wchargin: Thank you for your detailed explanation! 

**For problem 1: logging failure**
> Creating a SummaryWriter is analogous to calling Python’s open builtin, which does throw if the file can’t be opened. 
> Semantically, it seems to me that writing summaries is an important part of the training process, and if your model were to be silently training for hours or days but not actually writing any metrics, you might be pretty dismayed when you found out.

Thanks for that insight. I saw different people might have different expectation on logger behavior. 

Seems in python logger, both `logging.basicConfig` and `logging.FileHandler` will throw if file is inaccessible, but `logging.warn` won't throw if file becomes inaccessible midway, which is the same behavior as TensorBoard logger that you explained. Agree that it helps avoid the surprise that logging never happens.

Internally, people usually will only use python logger to log to stream which is very stable, and for logging to files, our internal logger will only throw in sandbox/intern, but not prod, to prioritize service SLA over debuggability. The logger problems are logged separately into another system though. So people might have the expectation that logging code will never impact service SLA.

So I don't feel strongly about this, we might discuss internally on whether we'll tweak this behavior for internal only.


**For problem 2: empty files**
> I imagine that any flag/behavior change here would keep the add_event and only bypass the flush, right?
>   I’d be happy to accept a patch that deferred this flush, as long as the writer still properly fails when the directory isn’t writable.

Unfortunately only deferring the flush would not solve the empty file problem, we would need to either:
- Never flush if only timestamp is in the queue
- Or bypass the write timestamp completely

It seems timestamp is still useful and neither of these two are easy, so we'll also look into lazy creation of SummaryWriter on the client side.
