### ISSUE TITLE
Can't launch TensorBoard from within Anaconda: typing-extensions not found

### ISSUE THREAD

**Issue by SeasonedLeo** [tensorflow/tensorboard#4217]
I have installed Anaconda Python 3.7.9 and TensorFlow 2.1 and also tried TensorFlow 2.0 . 
Tensorflow is working fine from the command prompt, in jupyter notebook . However, When I launch Tensorboard I get the following error and Tensor board fails to launch.  As recommended I have asked this question on stack over flow have not recieved any answers. Please provide some inputs . I have tried to uninstall anaconda multiple times. Also have tensorflow in other virtual environments as well ,tensorboard not working there as well . 

The error i get is following : 

```
ERROR: Failed to launch TensorBoard (exited with 1). Contents of stderr:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\tensorboard-script.py", line 9, in <module>
  sys.exit(run_main()) 
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorboard\main.py", line 65, in run_main default.get_plugins()
  + default.get_dynamic_plugins(), 
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorboard\default.py", line 125, in get_dynamic_plugins
  "tensorboard_plugins" 
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorboard\default.py", line 124, in <listcomp>
  for entry_point in pkg_resources.iter_entry_points( 
File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2442, in load
  self.require(*args, **kwargs) 
File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2465, in require
  items = working_set.resolve(reqs, env, installer, extras=self.extras) 
File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
  raise DistributionNotFound(req, requirers) pkg_resources.DistributionNotFound: The 'typing-extensions>=3.7.4; python_version < "3.8"' distribution was not found and is required by yarl
```

**Comment by debsuvra** [comment]
You don't have the `typing-extensions` package installed and tensorboard requires that. Install it using `conda install` and you should be good to go.

**Comment by wchargin** [comment]
Hi @SeasonedLeo! Thanks for reaching out, and sorry that you’re having
setup problems. The Anaconda build for TensorFlow is actually maintained
by the community, not the TensorFlow team, so it’s a bit hard for us to
guess at what’s going wrong here. It does look like the error is related
to `typing-extensions` being transitively required but not present; have
you tried `conda install` or `pip install`ing it?

One safe solution would be to try making a fresh virtualenv outside of
Anaconda and installing `tensorflow` and `jupyter` into it.

**Comment by SeasonedLeo** [comment]
Thanks I think it was indeed related to type extension . Closing issue
