### ISSUE TITLE
No recognized filesystem for prefix s3

### ISSUE THREAD

**Issue by tekumara** [tensorflow/tensorboard#4294]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 724b56cee52e7d8eb89bbeec1f0d5ce3e38c9682

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Darwin', nodename='TEKUMARA', release='19.6.0', version='Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/Users/tekumara/.virtualenvs/tmp-8ca152443f4af50'

--- check: installed_packages
INFO: installed: tensorboard==2.3.0
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.3.0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "/tmp/diagnose_tensorboard.py", line 487, in main
    suggestions.extend(check())
  File "/tmp/diagnose_tensorboard.py", line 78, in wrapper
    result = fn()
  File "/tmp/diagnose_tensorboard.py", line 270, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/Users/tekumara/.virtualenvs/tmp-8ca152443f4af50/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'TEKUMARA'

--- check: stat_tensorboardinfo
INFO: directory: /var/folders/00/3ln54lf50bv0bhyp38nskdhr0000gn/T/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=68966683, st_dev=16777220, st_nlink=2, st_uid=501, st_gid=20, st_size=64, st_atime=1604732765, st_mtime=1604890080, st_ctime=1604890080)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/Users/tekumara/.virtualenvs/tmp-8ca152443f4af50/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.11.0
cachetools==4.1.1
certifi==2020.11.8
chardet==3.0.4
google-auth==1.23.0
google-auth-oauthlib==0.4.2
grpcio==1.33.2
idna==2.10
importlib-metadata==2.0.0
Markdown==3.3.3
numpy==1.19.4
oauthlib==3.1.0
pip==20.2.3
protobuf==3.13.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
setuptools==50.2.0
six==1.15.0
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
urllib3==1.25.11
Werkzeug==1.0.1
wheel==0.35.1
zipp==3.4.0

``````

</details>

## Steps to reproduce (required)

1. Make a new virtualenv
1. `pip install tensorboard`
1. `tensorboard --logdir s3://tblogs/experiment/100/trial/100/`

    ```
    TensorFlow installation not found - running with reduced feature set.
    Exception in thread Reloader:
    Traceback (most recent call last):
    File "/Users/tekumara/.pyenv/versions/3.7.9/lib/python3.7/threading.py", line 926, in _bootstrap_inner
        self.run()
    File "/Users/tekumara/.pyenv/versions/3.7.9/lib/python3.7/threading.py", line 870, in run
        self._target(*self._args, **self._kwargs)
    File "/Users/tekumara/.virtualenvs/tmp-8ca152443f4af50/lib/python3.7/site-packages/tensorboard/backend/event_processing/data_ingester.py", line 100, in _reload
        self._multiplexer.AddRunsFromDirectory(path, name)
    File "/Users/tekumara/.virtualenvs/tmp-8ca152443f4af50/lib/python3.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 202, in AddRunsFromDirectory
        for subdir in io_wrapper.GetLogdirSubdirectories(path):
    File "/Users/tekumara/.virtualenvs/tmp-8ca152443f4af50/lib/python3.7/site-packages/tensorboard/backend/event_processing/io_wrapper.py", line 206, in GetLogdirSubdirectories
        if not tf.io.gfile.exists(path):
    File "/Users/tekumara/.virtualenvs/tmp-8ca152443f4af50/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 613, in exists
        return get_filesystem(filename).exists(filename)
    File "/Users/tekumara/.virtualenvs/tmp-8ca152443f4af50/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 81, in get_filesystem
        raise ValueError("No recognized filesystem for prefix %s" % prefix)
    ValueError: No recognized filesystem for prefix s3
    ```

I have the `AWS_DEFAULT_REGION` and `AWS_REGION` environment variables set.

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow and Tensorboard version. 

If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by nfelt** [comment]
S3 support requires that you have `boto3` installed - can you try pip installing that?

See:
https://github.com/tensorflow/tensorboard/blob/8bdcdeea2b68c6772fab221f75a0e6bfb32bf78d/tensorboard/compat/tensorflow_stub/io/gfile.py#L34-L40

**Comment by tekumara** [comment]
That works, thanks @nfelt ! 🙇
