### ISSUE TITLE
TensorFlow 2.4.1 - TensorBoard profiler dashboard is missing

### ISSUE THREAD

**Issue by yisitu** [tensorflow/tensorboard#4781]
## Environment information (required)

(venv_tensorboard) yisitu@a-yisitu-tensorflow-serving:~$ python3 ./diagnose_tensorboard.py 
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='a-yisitu-tensorflow-serving', release='5.4.0-1037-gcp', version='#40~18.04.1-Ubuntu SMP Fri Feb 5 15:41:35 UTC 2021', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/home/yisitu/venv_tensorboard'

--- check: installed_packages
INFO: installed: tensorboard==2.4.1
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']
INFO: installed: tensorboard-data-server==0.4.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.4.1'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "./diagnose_tensorboard.py", line 522, in main
    suggestions.extend(check())
  File "./diagnose_tensorboard.py", line 75, in wrapper
    result = fn()
  File "./diagnose_tensorboard.py", line 278, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: data server binary: '/home/yisitu/venv_tensorboard/lib/python3.6/site-packages/tensorboard_data_server/bin/server'
Traceback (most recent call last):
  File "./diagnose_tensorboard.py", line 522, in main
    suggestions.extend(check())
  File "./diagnose_tensorboard.py", line 75, in wrapper
    result = fn()
  File "./diagnose_tensorboard.py", line 301, in tensorboard_data_server_version
    check=True,
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/yisitu/venv_tensorboard/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'a-yisitu-tensorflow-serving.c.a-yisitu-oss.internal'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=2076785, st_dev=2049, st_nlink=2, st_uid=1001, st_gid=1002, st_size=4096, st_atime=1615855167, st_mtime=1615856391, st_ctime=1615856391)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/yisitu/venv_tensorboard/lib/python3.6/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.12.0
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
blinker==1.4
cachetools==4.2.1
certifi==2020.12.5
chardet==4.0.0
click==6.7
cloud-init==20.4
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
distro-info===0.18ubuntu0.18.04.1
google-auth==1.27.1
google-auth-oauthlib==0.4.3
grpcio==1.36.1
gviz-api==1.9.0
httplib2==0.9.2
hyperlink==17.3.1
idna==2.10
importlib-metadata==3.7.3
incremental==16.10.1
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
Markdown==3.3.4
MarkupSafe==1.0
netifaces==0.10.4
numpy==1.19.5
oauthlib==3.1.0
PAM==0.4.2
pip==21.0.1
pkg-resources==0.0.0
protobuf==3.15.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
pyOpenSSL==17.5.0
pyserial==3.4
python-apt==1.6.5+ubuntu0.5
python-debian==0.1.32
pyxdg==0.25
PyYAML==3.12
requests==2.25.1
requests-oauthlib==1.3.0
requests-unixsocket==0.1.5
rsa==4.7.2
SecretStorage==2.3.1
service-identity==16.0.0
setuptools==54.1.2
six==1.15.0
ssh-import-id==5.7
systemd-python==234
tensorboard==2.4.1
tensorboard-data-server==0.4.0
tensorboard-plugin-profile==2.4.0
tensorboard-plugin-wit==1.8.0
Twisted==17.9.0
typing-extensions==3.7.4.3
ufw==0.36
unattended-upgrades==0.1
urllib3==1.26.4
virtualenv==15.1.0
Werkzeug==1.0.1
wheel==0.36.2
zipp==3.4.1
zope.interface==4.3.2

``````

</details>

### Next steps
(blank)

## Issue description

I was working on TensorFlow Serving bug https://github.com/tensorflow/serving/issues/1755, and found that the "PROFILE" dashboard is missing.

Ran TensorBoard like this:
```
(venv_tensorboard) yisitu@a-yisitu-tensorflow-serving:~$ tensorboard --logdir=/tmp/tensorboard --bind_all --logtostderr --verbosity=0
TensorFlow installation not found - running with reduced feature set.
I0316 01:02:39.342621 139774070236992 plugin_event_multiplexer.py:106] Event Multiplexer initializing.
I0316 01:02:39.342793 139774070236992 plugin_event_multiplexer.py:125] Event Multiplexer done initializing
I0316 01:02:39.342842 139774070236992 data_ingester.py:124] Launching reload in a daemon thread
I0316 01:02:39.343115 139768309319424 data_ingester.py:98] TensorBoard reload process beginning
I0316 01:02:39.343456 139768309319424 plugin_event_multiplexer.py:201] Starting AddRunsFromDirectory: /tmp/tensorboard
I0316 01:02:39.343967 139768309319424 io_wrapper.py:227] GetLogdirSubdirectories: Starting to list directories via walking.
I0316 01:02:39.344612 139768309319424 plugin_event_multiplexer.py:207] Done with AddRunsFromDirectory: /tmp/tensorboard
I0316 01:02:39.344689 139768309319424 data_ingester.py:102] TensorBoard reload process: Reload the whole Multiplexer
I0316 01:02:39.344735 139768309319424 plugin_event_multiplexer.py:212] Beginning EventMultiplexer.Reload()
I0316 01:02:39.344840 139768309319424 plugin_event_multiplexer.py:256] Reloading runs serially (one after another) on the main thread.
I0316 01:02:39.344893 139768309319424 plugin_event_multiplexer.py:265] Finished with EventMultiplexer.Reload()
I0316 01:02:39.345601 139768309319424 data_ingester.py:107] TensorBoard done reloading. Load took 0.002 secs
TensorBoard 2.4.1 at http://a-yisitu-tensorflow-serving.c.a-yisitu-oss.internal:6006/ (Press CTRL+C to quit)

```

On the TensorBoard page, the PROFILE dashboard is missing. When directly navigated to via `http://localhost:6006/#profile` (port forwarding in play), it says:

> There’s no dashboard by the name of “profile”.
> You can select a dashboard from the list above.
> 
> Last reload: Mar 15, 2021, 6:04:36 PM
> Log directory: /tmp/tensorboard

**Comment by wchargin** [comment]
For posterity: it looks like this was just a bad copy of TensorFlow.
