### ISSUE TITLE
Cannot run profile demo: no field timestamp_ns

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#493]
This is `tensorflow-nightly-20170901`. Let me know if you need additional info.
```
$ bazel run tensorboard/plugins/profile:profile_demo
INFO: Analysed target //tensorboard/plugins/profile:profile_demo (0 packages loaded).
INFO: Found 1 target...
Target //tensorboard/plugins/profile:profile_demo up-to-date:
  bazel-bin/tensorboard/plugins/profile/profile_demo
INFO: Elapsed time: 0.219s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/tensorboard/plugins/profile/profile_demo
Traceback (most recent call last):
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/profile/profile_demo.py", line 77, in <module>
Saving output to /tmp/profile_demo.
Directory /tmp/profile_demo/plugins/profile already exists.
Directory /tmp/profile_demo/plugins/profile/foo already exists.
    tf.app.run()
  File "/home/wchargin/virtualenv/tensorflow-nightly-20170901/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/profile/profile_demo.py", line 72, in main
    dump_data(LOGDIR)
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/profile/profile_demo.py", line 60, in dump_data
    text_format.Merge(profile_demo_data.TRACES[run], proto)
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/protobuf/python/google/protobuf/text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/protobuf/python/google/protobuf/text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/protobuf/python/google/protobuf/text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/protobuf/python/google/protobuf/text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/protobuf/python/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/protobuf/python/google/protobuf/text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/wchargin/.cache/bazel/_bazel_wchargin/3f99396cfb979f2f5a2059c1fd233f92/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/plugins/profile/profile_demo.runfiles/protobuf/python/google/protobuf/text_format.py", line 643, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 23:3 : Message type "tensorboard.profile.TraceEvent" has no field named "timestamp_ns".
ERROR: Non-zero return code '1' from command: Process exited with status 1
[$ pip --version
pip 9.0.1 from /home/wchargin/virtualenv/tensorflow-nightly-20170901/local/lib/python2.7/site-packages (python 2.7)
$ pip freeze
autograd==1.1.13
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0rc1
bleach==1.5.0
decorator==4.1.2
enum34==1.1.6
funcsigs==1.0.2
future==0.16.0
futures==3.1.1
grpc==0.3.post19
grpcio==1.6.0
html5lib==0.9999999
ipython==5.4.0
ipython-genutils==0.2.0
Markdown==2.6.9
mock==2.0.0
msgpack-python==0.4.8
numpy==1.13.1
pathlib2==2.3.0
pbr==3.1.1
pexpect==4.2.1
pickleshare==0.7.4
pkg-resources==0.0.0
prompt-toolkit==1.0.15
protobuf==3.4.0
ptyprocess==0.5.2
Pygments==2.2.0
scandir==1.5
simplegeneric==0.8.1
six==1.10.0
tensorflow==1.3.0
tensorflow-tensorboard==0.1.5
traitlets==4.3.2
wcwidth==0.1.7
Werkzeug==0.12.2
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
```

**Comment by wchargin** [comment]
@ioeric please investigate?

**Comment by ioeric** [comment]
Sent https://github.com/tensorflow/tensorboard/pull/499

**Comment by wchargin** [comment]
@ioeric Thanks!
