### ISSUE TITLE
--logdir flag does not change directory. Always points to the same directory

### ISSUE THREAD

**Issue by j718** [tensorflow/tensorboard#5214]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
INFO: os.name: nt
INFO: os.uname(): N/A
INFO: sys.getwindowsversion(): sys.getwindowsversion(major=10, minor=0, build=22000, platform=2, service_pack='')

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
WARNING: no installation among: ['tb-nightly', 'tensorboard', 'tensorflow-tensorboard']
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.5.0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "C:\Users\jacob\diagnose.py", line 522, in main
    suggestions.extend(check())
  File "C:\Users\jacob\diagnose.py", line 75, in wrapper
    result = fn()
  File "C:\Users\jacob\diagnose.py", line 278, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: data server binary: None

--- check: tensorboard_binary_path
INFO: which tensorboard: b'C:\\Users\\jacob\\miniconda3\\Scripts\\tensorboard.exe\r\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'DESKTOP-UG4LT1V'

--- check: stat_tensorboardinfo
INFO: directory: C:\Users\jacob\AppData\Local\Temp\.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['C:\\Users\\jacob\\miniconda3\\lib\\site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1623774798911/work
aiohttp @ file:///D:/bld/aiohttp_1623682523147/work
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_1603108395799/work
async-timeout==3.0.1
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work
blinker==1.4
brotlipy==0.7.0
CacheControl==0.12.6
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1619593780156/work
cachy==0.3.0
certifi==2021.5.30
cffi @ file:///D:/bld/cffi_1625835466651/work
chardet @ file:///D:/bld/chardet_1610093673558/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1626371162869/work
cleo @ file:///home/conda/feedstock_root/build_artifacts/cleo_1602266613143/work
click @ file:///D:/bld/click_1621503904640/work
clikit @ file:///home/conda/feedstock_root/build_artifacts/clikit_1591735638473/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
conda==4.10.3
conda-package-handling @ file:///D:/bld/conda-package-handling_1618231584104/work
crashtest==0.3.0
cryptography @ file:///D:/bld/cryptography_1616851819782/work
cupy @ file:///D:/bld/cupy_1624658426652/work
distlib @ file:///home/conda/feedstock_root/build_artifacts/distlib_1622292800270/work
fastrlock==0.6
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1589994591731/work
google-auth @ file:///home/conda/feedstock_root/build_artifacts/google-auth_1627569118436/work
google-auth-oauthlib==0.4.5
grpcio==1.39.0
html5lib @ file:///home/conda/feedstock_root/build_artifacts/html5lib_1592930327044/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1609836280497/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1607548121797/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1614815863336/work
keyring @ file:///D:/bld/keyring_1607550048767/work
lockfile==0.12.2
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1614595805172/work
menuinst==1.4.16
msgpack @ file:///D:/bld/msgpack-python_1610122018553/work
multidict @ file:///D:/bld/multidict_1610319160902/work
numpy @ file:///D:/bld/numpy_1626648564420/work
oauthlib @ file:///home/conda/feedstock_root/build_artifacts/oauthlib_1622563202229/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1612459636436/work
pastel==0.2.0
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pip==21.2.3
pkginfo @ file:///home/conda/feedstock_root/build_artifacts/pkginfo_1625854086923/work
poetry @ file:///D:/bld/poetry_1624648407860/work
poetry-core @ file:///home/conda/feedstock_root/build_artifacts/poetry-core_1617989199588/work
protobuf==3.17.3
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat @ file:///D:/bld/pycosat_1610095047168/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1619620644068/work
pylev==1.3.0
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1608055815057/work
pyparsing==2.4.7
pyrsistent @ file:///D:/bld/pyrsistent_1607553974902/work
PySocks @ file:///D:/bld/pysocks_1610291737679/work
pyu2f @ file:///home/conda/feedstock_root/build_artifacts/pyu2f_1604248910016/work
pywin32==301
pywin32-ctypes @ file:///D:/bld/pywin32-ctypes_1610168398600/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1626393743643/work
requests-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/requests-oauthlib_1595492159598/work
requests-toolbelt==0.9.1
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1614171254180/work
ruamel-yaml-conda @ file:///D:/bld/ruamel_yaml_1611943595088/work
setuptools==49.6.0.post20210108
shellingham @ file:///home/conda/feedstock_root/build_artifacts/shellingham_1612179560728/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
tensorboard @ file:///home/conda/feedstock_root/build_artifacts/tensorboard_1623455378804/work/tensorboard-2.5.0-py3-none-any.whl
tensorboard-data-server==0.6.1
tensorboard-plugin-wit @ file:///home/conda/feedstock_root/build_artifacts/tensorboard-plugin-wit_1611075653546/work/tensorboard_plugin_wit-1.8.0-py3-none-any.whl
tensorboardX==2.4
tomlkit @ file:///D:/bld/tomlkit_1621900079124/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1627689047698/work
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1622748266870/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1624634538755/work
virtualenv @ file:///D:/bld/virtualenv_1621891842940/work
webencodings==0.5.1
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1621518206714/work
wheel==0.36.2
win-inet-pton @ file:///D:/bld/win_inet_pton_1610147566412/work
wincertstore==0.2
yarl @ file:///D:/bld/yarl_1625233126428/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1625284368454/work

``````

</details>

## Issue description

I created a log folder at ~/proj/lightning_logs. Now every project that I run tensorboard from only looks at that folder. For example. 

```
cd ~/proj2
tensorboard --logdir ./lightning_logs
```

Will still only look at the logs in ~/proj/lightning_logs. I have tried uninstalling and reinstalling tensorboard multiple times.

Thank you for your help.

**Comment by stephanwlee** [comment]
Hi there, could you please include a little bit more information? Specifically, I would like to see what TensorBoard prints when you launch it. It always includes port number and if you have multiple instances running simultaneously, it will increment the port number (e.g., 6006 vs 6007).

**Comment by j718** [comment]
This is a little silly. It looks like I had another vscode window open that already had it running in the background. A restart fixed it. Maybe it would be good to send an error that there is another process running already if a second process is opened.
