### ISSUE TITLE
`context.multiplexer` is None, `example_basic` plugin doesn't work

### ISSUE THREAD

**Issue by AnimeshSinha1309** [tensorflow/tensorboard#5355]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='animesh-laptop', release='5.11.0-37-generic', version='#41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.6.0
INFO: installed: tensorflow==2.6.0
INFO: installed: tensorflow-estimator==2.6.0
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.6.0'

--- check: tensorflow_python_version
2021-10-01 14:59:59.191038: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-01 14:59:59.191070: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO: tensorflow.__version__: '2.6.0'
INFO: tensorflow.__git_version__: 'v2.6.0-rc2-32-g919f693420e'

--- check: tensorboard_data_server_version
INFO: data server binary: '/home/animesh/Software/anaconda/envs/mlq-visualizers/lib/python3.9/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/animesh/Software/anaconda/envs/mlq-visualizers/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'animesh-laptop'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=31195312, st_dev=2056, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1633021534, st_mtime=1633080568, st_ctime=1633080568)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/animesh/Software/anaconda/envs/mlq-visualizers/lib/python3.9/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.13.0
argon2-cffi==21.1.0
astunparse==1.6.3
attrs==21.2.0
backcall==0.2.0
black==21.9b0
bleach==4.1.0
cachetools==4.2.2
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.6
clang==5.0
click==8.0.1
cycler==0.10.0
debugpy==1.4.3
decorator==5.1.0
defusedxml==0.7.1
entrypoints==0.3
flatbuffers==1.12
gast==0.4.0
google-auth==1.35.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
greenlet @ file:///home/conda/feedstock_root/build_artifacts/greenlet_1628272056983/work
grpcio==1.40.0
h5py==3.1.0
idna==3.2
ipykernel==6.4.1
ipython==7.27.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.0
Jinja2==3.0.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==7.0.3
jupyter-console==6.4.0
jupyter-core==4.8.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
keras==2.6.0
Keras-Preprocessing==1.1.2
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1630173722292/work
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1628881762877/work
matplotlib-inline==0.1.3
mistune==0.8.4
-e git+ssh://git@github.com/AnimeshSinha1309/mlq-visualizers@58045db87fd2aa579f4dee0243f4fdac08800572#egg=molecular_graphs
mypy-extensions==0.4.3
nbclient==0.5.4
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.4
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1629092040774/work
oauthlib==3.1.1
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
opt-einsum==3.3.0
packaging==21.0
pandas==1.3.3
pandocfilters==1.5.0
parso==0.8.2
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1602493092985/work
pip==21.2.4
platformdirs==2.4.0
prometheus-client==0.11.0
prompt-toolkit==3.0.20
protobuf==3.18.0
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.20.1
pycparser==2.20
Pygments==2.10.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1612179539967/work
pyzmq==22.3.0
qtconsole==5.1.1
QtPy==1.11.1
regex==2021.9.30
reportlab==3.5.68
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
Send2Trash==1.8.0
setuptools==58.0.4
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
SQLAlchemy @ file:///home/conda/feedstock_root/build_artifacts/sqlalchemy_1629314941805/work
tensorboard==2.6.0
tensorboard-data-server==0.6.1
-e git+https://github.com/tensorflow/tensorboard@c9e2b4d22c5bfd777e9594d95fc0e04aad790a06#egg=tensorboard_plugin_example&subdirectory=tensorboard/examples/plugins/example_basic
tensorboard-plugin-wit==1.8.0
tensorflow==2.6.0
tensorflow-estimator==2.6.0
termcolor==1.1.0
terminado==0.12.1
testpath==0.5.0
tomli==1.2.1
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1610094708661/work
traitlets==5.1.0
typing-extensions==3.10.0.2
urllib3==1.26.6
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.1
wheel==0.37.0
widgetsnbextension==3.5.1
wrapt==1.12.1

``````

</details>

## Issue Description

The `example_basic` plugin doesn't work for me. The `example_raw_scalars` does work.
Thise seems to be because `context.multiplexer` is None, so the `PluginRunToTagToContent` cannot be called.

### Getting to the Error

After cloning and installing the requirements in a conda enviroment, I did the following:
```sh
cd tensorboard/examples/plugins/example_basic
python demo.py
tensorboard --log-dir demo-logs/
```

### Error Message

```
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.6.0 at http://localhost:6006/ (Press CTRL+C to quit)
E1001 15:03:32.696796 139665710098176 application.py:442] Plugin listing: is_active() for example_basic failed (marking inactive)
Traceback (most recent call last):
  File "/home/animesh/Software/anaconda/envs/mlq-visualizers/lib/python3.9/site-packages/tensorboard/backend/application.py", line 433, in _serve_plugins_listing
    is_active = plugin.is_active()
  File "/home/animesh/Code/OpenSRC/tensorboard/tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py", line 47, in is_active
    self._multiplexer.PluginRunToTagToContent(metadata.PLUGIN_NAME)
AttributeError: 'NoneType' object has no attribute 'PluginRunToTagToContent'
E1001 15:03:36.267743 139663667705600 application.py:442] Plugin listing: is_active() for example_basic failed (marking inactive)
Traceback (most recent call last):
  File "/home/animesh/Software/anaconda/envs/mlq-visualizers/lib/python3.9/site-packages/tensorboard/backend/application.py", line 433, in _serve_plugins_listing
    is_active = plugin.is_active()
  File "/home/animesh/Code/OpenSRC/tensorboard/tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py", line 47, in is_active
    self._multiplexer.PluginRunToTagToContent(metadata.PLUGIN_NAME)
AttributeError: 'NoneType' object has no attribute 'PluginRunToTagToContent'
```

**Comment by japie1235813** [comment]
Hello,

on thing I noticed is the command you're running is different from the [instruction](https://github.com/tensorflow/tensorboard/tree/master/tensorboard/examples/plugins/example_basic)
did you link the plugin to your virtual env?

also, where is your `demo-logs/` located? Please double check you have the right path.  The error suggests there is no plugin so I guess something went wrong when reading the file.

**Comment by AnimeshSinha1309** [comment]
I did register the plugin with `python setup.py develop`, sorry I didn't add that to the reproducing steps.

And the instructions don't seem correct, they suggest that the logs are in `/tmp/<some-folder>`, but they aren't. They are in `demo-logs` in the local directory, as created by the line below.
https://github.com/tensorflow/tensorboard/blob/ef3feb7fdd2a4d9ffa221a6ca6db3f9b33a9f8c7/tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/demo.py#L25

I am sure that the directory exists, the plugin is registered, which is why I can even get an error, otherwise TFBoard would never run the plugin. The issue seems to be in the fact that `context.multiplexer` is no longer a thing, and all other plugins use `context.data_provider`. I believe some fixes need to be made to this example plugin.

**Comment by japie1235813** [comment]
Thanks for the comment. I'm able to reproduce the issue. Looking into it.
(I was confused by your cd path, `demo.py` is located nested in  `tensorboard_plugin_example`

**Comment by AnimeshSinha1309** [comment]
Thanks, I will clone and see if this is working and if it solves my issue on the custom plugin too, thanks a lot for the fix.
