### ISSUE TITLE
The tensorboard is blocked by "/data/plugins_listing"

### ISSUE THREAD

**Issue by hanyang-sh** [tensorflow/tensorboard#5481]
I just run the basic code as follow:
```py
import numpy as np
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter()

for n_iter in range(100):
    writer.add_scalar('Loss/train', np.random.random(), n_iter)
    writer.add_scalar('Loss/test', np.random.random(), n_iter)
    writer.add_scalar('Accuracy/train', np.random.random(), n_iter)
    writer.add_scalar('Accuracy/test', np.random.random(), n_iter)
```
and run the following script
```bash
tensorboard --logdir runs/
```
and generate the following
![image](https://user-images.githubusercontent.com/31543505/147915805-3eb080f3-353a-44aa-a747-4ae069d8905d.png)
but when I open it in the browser, I get
![image](https://user-images.githubusercontent.com/31543505/147915858-639ea769-7e66-4cdc-93ce-b274d811c13b.png)
I open the browser F12, and find the API *http://localhost:6006/data/plugins_listing*, I find it's pending and never gets a response.
![image](https://user-images.githubusercontent.com/31543505/147916085-e22651e9-51b8-4515-9171-ef0d0554f290.png)
Hope to get your attention and help, thanks a lot!!

**Comment by sanatmpa1** [comment]
@hanyang-sh,

Can you take a look at this [issue](https://github.com/tensorflow/tensorboard/issues/2102) and this [pull](https://github.com/tensorflow/tensorboard/pull/1931) raised for this [similar issue](https://github.com/tensorflow/tensorboard/issues/625) may be a possibility. Can you try out few manual refreshes in this screen and confirm if the problem still persists? Thanks!

**Comment by bmd3k** [comment]
Hi @hanyang-sh, sorry you are having trouble. This might be difficult to diagnose but let's give it a try. Can you help us by doing the following?

1. Call writer.close() at the end of your script to ensure file contents are flushed and released and then try again. I don't know much about pytorch summary writing so this is just a wild guess.

2. Provide more information about your system using diagnose_tensorboard.py, as mentioned in the default bug template?

3. Provide more detailed logs by running tensorboard with `--verbosity=1`?

4. Let us know if you are aware whether there is anything notable about your file system. For example, is it over a network?

**Comment by bmd3k** [comment]
5. Also, could you retry with latest tensorboard (2.7.0) and/or tb-nightly?

**Comment by sanatmpa1** [comment]
@hanyang-sh,

Can you take a look at the above comments by @bmd3k and let us know if it helps. Thanks!

**Comment by hanyang-sh** [comment]
Sorry to respond slowly!
1. As I call `writer.close()` at the end, it doesn't work!
2. As I run the `diagnose_tensorboard.py`, I got
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='lab4074-PowerEdge-T640', release='5.11.0-43-generic', version='#47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tb-nightly==2.8.0a20220103
INFO: installed: tensorflow==2.5.0
INFO: installed: tensorflow-estimator==2.5.0
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.8.0a20220103'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '2.5.0'
INFO: tensorflow.__git_version__: 'v2.5.0-rc3-213-ga4dfb8d1a71'

--- check: tensorboard_data_server_version
INFO: data server binary: '/home/hanyang/.local/lib/python3.8/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/hanyang/.conda/envs/hanyang/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'lab4074-PowerEdge-T640'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=33423391, st_dev=2053, st_nlink=2, st_uid=1001, st_gid=1001, st_size=4096, st_atime=1641200669, st_mtime=1641971868, st_ctime=1641971868)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/hanyang/.conda/envs/hanyang/lib/python3.8/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.13.0
aiohttp==3.8.1
aiosignal==1.2.0
asgiref==3.4.1
astunparse==1.6.3
async-timeout==4.0.2
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
baidu-aip==2.2.18.0
blessings==1.7
blinker==1.4
brotlipy==0.7.0
cachetools==4.2.2
camelot-py==0.10.1
certifi==2021.10.8
cffi @ file:///tmp/build/80754af9/cffi_1625807838443/work
charset-normalizer==2.0.9
click==8.0.3
cryptography @ file:///tmp/build/80754af9/cryptography_1633520369403/work
debugpy @ file:///tmp/build/80754af9/debugpy_1637091796427/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1631346842025/work
dgl-cu111==0.7.1
Django==3.2.5
einops==0.3.0
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1605121927639/work/dist/entrypoints-0.3-py2.py3-none-any.whl
flatbuffers==1.12
frozenlist==1.2.0
fsspec==2021.11.1
gast==0.4.0
geographiclib==1.52
geopy==2.2.0
ghostscript==0.7
google-auth==1.32.1
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
googledrivedownloader==0.4
gpustat==0.6.0
grpcio==1.34.1
h5py==3.1.0
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1638542885373/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1641325327884/work/dist/ipykernel-6.6.1-py3-none-any.whl
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1638470220711/work
isodate==0.6.0
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1637175084646/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1637611911738/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1636814262349/work
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
loguru==0.5.3
Markdown==3.3.4
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
minepy==1.2.5
mkl-fft==1.3.1
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626186064646/work
mkl-service==2.4.0
multidict==5.2.0
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1638419302549/work
numpy==1.19.5
nvidia-ml-py3==7.352.0
oauthlib==3.1.1
olefile @ file:///Users/ktietz/demo/mc3/conda-bld/olefile_1629805411829/work
opencv-python==4.5.3.56
opt-einsum==3.3.0
pandas==1.3.0
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pathlib==1.0.1
pdfminer.six==20200517
pdfplumber==0.5.28
pdftopng==0.2.3
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==8.4.0
pip==21.2.4
pip-review==1.1.1
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1639065841292/work
protobuf==3.17.3
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.8.0
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pycryptodome==3.11.0
pyDeprecate==0.3.1
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1640969120816/work
PyJWT @ file:///tmp/build/80754af9/pyjwt_1619651636675/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1635333100036/work
PyPDF2==1.26.0
PySocks @ file:///tmp/build/80754af9/pysocks_1605305779399/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-louvain==0.15
pytorch-lightning==1.5.7
pytz==2021.3
pyzmq==19.0.2
rdflib==5.0.0
requests @ file:///tmp/build/80754af9/requests_1629994808627/work
requests-oauthlib==1.3.0
rsa==4.7.2
setuptools==58.0.4
six==1.15.0
sqlparse==0.4.1
tabulate==0.8.9
tb-nightly==2.8.0a20220103
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorboardX==2.4
tensorflow==2.5.0
tensorflow-estimator==2.5.0
termcolor==1.1.0
torch==1.10.1
torch-cluster==1.5.9
torch-geometric==1.7.2
torch-geometric-temporal==0.37
torch-scatter==2.0.7
torch-sparse==0.6.10
torch-spline-conv==1.2.1
torch-tb-profiler==0.2.0
torchaudio==0.10.1
torchmetrics==0.6.2
torchsummary==1.5.1
torchvision==0.11.2
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1610094706440/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1635260543454/work
typing-extensions==3.7.4.3
urllib3==1.26.7
Wand==0.6.7
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
Werkzeug @ file:///tmp/build/80754af9/werkzeug_1635505089296/work
wheel==0.37.0
wrapt==1.12.1
yarl==1.7.2
zipp @ file:///tmp/build/80754af9/zipp_1633618647012/work

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.
3. when I run it with --verbosity=1, I got a log as 
[ver.txt](https://github.com/tensorflow/tensorboard/files/7852522/ver.txt)
4. I run tensorboard in Linux, which I connect to it by ssh.
5. when I update tensorboard to 2.7.0, I got a ValueError as
```
2022-01-12 15:28:07.920410: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

I0112 15:28:08.856945 139626270455552 plugin.py:292] Monitor runs begin
Traceback (most recent call last):
  File "/home/hanyang/.conda/envs/hanyang/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/home/hanyang/.conda/envs/hanyang/lib/python3.8/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/home/hanyang/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/hanyang/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/hanyang/.conda/envs/hanyang/lib/python3.8/site-packages/tensorboard/program.py", line 276, in main
    return runner(self.flags) or 0
  File "/home/hanyang/.conda/envs/hanyang/lib/python3.8/site-packages/tensorboard/program.py", line 292, in _run_serve_subcommand
    server = self._make_server()
  File "/home/hanyang/.conda/envs/hanyang/lib/python3.8/site-packages/tensorboard/program.py", line 476, in _make_server
    app = application.TensorBoardWSGIApp(
  File "/home/hanyang/.conda/envs/hanyang/lib/python3.8/site-packages/tensorboard/backend/application.py", line 139, in TensorBoardWSGIApp
    return TensorBoardWSGI(
  File "/home/hanyang/.conda/envs/hanyang/lib/python3.8/site-packages/tensorboard/backend/application.py", line 252, in __init__
    raise ValueError(
ValueError: Duplicate plugins for name projector
```

**Comment by hanyang-sh** [comment]
I am sorry for my slow response and I found the reason for the ValueError refer to https://github.com/pytorch/pytorch/issues/22676, Thanks for your time and attention!!
