### ISSUE TITLE
Seemingly random TensorBoard logging error

### ISSUE THREAD

**Issue by mahenning** [tensorflow/tensorboard#5483]
## Environment information (required)

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:
<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='[sensitive]', release='4.14.13-tf1-ll', version='#2 SMP PREEMPT Wed Jan 17 08:23:25 CET 2018', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv'

--- check: installed_packages
INFO: installed: tensorboard==2.5.0
INFO: installed: tensorflow==2.3.3
INFO: installed: tensorflow-estimator==2.3.0
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.5.0'

--- check: tensorflow_python_version
2022-01-04 20:42:46.005862: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
INFO: tensorflow.__version__: '2.3.3'
INFO: tensorflow.__git_version__: 'v2.3.2-249-g3929ffacfbe'

--- check: tensorboard_data_server_version
INFO: data server binary: '/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorboard_data_server/bin/server'
Traceback (most recent call last):
  File "diagnose_tensorboard.py", line 522, in main
    suggestions.extend(check())
  File "diagnose_tensorboard.py", line 75, in wrapper
    result = fn()
  File "diagnose_tensorboard.py", line 301, in tensorboard_data_server_version
    check=True,
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): '[sensitive]'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.13.0
astor==0.8.1
astunparse==1.6.3
cachetools==4.2.2
certifi==2021.5.30
chardet==4.0.0
cycler==0.10.0
dataclasses==0.8
flatbuffers==1.12
gast==0.3.3
google-auth==1.32.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
graphviz==0.17
grpcio==1.38.1
h5py==2.10.0
haste-tf==0.5.0rc0
idna==2.10
importlib-metadata==4.5.0
joblib==1.0.1
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
Markdown==3.3.4
matplotlib==3.3.4
numpy==1.18.5
oauthlib==3.1.1
opt-einsum==3.3.0
Pillow==8.2.0
pip==21.1.2
pkg-resources==0.0.0
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydot==1.4.2
pydotplus==2.0.2
pyparsing==2.4.7
python-dateutil==2.8.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
scikit-learn==0.24.2
scipy==1.5.4
setuptools==57.0.0
six==1.16.0
sklearn==0.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.3.3
tensorflow-addons==0.13.0
tensorflow-estimator==2.3.0
termcolor==1.1.0
threadpoolctl==2.1.0
typeguard==2.12.1
typing-extensions==3.10.0.0
urllib3==1.26.5
Werkzeug==2.0.1
wheel==0.36.2
wrapt==1.12.1
zipp==3.4.1

``````

</details>

## Issue description

When running a time neural network and saving data in tensorboard, I randomly get the following error: (By randomly I mean that I have a batch of networks that run one after the other in a batch file and it is never the completely same network to get the error. Mostly GRU or BiGRU networks. Sometimes every network runs without this problem. Sometimes multiple networks are affected per run.)

2021-11-28 19:11:18.779759: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at summary_kernels.cc:106 : Permission denied: ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2; Permission denied
Failed to flush 2 events to ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2
Could not flush events file.
(Full traceback below)

I also tried to get the error with a simple code snipped with random input data for a minimum example, but could not get an error. As it is a really rarely and randomly occurring error in my code I'm not sure what I need to replicate it.
I hope I'm at the right place with this error. If I forgot any important info, please say so.

Full trace:
2021-11-28 19:11:18.779759: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at summary_kernels.cc:106 : Permission denied: ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2; Permission denied
Failed to flush 2 events to ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2
Could not flush events file.
Traceback (most recent call last):
File "main.py", line 312, in
main()
File "main.py", line 241, in main
validation_data=val_data, callbacks=keras_callbacks)
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
return method(self, *args, **kwargs)
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
callbacks.on_epoch_end(epoch, epoch_logs)
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 412, in on_epoch_end
callback.on_epoch_end(epoch, logs)
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 2179, in on_epoch_end
self._log_epoch_metrics(epoch, logs)
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 2220, in log_epoch_metrics
summary_ops_v2.scalar('epoch' + name, value, step=epoch)
File "/usr/lib/python3.6/contextlib.py", line 88, in exit
next(self.gen)
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 269, in as_default
self.flush()
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 286, in flush
return _flush_fn(writer=self)
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 967, in flush
return gen_summary_ops.flush_summary_writer(resource, name=name)
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 201, in flush_summary_writer
_ops.raise_from_not_ok_status(e, name)
File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
six.raise_from(core._status_to_exception(e.code, message), None)
File "", line 3, in raise_from
tensorflow.python.framework.errors_impl.PermissionDeniedError: ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2; Permission denied
Failed to flush 2 events to ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2
Could not flush events file. [Op:FlushSummaryWriter]

**Comment by bileschi** [comment]
Thanks for the report and sorry you are having trouble!

Looking at where the error is raised from, in combination that a minimal reproduction it seems likely this is an issue with contention over the ability to write the file:

https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/summary/summary_file_writer.cc;l=175?q=%22could%20not%20flush%20events%20file%22

It's difficult to diagnose or correct without a reproduction.  Tracking down the source of the error, through the `Flush` call in `RecordIO` [[LINK](https://cs.opensource.google/tensorflow/tensorflow/+/r2.3:tensorflow/core/lib/io/record_writer.cc;bpv=0;bpt=0;l=150)], it looks like it's bubbling up from the underlying filesystem.   If we assume that it may be Keras trying to write the same file multiple times, perhaps we can limit the likelihood by changing how often the data is written.  Can you reduce the `update_freq` parameter in your [[TensorBoard callback](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/python/keras/callbacks.py;l=2071?q=keras%2Fcallbacks.py)] to see if that helps?

If not, then we will need to see if we can share a repro case.

**Comment by mahenning** [comment]
Hi, 
sorry for posting so much later, but I want to clear things up, at least a bit. I couldn't test your proposed reduction on update_freq, because I already have measurements with freq 1 and I need to have the same freq for every dataset for eval. I also need every bit of time to work on this dataset, so unfortunately can't test it with dummy data.
I spoke with a few people that also work on this remote space and it seems to be indeed a (new) problem with the underlying file system where sometimes somewhere too many things get written and then this happens, not just to me. It's still annoying but now I know who's at fault. 
This gets supported by the fact that I couldn't reproduce the error on my local machine nor on another remote machine with dummy data.

But thank you for your help! Without your input I wouldn't have gotten the idea that it was a fault of the file system. And it's at least great news that it is not a bug with TB or smth like that.

**Comment by robclouth** [comment]
@mahenning  sorry to dig up a corpse but did you figure this out? i'm having the same problem. it fails after a few hours of training. i thought maybe it's because tensorboard is running in a separate process...

**Comment by mahenning** [comment]
Unfortunately, no. The remote machine/file system was from the university, so I reported it there, but it didn't get fixed while I was there. Maybe look for high write spikes or something like that. I'm not really sure what to look for, only that a generic "can't save" error happened to multiple people who worked on completely different projects.

My personal "fix" was to let it save the model every 10 or so epochs with a callback, and write a function to resume training of a model. In my function, I could give a folder, and it checked every subfolder for models that had not trained to x epochs (500 for me) and resumed them from the last save point. If you use TensorFlow, you can use the [initial_epoch](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit) parameter of the fit function to start from the correct epoch for TensorBoard and not overwrite the starting epochs when resuming. Hope it helps.

**Comment by robclouth** [comment]
ok thanks!
