### ISSUE TITLE
Debugger V2 is inactive because no data is available.

### ISSUE THREAD

**Issue by pwrliang** [tensorflow/tensorboard#5518]
## Environment information (required)
TensorFlow 2.8rc0 (I build it from source)
TensorBoard (Installed with pip on MacBook M1)

### Diagnostics (On my local computer which runs the TensorBoard)
```
<details>
<summary>Diagnostics output</summary>

--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=8, micro=9, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Darwin', nodename='Liangs-MacBook-Pro.local', release='21.2.0', version='Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000', machine='arm64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.8.0
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
INFO: installed: tensorflow-estimator==2.7.0
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.8.0'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '2.7.0'
INFO: tensorflow.__git_version__: 'unknown'

--- check: tensorboard_data_server_version
INFO: data server binary: None

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/Users/liang/Library/Python/3.8/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): '1.0.0.127.in-addr.arpa'

--- check: stat_tensorboardinfo
INFO: directory: /var/folders/d6/p_d03m7s485_12fwynwkps4c0000gp/T/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=2267416, st_dev=16777231, st_nlink=3, st_uid=502, st_gid=20, st_size=96, st_atime=1642729086, st_mtime=1642780210, st_ctime=1642780210)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/Users/liang/Library/Python/3.8/lib/python/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==1.0.0
astunparse==1.6.3
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.10
flatbuffers==2.0
gast==0.4.0
google-auth==2.3.3
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.43.0
h5py==3.6.0
idna==3.3
importlib-metadata==4.10.1
keras==2.7.0
Keras-Preprocessing==1.1.2
libclang==12.0.0
Markdown==3.3.6
numpy==1.22.1
oauthlib==3.1.1
opt-einsum==3.3.0
pip==21.3.1
protobuf==3.19.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.27.1
requests-oauthlib==1.3.0
rsa==4.8
setuptools==49.2.1
six @ file:///AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-103/six-1.15.0-py2.py3-none-any.whl
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.7.0
tensorflow-macos==2.7.0
termcolor==1.1.0
typing_extensions==4.0.1
urllib3==1.26.8
Werkzeug==2.0.2
wheel @ file:///AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-103/wheel-0.33.1-py2.py3-none-any.whl
wrapt==1.13.3
zipp==3.7.0

```

### Diagnostics (On the server which runs TensorFlow)

```
<details>
<summary>Diagnostics output</summary>

--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='', release='3.10.0-1127.19.1.el7.x86_64', version='#1 SMP Tue Aug 25 17:23:54 UTC 2020', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.7.0
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
INFO: installed: tf-estimator-nightly==2.8.0.dev2021122109
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.7.0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "diagnose_tensorboard.py", line 522, in main
    suggestions.extend(check())
  File "diagnose_tensorboard.py", line 75, in wrapper
    result = fn()
  File "diagnose_tensorboard.py", line 280, in tensorflow_python_version
    logging.info("tensorflow.__version__: %r", tf.__version__)
AttributeError: module 'tensorflow' has no attribute '__version__'

--- check: tensorboard_data_server_version
INFO: data server binary: '/home/geng.161/.pyenv/versions/3.8.3/lib/python3.8/site-packages/tensorboard_data_server/bin/server'
INFO: failed to check binary version: Command '['/home/geng.161/.pyenv/versions/3.8.3/lib/python3.8/site-packages/tensorboard_data_server/bin/server', '--version']' returned non-zero exit status 1.

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/usr/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): ''

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=268440070, st_dev=2430, st_nlink=2, st_uid=1127, st_gid=1141, st_size=6, st_atime=1642720356, st_mtime=1642597251, st_ctime=1642597251)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/geng.161/.pyenv/versions/3.8.3/lib/python3.8/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==1.0.0
astunparse==1.6.3
attrs==21.4.0
cachetools==4.2.4
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.10
cloudpickle==2.0.0
dill==0.3.4
flatbuffers==2.0
future==0.18.2
gast==0.5.3
google-auth==2.3.3
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.54.0
grpcio==1.43.0
h5py==3.6.0
horovod==0.23.0
idna==3.3
importlib-metadata==4.10.1
importlib-resources==5.4.0
keras==2.8.0rc1
Keras-Preprocessing==1.1.2
libclang==12.0.0
Markdown==3.3.6
numpy==1.22.1
oauthlib==3.1.1
opt-einsum==3.3.0
pip==21.3.1
promise==2.3
protobuf==3.19.3
psutil==5.9.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
PyYAML==6.0
requests==2.27.1
requests-oauthlib==1.3.0
rsa==4.8
setuptools==41.2.0
six==1.16.0
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-datasets==4.4.0
tensorflow-io-gcs-filesystem==0.23.1
tensorflow-metadata==1.6.0
termcolor==1.1.0
tf-estimator-nightly==2.8.0.dev2021122109
tqdm==4.62.3
typing_extensions==4.0.1
urllib3==1.26.8
Werkzeug==2.0.2
wheel==0.37.1
wrapt==1.13.3
zipp==3.7.0


</details>
```

</details>

## Issue description

I'm trying to debug with TensorFlow. I firstly run the following script on servers to collect dump files
```python
import tensorflow as tf
import tensorflow_datasets as tfds
import os
import json
import sys
import time
from absl import logging

num_epochs = 1
batch_size_per_replica = 64
learning_rate = 0.001

worker_idx = int(sys.argv[1])
num_workers = 2
os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["10.3.1.101:20000", "10.3.1.102:20000"]
    },
    'task': {'type': 'worker', 'index': worker_idx}
})

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '0'
os.environ['TF_CPP_MIN_VLOG_LEVEL'] = '3'

logging.set_verbosity(logging.DEBUG)

################ HERE ######################
tf.debugging.experimental.enable_dump_debug_info('/home/geng.161/my-tfdbg-dumps', tensor_debug_mode="FULL_HEALTH", circular_buffer_size=-1)
################ HERE ######################

strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
batch_size = batch_size_per_replica * num_workers

def resize(image, label):
    image = tf.image.resize(image, [224, 224]) / 255.0
    return image, label

dataset = tfds.load("cats_vs_dogs", split=tfds.Split.TRAIN, as_supervised=True)
dataset = dataset.map(resize).shuffle(1024).batch(batch_size)

with strategy.scope():
    model = tf.keras.applications.MobileNetV2(weights=None, classes=2)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        loss=tf.keras.losses.sparse_categorical_crossentropy,
        metrics=[tf.keras.metrics.sparse_categorical_accuracy]
    )

begin = time.time()
model.fit(dataset, epochs=num_epochs)
end = time.time()
print("Train Time: %s" % (end - begin))
```

Then I got following files:
```
****:/home/geng.161/my-tfdbg-dumps ll
total 176952
-rw-rw-r-- 1 geng.161 geng.161  5059338 Jan 20 21:04 tfdbg_events.1642730100.fpga01.cluster.execution
-rw-rw-r-- 1 geng.161 geng.161 46143327 Jan 20 21:04 tfdbg_events.1642730100.fpga01.cluster.graph_execution_traces
-rw-rw-r-- 1 geng.161 geng.161 29839627 Jan 20 21:04 tfdbg_events.1642730100.fpga01.cluster.graphs
-rw-rw-r-- 1 geng.161 geng.161       63 Jan 20 20:55 tfdbg_events.1642730100.fpga01.cluster.metadata
-rw-rw-r-- 1 geng.161 geng.161  9455439 Jan 20 21:04 tfdbg_events.1642730100.fpga01.cluster.source_files
-rw-rw-r-- 1 geng.161 geng.161    83195 Jan 20 21:04 tfdbg_events.1642730100.fpga01.cluster.stack_frames
-rw-rw-r-- 1 geng.161 geng.161  5056651 Jan 20 21:04 tfdbg_events.1642730108.fpga02.cluster.execution
-rw-rw-r-- 1 geng.161 geng.161 46146055 Jan 20 21:04 tfdbg_events.1642730108.fpga02.cluster.graph_execution_traces
-rw-rw-r-- 1 geng.161 geng.161 29839627 Jan 20 21:04 tfdbg_events.1642730108.fpga02.cluster.graphs
-rw-rw-r-- 1 geng.161 geng.161       63 Jan 20 20:55 tfdbg_events.1642730108.fpga02.cluster.metadata
-rw-rw-r-- 1 geng.161 geng.161  9455439 Jan 20 21:04 tfdbg_events.1642730108.fpga02.cluster.source_files
-rw-rw-r-- 1 geng.161 geng.161    83194 Jan 20 21:04 tfdbg_events.1642730108.fpga02.cluster.stack_frames
```

Then, I copied these files to my local computer which is a MacBook M1, and started TensorBoard to read these dumps.
```bash
liang@Liangs-MacBook-Pro.local:/Users/liang tensorboard --logdir ~/Downloads/my-tfdbg-dumps
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.8.0 at http://localhost:6006/ (Press CTRL+C to quit)
```

Unfortunately, I got this:
![image](https://user-images.githubusercontent.com/14839342/150558469-206b3984-3620-4802-b38f-3855a9e891cd.png)

**Comment by yatbear** [comment]
Hi @pwrliang, it seems that there was some issue with your distributed training setup, I tried your script, initially nothing was logged to the debug info directory, but once I removed the following the distributed training strategy and run the script like below:
```
import tensorflow as tf
import tensorflow_datasets as tfds
import os
import json
import sys
import time
from absl import logging

num_epochs = 1
# batch_size_per_replica = 64
batch_size = 64
learning_rate = 0.001

# worker_idx = int(sys.argv[1])
# num_workers = 2
# os.environ['TF_CONFIG'] = json.dumps({
#     'cluster': {
#         'worker': ["10.3.1.101:20000", "10.3.1.102:20000"]
#     },
#     'task': {'type': 'worker', 'index': worker_idx}
# })

# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '0'
# os.environ['TF_CPP_MIN_VLOG_LEVEL'] = '3'

logging.set_verbosity(logging.DEBUG)

################ HERE ######################
tf.debugging.experimental.enable_dump_debug_info('/home/geng.161/my-tfdbg-dumps', tensor_debug_mode="FULL_HEALTH", circular_buffer_size=-1)
################ HERE ######################

strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
# batch_size = batch_size_per_replica * num_workers

def resize(image, label):
    image = tf.image.resize(image, [224, 224]) / 255.0
    return image, label

dataset = tfds.load("cats_vs_dogs", split=tfds.Split.TRAIN, as_supervised=True)
dataset = dataset.map(resize).shuffle(1024).batch(batch_size)

# with strategy.scope():
model = tf.keras.applications.MobileNetV2(weights=None, classes=2)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
    loss=tf.keras.losses.sparse_categorical_crossentropy,
    metrics=[tf.keras.metrics.sparse_categorical_accuracy]
)

begin = time.time()
model.fit(dataset, epochs=num_epochs)
end = time.time()
print("Train Time: %s" % (end - begin))
```
I was able to see debugging information:
![image](https://user-images.githubusercontent.com/15273931/150602427-ad4daa2c-234a-4e9a-ace1-8dc8c9a0b772.png)

To further troubleshoot the distributed training setup, you can create an issue under https://github.com/tensorflow/tensorflow/issues. Thanks!

**Comment by pwrliang** [comment]
Thanks, @yatbear, I've opened a new issue in the TensorFlow repo.
