### ISSUE TITLE
Cachetools version conflict inside tensorboard

### ISSUE THREAD

**Issue by promach** [tensorflow/tensorboard#5572]
Why do I have `pkg_resources.ContextualVersionConflict: (cachetools 5.0.0 (/usr/lib/python3.10/site-packages), Requirement.parse('cachetools<5.0,>=2.0.0'), {'google-auth'})` ?

```
[phung@archlinux beginner_tutorial]$ tensorboard --logdir=runs
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cachetools 5.0.0 (/usr/lib/python3.10/site-packages), Requirement.parse('cachetools<5.0,>=2.0.0'), {'google-auth'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tensorboard", line 33, in <module>
    sys.exit(load_entry_point('tensorboard==2.8.0', 'console_scripts', 'tensorboard')())
  File "/usr/bin/tensorboard", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/usr/lib/python3.10/site-packages/tensorboard/default.py", line 30, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3266, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3278, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cachetools<5.0,>=2.0.0' distribution was not found and is required by google-auth
[phung@archlinux beginner_tutorial]$ 
[phung@archlinux beginner_tutorial]$ sudo pacman -S python-cachetools
warning: python-cachetools-5.0.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) python-cachetools-5.0.0-1

Total Installed Size:  0.09 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                                                 [########################################################################################] 100%
(1/1) checking package integrity                                                                                                               [########################################################################################] 100%
(1/1) loading package files                                                                                                                    [########################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [########################################################################################] 100%
(1/1) checking available disk space                                                                                                            [########################################################################################] 100%
:: Processing package changes...
(1/1) reinstalling python-cachetools                                                                                                           [########################################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[phung@archlinux beginner_tutorial]$ 
[phung@archlinux beginner_tutorial]$ sudo pacman -S tensorboard
[sudo] password for phung: 
warning: tensorboard-2.8.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) tensorboard-2.8.0-1

Total Installed Size:  19.70 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                                                 [########################################################################################] 100%
(1/1) checking package integrity                                                                                                               [########################################################################################] 100%
(1/1) loading package files                                                                                                                    [########################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [########################################################################################] 100%
(1/1) checking available disk space                                                                                                            [########################################################################################] 100%
:: Processing package changes...
(1/1) reinstalling tensorboard                                                                                                                 [########################################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[phung@archlinux beginner_tutorial]$ 
```

**Comment by bmd3k** [comment]
I suspect you have some version mismatch between google-auth and cachetools that you need to solve.

Can you upgrade your google-auth library and see if that fixes the problem? If that does not then can you please run diagnose_tensorboard.py (as suggested by the Bug Report template) and post the output?

My tensorboard 2.8.0 from several weeks ago have the following versions of these libraries:
```
$ pip show cachetools
Name: cachetools
Version: 4.2.4
<snip>
Requires: 
Required-by: google-auth
$ pip show google-auth
Name: google-auth
Version: 2.3.3
<snip>
Requires: cachetools, pyasn1-modules, rsa, setuptools, six
Required-by: google-auth-oauthlib, tensorboard
```

But installing it again today gives newer versions of these libraries:
```
$ pip show cachetools
Name: cachetools
Version: 5.0.0
<snip>
Requires: 
Required-by: google-auth
$ pip show google-auth
Name: google-auth
Version: 2.6.0
<snip>
Requires: cachetools, six, pyasn1-modules, rsa
Required-by: tensorboard, google-auth-oauthlib
```

**Comment by promach** [comment]
The problem is temporarily resolved by using the latest release of python-google-auth library at this point of time.

https://github.com/googleapis/google-auth-library-python/releases/tag/v2.6.0

**Comment by pindinagesh** [comment]
@promach 

Could you please close this issue if it's resolved. Thanks!
