### ISSUE TITLE
TensorBoard's generated pb2.py files are incompatible with protobuf 4.21.0

### ISSUE THREAD

**Issue by czxttkl** [tensorflow/tensorboard#5703]
***Edited by @nfelt for context***: The original title for this issue was `AttributeError: module 'google._upb._message' has no attribute 'Message'` because that was the original error message with protobuf 4.21.0rc1. The final release protobuf 4.21.0 has a different error message, `TypeError: Descriptors cannot not be created directly.`.

Current status:
- https://github.com/tensorflow/tensorboard/pull/5726 works around the issue by pinning protobuf to be <3.20.0 (this commit is not yet in any releases; we can consider doing a patch release depending on need)
- https://github.com/tensorflow/tensorboard/issues/5708 tracks a more permanent fix to this problem.

---

Our open source [tests](https://app.circleci.com/pipelines/github/facebookresearch/ReAgent/2388/workflows/6ca38266-8a1c-445f-b8f6-6d7d469f5a80/jobs/22868) have recently encountered the following error which comes from tensorboard (or maybe protobuf):
```
...
    from torch.utils.tensorboard import SummaryWriter
.tox/circleci_gym_gpu_unittest/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:10: in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
.tox/circleci_gym_gpu_unittest/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py:9: in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
.tox/circleci_gym_gpu_unittest/lib/python3.8/site-packages/tensorboard/compat/proto/event_pb2.py:17: in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
.tox/circleci_gym_gpu_unittest/lib/python3.8/site-packages/tensorboard/compat/proto/summary_pb2.py:17: in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
.tox/circleci_gym_gpu_unittest/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_pb2.py:16: in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
.tox/circleci_gym_gpu_unittest/lib/python3.8/site-packages/tensorboard/compat/proto/resource_handle_pb2.py:16: in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
.tox/circleci_gym_gpu_unittest/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py:36: in <module>
    _descriptor.FieldDescriptor(
.tox/circleci_gym_gpu_unittest/lib/python3.8/site-packages/google/protobuf/descriptor.py:560: in __new__
    _message.Message._CheckCalledFromGeneratedFile()
E   AttributeError: module 'google._upb._message' has no attribute 'Message'
```

Our pip install package list is as follows:
```
circleci_gym_gpu_unittest installed: absl-py==1.0.0,aiohttp==4.0.0a1,arrow==1.2.2,async-timeout==3.0.1,atari-py==0.2.9,attrs==21.4.0,box2d-py==2.3.8,cachetools==5.0.0,certifi==2021.10.8,chardet==3.0.4,charset-normalizer==2.0.12,click==8.1.3,cloudpickle==1.2.2,cmake==3.22.4,coverage==6.3.2,Cython==3.0.0a10,dill==0.3.4,diskcache==5.4.0,distro==1.7.0,docker==5.0.3,docstring-parser==0.8.1,execnet==1.9.0,filelock==3.6.0,findspark==2.0.1,fsspec==2022.3.0,future==0.18.2,gin-config==0.5.0,google-auth==2.6.6,google-auth-oauthlib==0.4.6,grpcio==1.46.1,gym==0.17.2,gym-minigrid==1.0.3,hypothesis==6.46.3,idna==3.3,importlib-metadata==4.11.3,iniconfig==1.1.1,iopath==0.1.9,Jinja2==3.1.2,joblib==1.1.0,linecache2==1.0.0,Markdown==3.3.7,MarkupSafe==2.1.1,multidict==4.7.6,mypy-extensions==0.4.3,ninja==1.10.2.3,numpy==1.22.3,oauthlib==3.2.0,opencv-python==4.5.5.64,packaging==21.3,pandas==1.4.2,parameterized==0.8.1,petastorm==0.11.4,Pillow==9.1.0,pluggy==1.0.0,portalocker==2.4.0,protobuf==4.21.0rc1,psutil==5.9.0,py==1.11.0,py4j==0.10.9,pyarrow==8.0.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pydantic==1.6.2,pyDeprecate==0.3.2,pyglet==1.5.0,pyparsing==3.0.9,pyre-extensions==0.0.27,pyspark==3.1.1,pytest==7.1.2,pytest-cov==3.0.0,pytest-forked==1.4.0,pytest-xdist==2.5.0,python-dateutil==2.8.2,pytorch-lightning @ git+https://github.com/PyTorchLightning/pytorch-lightning@9b011606f354ab6afa4135cc8bfe1339a06b3aeb,pytz==2022.1,PyYAML==6.0,pyzmq==23.0.0b2,reagent @ file:///home/circleci/project/.tox/.tmp/package/1/reagent-0.1.zip,recsim-no-tf==0.2.3,requests==2.27.1,requests-oauthlib==1.3.1,rsa==4.8,ruamel.yaml==0.17.21,ruamel.yaml.clib==0.2.6,scikit-build==0.14.1,scikit-learn==1.1.0rc1,scipy==1.8.0,six==1.16.0,sortedcontainers==2.4.0,spark-testing-base==0.10.0,tabulate==0.8.9,tensorboard==2.9.0,tensorboard-data-server==0.6.1,tensorboard-plugin-wit==1.8.1,threadpoolctl==3.1.0,tinydb==4.7.0,tomli==2.0.1,torch==1.11.0+cu113,torchmetrics==0.8.2,torchrec==0.1.0,torchx-nightly==2022.5.11,tqdm==4.64.0,traceback2==1.4.0,typing==3.7.4.3,typing-inspect==0.7.1,typing_extensions==4.2.0,unittest2==1.1.0,urllib3==1.26.9,websocket-client==1.3.2,Werkzeug==2.1.2,yarl==1.7.2,zipp==3.8.0
```

Can anyone help us investigate if this is a known bug? how do we unblock ourselves? Thanks!

**Comment by bileschi** [comment]
Can you verify whether this works with a previous version of TensorBoard?  It looks like you are using tensorboard==2.9.0.  Can you try `tensorboard==2.8.0`?

**Comment by czxttkl** [comment]
> Can you verify whether this works with a previous version of TensorBoard? It looks like you are using tensorboard==2.9.0. Can you try `tensorboard==2.8.0`?

I only verified that the issue was gone if I use tensorboard==2.9.0 and force protobuf to be 3.20.1 (by default it was 4.21.0rc1). According to https://developers.google.com/protocol-buffers/docs/news/2022-05-06, protobuf just updates from 3.20.1 to 4.21.0.

**Comment by parthea** [comment]
The issue may be resolved if you install `grpcio-tools==1.44.0`. See https://github.com/protocolbuffers/protobuf/issues/9954

**Comment by mrgeorge** [comment]
I saw the same error, and it appeared with both tensorboard 2.8.0 and 2.9.0 with protobuf 4.21.0rc1, but resolved when forcing protobuf to 3.20.1.

**Comment by czxttkl** [comment]
> The issue may be resolved if you install `grpcio-tools>=1.44.0`. See [protocolbuffers/protobuf#9954](https://github.com/protocolbuffers/protobuf/issues/9954)

This works.

**Comment by nfelt** [comment]
The more recent updates to https://github.com/protocolbuffers/protobuf/issues/9954 seem to make it pretty clear that it's not actually grpcio-tools that fixes the issue, it's probably just that installing it forced a protobuf downgrade.

The solution is probably that TensorBoard needs to either regenerate our `_pb2.py` files using protoc 3.19.0+ (unfortunately not that easy; Googlers, see b/219030239) or we need to [pin our protobuf runtime dep](https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/pip_package/requirements.txt;l=27;drc=25784fff966dcfa19a417bb5f58f385031955b91) to `<4.0.0`.

**Comment by nfelt** [comment]
I've escalated to the protobuf folks at https://github.com/protocolbuffers/protobuf/issues/9954#issuecomment-1128283911.

I also opened up a larger tracking issue for updating to 3.19.0+ in #5708.

**Comment by nfelt** [comment]
This has a workaround in #5726 that forces the protobuf dep to be <3.20.0.

https://github.com/tensorflow/tensorboard/issues/5708 tracks a longer-term fix.

**Comment by nfelt** [comment]
As of `protobuf 4.21.1` release, we're getting import errors while importing certain `tensorboard` components.

Repro:
```
conda create -n test_tensorboard python=3.7
conda activate test_tensorboard
pip install tensorboard
python
from tensorboard.backend.event_processing import plugin_event_multiplexer as event_multiplexer
```
Trace:
```
>>> from tensorboard.backend.event_processing import plugin_event_multiplexer as event_multiplexer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 24, in <module>
    from tensorboard.backend.event_processing import (
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 23, in <module>
    from tensorboard.backend.event_processing import event_file_loader
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 20, in <module>
    from tensorboard import data_compat
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/tensorboard/data_compat.py", line 20, in <module>
    from tensorboard.compat.proto import event_pb2
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "/Users/saitcakmak/opt/anaconda3/envs/test_tensorboard/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
>>> 

```

_Originally posted by @saitcakmak in https://github.com/tensorflow/tensorboard/issues/5708#issuecomment-1140312785_

**Comment by nfelt** [comment]
This should be resolved by #6147 which has been released by TensorBoard 2.12.

If you are still seeing this error, please update to TensorBoard 2.12.

**Comment by zhanwenchen** [comment]
I had to do this to solve the problem: `pip install tensorboard==2.12.0 --user`

**Comment by yerrick** [comment]
pip install -U protobuf==3.20.3
hope this helps you
