### ISSUE TITLE
tensorboard-data-server: build issues on Apple M1 (arm64)

### ISSUE THREAD

**Issue by adamjstewart** [tensorflow/tensorboard#5713]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=8, micro=9, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Darwin', nodename='ajstewart-mbp', release='21.4.0', version='Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000', machine='arm64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
WARNING: no installation among: ['tb-nightly', 'tensorboard', 'tensorflow-tensorboard']
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']

--- check: tensorboard_python_version
Traceback (most recent call last):
  File "diagnose_tensorboard.py", line 522, in main
    suggestions.extend(check())
  File "diagnose_tensorboard.py", line 75, in wrapper
    result = fn()
  File "diagnose_tensorboard.py", line 271, in tensorboard_python_version
    from tensorboard import version
ModuleNotFoundError: No module named 'tensorboard'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "diagnose_tensorboard.py", line 522, in main
    suggestions.extend(check())
  File "diagnose_tensorboard.py", line 75, in wrapper
    result = fn()
  File "diagnose_tensorboard.py", line 278, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: no data server installed

--- check: tensorboard_binary_path
INFO: which tensorboard: None

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'ajstewart-mbp.dhcp.thefacebook.com'

--- check: stat_tensorboardinfo
INFO: directory: /var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (0): []; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
pip==20.2.3
setuptools==49.2.1
six @ file:///AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-110/six-1.15.0-py2.py3-none-any.whl
wheel @ file:///AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-110/wheel-0.36.2-py2.py3-none-any.whl

``````

</details>

## Steps to reproduce (required)

I'm trying to build tensorboard-data-server from source using the [Spack](https://spack.io) package manager. The build steps basically involve:
```console
$ cd tensorboard/data/server
$ cargo build --release
$ cd pip_package
$ python build.py --out-dir=... --server-binary=...
```
It seems like `build.py` is hardcoded to use x86_64 even when on arm64? The following build log illustrates this issue, it builds for arm64 but then stuffs it into an x86_64 wheel: [spack-build-out.txt](https://github.com/tensorflow/tensorboard/files/8720997/spack-build-out.txt). Is there a better approach to build a wheel than using `pip_package/build.py`?

@glennpj

**Comment by adamjstewart** [comment]
Looks like `platform.machine()` may work most of the time, although it's a bit tricky since Apple's M1 has this Rosetta emulation mode so an x86_64 Python install will report that the system is x86_64 even if it's really arm64.

**Comment by adamjstewart** [comment]
Alright, for anyone who encounters this issue, the following patch allows me to build successfully on Apple M1 and macOS 12.3.1:
```patch
diff --git a/tensorboard/data/server/pip_package/build.py b/tensorboard/data/server/pip_package/build.py
index b93b06eb5..3489ce464 100644
--- a/tensorboard/data/server/pip_package/build.py
+++ b/tensorboard/data/server/pip_package/build.py
@@ -78,13 +78,13 @@ def main():
         platform_name = {
             # using platform tag values from TensorFlow releases
             "Linux": "manylinux2010",
-            "Darwin": "macosx_10_9",
+            "Darwin": "macosx_12_0",
         }.get(platform.system())
         if platform_name is None:
             raise RuntimeError(
                 "Unsupported platform: %r" % (platform.system(),)
             )
-        cpu_name = "x86_64"
+        cpu_name = "arm64"
         platform_tag = "%s_%s" % (platform_name, cpu_name)
 
     os.chdir(tmpdir)
```
So not only do you need to change the `cpu_name`, you also need to change the `platform_name`. It shouldn't be too hard to automatically detect these.

**Comment by japie1235813** [comment]
I'm glad you're able to make this works on M1. Thanks for contributing back. I will take a look on that PR.
