### ISSUE TITLE
write event file error

### ISSUE THREAD

**Issue by ninisy** [tensorflow/tensorboard#5759]
https://github.com/tensorflow/tensorboard/blob/b044c729e131097fc133c06d453a712f45f90b1d/tensorboard/compat/tensorflow_stub/io/gfile.py#L166

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 766, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 160, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 166, in _write
    f.write(compatify(file_content))
FileNotFoundError: [Errno 2] No such file or directory

**Comment by ericdnielsen** [comment]
I'm going to need more information about what you were trying to do when you got the stack trace.
