### ISSUE TITLE
got error “ValueError: Duplicate plugins for name projector” after "tensorboard --logdir dir" in ubuntu

### ISSUE THREAD

**Issue by DryPilgrim** [tensorflow/tensorboard#5815]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='workspace-job-62d7b280017cb420aac7790c-9d2hx', release='5.4.5-050405-generic', version='#201912181630 SMP Wed Dec 18 16:33:40 UTC 2019', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.9.1
INFO: installed: tensorflow==2.9.1
INFO: installed: tensorflow-estimator==2.9.0
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.9.1'

--- check: tensorflow_python_version
2022-07-21 03:24:07.606360: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
INFO: tensorflow.__version__: '2.9.1'
INFO: tensorflow.__git_version__: 'v2.9.0-18-gd8ce9f9c301'

--- check: tensorboard_data_server_version
INFO: data server binary: '/opt/conda/lib/python3.8/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/opt/conda/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'workspace-job-62d7b280017cb420aac7790c-9d2hx'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=39848715, st_dev=1048613, st_nlink=2, st_uid=0, st_gid=0, st_size=4096, st_atime=1658370922, st_mtime=1658370876, st_ctime=1658370876)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/opt/conda/lib/python3.8/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==1.2.0
addict==2.4.0
alabaster==0.7.12
anyio==3.5.0
apex==0.1
appdirs==1.4.4
argon2-cffi==20.1.0
ascii-graph==1.5.1
astunparse==1.6.3
async-generator==1.10
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
audioread==2.1.9
Babel==2.9.0
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
bagpy==0.4.8
beautifulsoup4 @ file:///home/linux1/recipes/ci/beautifulsoup4_1610988766420/work
bitstring==3.1.9
bleach==3.3.0
blis @ file:///tmp/build/80754af9/cython-blis_1613319335612/work
boto3==1.17.32
botocore==1.20.32
brotlipy==0.7.0
cachetools==5.2.0
catalogue==1.0.0
catkin-pkg==0.4.24
catkin-tools==0.8.2
certifi==2022.6.15
cffi @ file:///tmp/build/80754af9/cffi_1605538068321/work
chardet @ file:///tmp/build/80754af9/chardet_1605303185383/work
click==7.1.2
codecov==2.1.11
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
commonmark==0.9.1
conda==4.13.0
conda-build==3.21.4
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1603018141399/work
coolname==1.1.0
coverage==5.5
cryptography @ file:///tmp/build/80754af9/cryptography_1605544487601/work
cxxfilt==0.2.2
cycler==0.10.0
cymem @ file:///tmp/build/80754af9/cymem_1613319259039/work
Cython==0.28.4
DataProperty==0.50.0
decorator @ file:///home/ktietz/src/ci/decorator_1611930055503/work
defusedxml==0.7.1
deprecation==2.1.0
distro==1.6.0
DLLogger @ git+git://github.com/NVIDIA/dllogger.git@26a0f8f1958de2c0c460925ff6102a4d2486d6cc
docutils==0.16
dominate==2.6.0
easydict==1.9
entrypoints==0.3
filelock @ file:///home/linux1/recipes/ci/filelock_1610993975404/work
flake8==3.7.9
Flask==1.1.2
flatbuffers==1.12
freetype-py==2.2.0
future==0.18.2
gast==0.3.3
ghp-import==2.0.2
glfw==2.5.0
glob2 @ file:///home/linux1/recipes/ci/glob2_1610991677669/work
gnupg==2.3.1
google-auth==2.9.1
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
graphsurgeon @ file:///workspace/TensorRT-7.2.2.3/graphsurgeon/graphsurgeon-0.4.5-py2.py3-none-any.whl
grpcio==1.32.0
h5py==2.10.0
hsluv==5.0.2
html2text==2020.1.16
hypothesis==4.50.8
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
imageio==2.9.0
imagesize==1.2.0
imgui==1.4.1
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1615900442896/work
inflect==5.3.0
iniconfig==1.1.1
ipdb==0.13.7
ipykernel==5.5.0
ipython @ file:///tmp/build/80754af9/ipython_1614615245721/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets==7.6.5
itsdangerous==1.1.0
jedi==0.17.0
Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work
jmespath==0.10.0
joblib==1.0.1
json5==0.9.5
jsonschema @ file:///tmp/build/80754af9/jsonschema_1594303806266/work
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyter-packaging==0.11.1
jupyter-server==1.13.5
jupyter-tensorboard @ git+https://github.com/cliffwoolley/jupyter_tensorboard.git@ffa7e26138b82549453306e06b535a9ac36db17a
jupyterlab==3.2.9
jupyterlab-pygments==0.1.2
jupyterlab-server==2.10.3
jupyterlab-widgets==1.0.2
jupytext==1.11.0
keras==2.9.0
Keras-Preprocessing==1.1.2
kitti360Scripts @ git+https://github.com/autonomousvision/kitti360Scripts.git@8d19781c4b08b9591d67f355984af77ab1c3476e
kiwisolver==1.3.1
knn==0.0.0
laspy @ file:///home/conda/feedstock_root/build_artifacts/laspy_1642971551113/work
libarchive-c @ file:///home/linux1/recipes/ci/python-libarchive-c_1610974153025/work
libclang==14.0.1
librosa==0.8.0
llvmlite==0.35.0
lmdb==1.1.1
m2r2==0.3.2
Mako==1.1.4
Markdown==3.3.4
markdown-it-py==0.6.2
MarkupSafe==1.1.1
maskrcnn-benchmark @ file:///opt/pytorch/examples/maskrcnn/pytorch
matplotlib==3.3.4
mbstrdecoder==1.0.1
mccabe==0.6.1
mdit-py-plugins==0.2.6
mergedeep==1.3.4
mistune==0.8.4
mkdocs==1.2.3
mlperf-compliance==0.0.10
mock @ file:///tmp/build/80754af9/mock_1607622725907/work
msgfy==0.1.0
munch==2.5.0
murmurhash @ file:///tmp/build/80754af9/murmurhash_1607456108764/work
nbclassic==0.3.5
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
networkx==2.0
ninja==1.10.2.3
nltk==3.5
nose==1.3.7
notebook==6.2.0
numba @ file:///tmp/build/80754af9/numba_1614888130619/work
numpy==1.23.1
nvidia-dali-cuda110==0.31.0
nvidia-dlprof-pytorch-nvtx @ file:///nvidia/opt/dlprof/bin/nvidia_dlprof_pytorch_nvtx-1.0.0-py3-none-any.whl
nvidia-pyprof @ git+https://github.com/NVIDIA/PyProf@5e3756a779aee4b673adbc614b3a0ac96dc94485
nvidia-tensorboard @ file:///nvidia/opt/tensorboard_install/nvidia_tensorboard-1.15.0%2Bnv21.03-py3-none-any.whl
nvidia-tensorboard-plugin-dlprof @ file:///nvidia/opt/tensorboard_install/nvidia_tensorboard_plugin_dlprof-0.12-py3-none-any.whl
oauthlib==3.2.0
onnx @ file:///opt/pytorch/pytorch/third_party/onnx
onnxruntime==1.7.0
open3d==0.13.0
opencv-python==4.5.5.62
opt-einsum==3.3.0
osrf-pycommon==2.0.0
packaging==20.9
pandas==1.1.4
pandocfilters==1.4.3
parso @ file:///tmp/build/80754af9/parso_1607623074025/work
pathlib==1.0.1
pathvalidate==2.3.2
pclpy==0.12.0
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
piexif==1.1.3
Pillow==9.0.1
Pillow-SIMD @ file:///tmp/pillow-simd
pip==20.2.4
pkginfo==1.7.0
plac @ file:///tmp/build/80754af9/plac_1594259967336/work
pluggy==0.13.1
polygraphy==0.25.1
pooch==1.3.0
preshed==3.0.2
pretrainedmodels==0.7.4
prettytable==2.1.0
progressbar==2.5
prometheus-client==0.9.0
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
protobuf==3.15.6
psutil @ file:///tmp/build/80754af9/psutil_1612298023621/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
py==1.10.0
py3rosmsgs==1.18.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybind11==2.6.2
pycocotools @ git+https://github.com/nvidia/cocoapi.git@6ac4a93058202603f36fd1ce47228e7d81119e5a#subdirectory=PythonAPI
pycodestyle==2.5.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycryptodomex==3.14.1
pycuda==2020.1
pydash==5.1.0
pydot==1.4.2
pyflakes==2.1.1
Pygments @ file:///tmp/build/80754af9/pygments_1615143339740/work
pymdown-extensions==9.2
pynvml==8.0.4
PyOpenGL==3.1.5
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1605545627475/work
pyparsing==2.4.7
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
pyrsistent @ file:///tmp/build/80754af9/pyrsistent_1600141720057/work
pyserial==3.5
PySocks @ file:///tmp/build/80754af9/pysocks_1605305779399/work
pytablewriter==0.47.0
pytest==6.2.2
pytest-cov==2.11.1
pytest-pythonpath==0.7.3
python-dateutil==2.8.1
Python-Deprecated==1.1.0
python-hostlist==1.21
python-nvd3==0.15.0
python-slugify==4.0.1
pytools==2021.2
pytorch-ignite==0.4.8
pytorch-quantization==2.1.0
pytorch-transformers==1.1.0
pytz @ file:///tmp/build/80754af9/pytz_1612215392582/work
PyWavelets==1.1.1
PyYAML==5.4.1
pyyaml-env-tag==0.1
pyzmq==22.0.3
qtconsole==5.2.2
QtPy==2.0.1
recommonmark==0.7.1
regex==2021.3.17
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
requests-oauthlib==1.3.1
resampy==0.2.2
resnest==0.0.5
revtok @ git+git://github.com/jekbradbury/revtok.git@f1998b72a941d1e5f9578a66dc1c20b01913caab
rfconv==0.0.2b20210406
rinoh-typeface-dejavuserif==0.1.3
rinoh-typeface-texgyrecursor==0.1.1
rinoh-typeface-texgyreheros==0.1.1
rinoh-typeface-texgyrepagella==0.1.1
rinohtype==0.5.3
rosdep==0.21.0
rosdistro==0.8.3
rosinstall==0.7.8
rosinstall-generator==0.1.22
rospkg==1.3.0
rsa==4.9
ruamel-yaml==0.15.87
runx==0.0.6
s3transfer==0.3.6
sacrebleu==1.2.10
sacremoses==0.0.35
scikit-build==0.13.1
scikit-image==0.15.0
scikit-learn==0.24.1
scipy @ file:///tmp/build/80754af9/scipy_1614021897168/work
seaborn==0.11.2
Send2Trash==1.5.0
sentencepiece==0.1.95
setuptools==50.3.1.post20201107
six @ file:///tmp/build/80754af9/six_1605205327372/work
sklearn==0.0
sniffio==1.2.0
snowballstemmer==2.1.0
SoundFile==0.10.3.post1
soupsieve @ file:///tmp/build/80754af9/soupsieve_1614023247537/work
sox==1.4.1
spacy @ file:///tmp/build/80754af9/spacy_1608321098157/work
Sphinx==3.2.1
sphinx-autodoc-typehints==1.4.0
sphinx-bootstrap-theme==0.8.1
sphinx-glpi-theme==0.3
sphinx-markdown-parser==0.2.4
sphinx-rtd-theme==0.5.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
srsly @ file:///tmp/build/80754af9/srsly_1607548537638/work
subword-nmt @ git+git://github.com/rsennrich/subword-nmt.git@48ba99e657591c329e0003f0c6e32e493fa959ef
tabledata==1.1.3
tabulate==0.8.9
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.4.1
tensorflow==2.9.1
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.26.0
tensorrt @ file:///workspace/TensorRT-7.2.2.3/python/tensorrt-7.2.2.3-cp38-none-linux_x86_64.whl
termcolor==1.1.0
terminado==0.9.3
testpath==0.4.4
text-unidecode==1.3
thinc @ file:///tmp/build/80754af9/thinc_1607710152385/work
threadpoolctl==2.1.0
timm==0.5.4
toml==0.10.2
tomlkit==0.9.2
torch @ file:///opt/pytorch/pytorch
torchcontrib==0.0.2
torchsparse @ git+https://github.com/mit-han-lab/torchsparse.git@74099d10a51c71c14318bce63d6421f698b24f24
torchtext @ file:///opt/pytorch/text
torchvision @ file:///opt/pytorch/vision
tornado==6.1
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1649051611147/work
traitlets @ file:///home/ktietz/src/ci/traitlets_1611929699868/work
typepy==1.1.4
typing-extensions==3.7.4.3
uff @ file:///workspace/TensorRT-7.2.2.3/uff/uff-0.6.9-py2.py3-none-any.whl
Unidecode==1.2.0
unify==0.5
untokenize==0.1.1
urllib3 @ file:///tmp/build/80754af9/urllib3_1603305693037/work
vcstools==0.1.42
vispy==0.9.6
wasabi @ file:///tmp/build/80754af9/wasabi_1612219178408/work
watchdog==2.1.6
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
websocket-client==1.2.3
Werkzeug==1.0.1
wheel==0.37.1
widgetsnbextension==3.5.2
wrapt==1.12.1
wstool==0.1.17
yacs==0.1.8
yapf==0.32.0
ytsphinx==1.2.1.dev20200430
zipp @ file:///tmp/build/80754af9/zipp_1615904174917/work

``````

</details>

###    Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

## Issue description
run "tensorboard --logdir log/log_SM3D/"

2022-07-21 03:32:17.518207: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

Traceback (most recent call last):
  File "/opt/conda/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/program.py", line 276, in main
    return runner(self.flags) or 0
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/program.py", line 292, in _run_serve_subcommand
    server = self._make_server()
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/program.py", line 467, in _make_server
    app = application.TensorBoardWSGIApp(
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/backend/application.py", line 139, in TensorBoardWSGIApp
    return TensorBoardWSGI(
  File "/opt/conda/lib/python3.8/site-packages/tensorboard/backend/application.py", line 252, in __init__
    raise ValueError(
ValueError: Duplicate plugins for name projector

**Comment by bileschi** [comment]
It sounds like the system is confused because it found projector twice in the environment.  Can you try executing tensorboard within a virtual environment to see if the problem may be with your global python environment?

```
$ deactivate # (not necessary if you are not already in a virtual env)
...

$ python3 -m venv 'my_temp_venv'
...

$ source my_temp_venv/bin/activate
...

$ pip install tensorboard
...

$ which tensorboard
/Users/bileschi/proj/tensorboard/my_temp_venv/bin/tensorboard

$ tensorboard --version
TensorFlow installation not found - running with reduced feature set.
2.9.1

$ tensorboard --logdir ~/tensorboard-logdirs/scalars_demo/
```

**Comment by bmd3k** [comment]
Thanks @DryPilgrim for the report. I agree with Stan that this sounds like an environment problem. I notice you have tensorboard, tensorboardX, nvidia_tensorboard, and jupyter_tensorboard. Is it possible one of those has the conflicting plugin?

Similary: In https://github.com/tensorflow/tensorboard/issues/3443#issuecomment-606077549 we mention that sometimes installing a new tensorboard over an existing tensorboard will create this duplicate plugin scenario. Can you try `pip uninstall tensorboard && pip install tensorboard` to see if it will resolve your issue?
