### ISSUE TITLE
ImportError _sqlite3 running virtualenv tensorboard

### ISSUE THREAD

**Issue by roballsopp** [tensorflow/tensorboard#584]
I followed the instructions [here](https://www.tensorflow.org/install/install_mac#installing_with_virtualenv) to install tensorflow. Tensorflow seems to work fine, at least it seems I can train my model with no problems. However, when I attempt to run tensorboard to view the summaries I saved, I get the following error:
`ImportError: No module named _sqlite3`. The full trace is:

```
Traceback (most recent call last):
  File "/Users/rallsopp/tensorflow/bin/tensorboard", line 7, in <module>
    from tensorboard.main import main
  File "/Users/rallsopp/tensorflow/lib/python2.7/site-packages/tensorboard/main.py", line 33, in <module>
    from tensorboard.backend import application
  File "/Users/rallsopp/tensorflow/lib/python2.7/site-packages/tensorboard/backend/application.py", line 29, in <module>
    import sqlite3
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
```

I'm kinda new to python and not familiar with virtualenv. There is very little on this error when I've searched, but it seems like most folks run into this if they improperly build python from source, but I'm not doing that am I?

**Comment by roballsopp** [comment]
i think my global python install was bad. I solved this by deleting my virtualenv, uninstalling my global python installation, reinstall global python with brew, and recreating my virtualenv. Sorry for the frivolous issue. Hopefully this saves somebody an hour or two.
