### ISSUE TITLE
Error in visualization MASK R-CNN

### ISSUE THREAD

**Issue by 1358467720** [tensorflow/tensorboard#5961]
When I study  target detection in this website https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html#, I would like to know what's it like in the framework of the network visualization, I will use the following code 

```python
    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

    # our dataset has two classes only - background and person
    num_classes = 2
    # use our dataset and defined transformations
    dataset = PennFudanDataset('PennFudanPed', get_transform(train=True))
    dataset_test = PennFudanDataset('PennFudanPed', get_transform(train=False))

    # split the dataset in train and test set
    indices = torch.randperm(len(dataset)).tolist()
    dataset = torch.utils.data.Subset(dataset, indices[:-50])
    dataset_test = torch.utils.data.Subset(dataset_test, indices[-50:])

    # define training and validation data loaders
    data_loader = torch.utils.data.DataLoader(
        dataset, batch_size=2, shuffle=True, num_workers=4,
        collate_fn=utils.collate_fn)

    data_loader_test = torch.utils.data.DataLoader(
        dataset_test, batch_size=1, shuffle=False, num_workers=4,
        collate_fn=utils.collate_fn)

    # get the model using our helper function
    model = get_model_instance_segmentation(num_classes)

    # move model to the right device
    model.to(device)

    # grab a single mini-batch of images
    images, labels = next(iter(data_loader))
    # images = images[0]
    # images = torch.reshape(images, ((1, images.shape[0], images.shape[1], images.shape[2])))
    images = list(image for image in images)

    # 使用tensorboard可视化model
    writer = SummaryWriter('runs/people-pretrain-mask-r-cnn')
    # add_graph() will trace the sample input through your model,
    # and render it as a graph.
    model.eval()
    writer.add_graph(model, images)
    writer.flush()
```
Then I encountered an error:
```
C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=MaskRCNN_ResNet50_FPN_Weights.COCO_V1`. You can also use `weights=MaskRCNN_ResNet50_FPN_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torch\onnx\utils.py", line 87, in select_model_mode_for_export
    yield
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torch\utils\tensorboard\_pytorch_graph.py", line 338, in graph
    trace = torch.jit.trace(model, args, strict=use_strict_trace)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torch\jit\_trace.py", line 750, in trace
    return trace_module(
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torch\jit\_trace.py", line 967, in trace_module
    module._c._create_method_from_trace(
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torchvision\models\detection\generalized_rcnn.py", line 83, in forward
    images, targets = self.transform(images, targets)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\torchvision\models\detection\transform.py", line 119, in forward
    for k, v in t.items():
AttributeError: 'Tensor' object has no attribute 'items'

Process finished with exit code 1

```
Can someone help me?! Really Thank !

**Comment by bmd3k** [comment]
Hi @1358467720 . Unfortunately we didn't build or maintain the pytorch library. Perhaps you would have some luck reaching out to the pytorch community for help?
