### ISSUE TITLE
Scalar graphs in unseen paginated-views not updated on run (de)selection

### ISSUE THREAD

**Issue by sbrodehl** [tensorflow/tensorboard#6102]
To report a problem with TensorBoard itself, please fill out the
remainder of this template.

## Environment information (required)

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 516a2f9433ba4f9c3a4fdb0f89735870eda054a1

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=10, micro=8, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='', release='6.0.10-arch2-1', version='#1 SMP PREEMPT_DYNAMIC Sat, 26 Nov 2022 16:51:18 +0000', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/XXX/.venv/ABC'

--- check: installed_packages
INFO: installed: tensorboard==2.10.1
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.10.1'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "/XXX/diagnose_tensorboard.py", line 528, in main
    suggestions.extend(check())
  File "/XXX/diagnose_tensorboard.py", line 81, in wrapper
    result = fn()
  File "/XXX/diagnose_tensorboard.py", line 284, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: data server binary: '/XXX/.venv/ABC/lib/python3.10/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/XXX/.venv/ABC/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'localhost'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=62, st_dev=34, st_nlink=2, st_uid=1000, st_gid=1000, st_size=60, st_atime=1669839096, st_mtime=1670776214, st_ctime=1670776214)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/XXX/.venv/ABC/lib/python3.10/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==1.3.0
appdirs==1.4.4
asciitree==0.3.3
astroid==2.12.12
attrs==22.1.0
cachetools==5.2.0
certifi==2022.9.24
cftime==1.6.2
charset-normalizer==2.1.1
click==8.1.3
cloudpickle==2.2.0
colored==1.4.3
configobj==5.0.6
contourpy==1.0.6
cycler==0.11.0
Cython==0.29.32
dill==0.3.6
donfig==0.7.0
entrypoints==0.4
et-xmlfile==1.1.0
exceptiongroup==1.0.1
fasteners==0.18
flake8==5.0.4
fonttools==4.38.0
gitdb==4.0.9
GitPython==3.1.29
google-auth==2.14.1
google-auth-oauthlib==0.4.6
grpcio==1.50.0
idna==3.4
imageio==2.22.4
iniconfig==1.1.1
isort==5.10.1
jplephem==2.18
kiwisolver==1.4.4
lazy-object-proxy==1.8.0
locket==1.0.0
lz4==4.0.2
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.2
mccabe==0.7.0
numcodecs==0.10.2
numpy==1.23.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.2
openpyxl==3.0.10
packaging==21.3
pandas==1.5.1
partd==1.3.0
pip==22.3.1
platformdirs==2.5.3
pluggy==1.0.0
pooch==1.6.0
protobuf==3.19.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.9.1
pyflakes==2.5.0
pylint==2.15.5
pyparsing==3.0.9
pytest==7.2.0
python-dateutil==2.8.2
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
setuptools==60.2.0
sgp4==2.21
six==1.16.0
smmap==5.0.0
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tomli==2.0.1
tomlkit==0.11.6
toolz==0.12.0
torch==1.13.0
torchvision==0.14.0
tqdm==4.64.1
typing_extensions==4.4.0
urllib3==1.26.12
Werkzeug==2.2.2
wheel==0.37.1
wrapt==1.14.1
xarray==2022.11.0
zarr==2.13.3

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

For browser-related issues, please additionally specify:

  - Browser type and version (e.g., Chrome 64.0.3282.140):
  - Screenshot, if it’s a visual issue:

## Issue description

When selecting (or deselection) runs from the list on the left hand side, graphs of scalars on non-visible paginated-views are not updated with the new (or removed) data.
Only the current view is updated correctly. If one (de)selects an additional run and switched to another page, the graphs show outdated information (either new run is missing, or deselected run is still seen).

**Comment by qihach64** [comment]
[cast (1).webm](https://user-images.githubusercontent.com/88216042/208785388-998cc212-8f60-4927-9cf3-8823157e75c0.webm)

Hi @sbrodehl, thanks for reporting the issue! I tried to reproduce the issue based on your description but it seems to work just fine for me (See the screenshot above). Am I missing something or were you looking at the wrong runs?

It would be nice if you can share some screenshot or me. Thx!

**Comment by sbrodehl** [comment]
Thanks for getting back to me, and sorry for the somewhat "simple" bug description.

The bug exists only if multiple runs are initially selected, and one or more are added or removed (with at least one remaining) and when switching between different "pages".

I have added a screencast of the bug below.

https://user-images.githubusercontent.com/7113492/208891046-23890846-34f8-4e5c-86ad-fc937199c247.mp4

Here, first switch between pages shows all three selected runs are shown.
After removing the red run, the data is still shown in other pages, which were not shown during the deselection event.

I hope this better shows when the bug appears and you are able to reproduce this.
Let me know if you have more / other questions!

**Comment by qihach64** [comment]
Thanks for the detailed instructions for reproducing the issue and the screenshot! 

I've added it to our bug-fix list and will leave this issue open until we fix it.
