### ISSUE TITLE
Internal error. Please report this and specify reference code 05f2965d-579f-4cc2-bdfd-8e1879ca2cd2.

### ISSUE THREAD

**Issue by lukaspfeifenberger** [tensorflow/tensorboard#6104]
tensorboard --version_tb
TensorFlow installation not found - running with reduced feature set.
2.11.0

tensorboard dev upload --logdir=.
TensorFlow installation not found - running with reduced feature set.
Traceback (most recent call last):
  File "/opt/conda/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/program.py", line 276, in main
    return runner(self.flags) or 0
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/uploader/uploader_subcommand.py", line 692, in run
    return _run(flags, self._experiment_url_callback)
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/uploader/uploader_subcommand.py", line 125, in _run
    intent.execute(server_info, channel)
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/uploader/uploader_subcommand.py", line 462, in execute
    experiment_id = uploader.create_experiment()
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/uploader/uploader.py", line 180, in create_experiment
    self._api.CreateExperiment, request
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/util/grpc_util.py", line 235, in call_with_retries
    metadata=version_metadata(),
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Internal error. Please report this and specify reference code 05f2965d-579f-4cc2-bdfd-8e1879ca2cd2."
	debug_error_string = "{"created":"@1670968780.018092049","description":"Error received from peer ipv4:34.95.66.171:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Internal error. Please report this and specify reference code 05f2965d-579f-4cc2-bdfd-8e1879ca2cd2.","grpc_status":13}"

**Comment by lukaspfeifenberger** [comment]
This bug seems to be server related: I removed my auth, and logged into a different google-account and it works. How do I remove the server-side tensorboard information?

**Comment by lukaspfeifenberger** [comment]
Okay so I played around with "tensorboard dev delete", and it turns out you have a quota of how many experiments you can upload. After that, this quite unhelpful error appears.

**Comment by bileschi** [comment]
Hrm - yes this error is particularly unhelpful.  Thanks for raising attention!  In the meantime are you able to delete some experiments as a workaround?
