### ISSUE TITLE
Loading data on HDFS with reduced feature set (w/o TensorFlow installation)

### ISSUE THREAD

**Issue by nyamashi** [tensorflow/tensorboard#6165]
When loading TensorBoard data on HDFS without TensorFlow installation, I got the following error log (note: I modified HDFS data paths in the log) and could not load the data.  Recently dependent module `fsspec` has updated (`fsspec==2023.1.0`) and supported seeking API 
- https://filesystem-spec.readthedocs.io/en/latest/changelog.html#id1.
- https://github.com/fsspec/filesystem_spec/pull/1154 

In response, I modified `tensorboard/compat/tensorflow_stub/io/gfile.py` as like 
https://github.com/nyamashi/tensorboard/commit/ea9f6e6dd3c36b19d51563f2ab2f0ef7f87e3d40.
Then it looks working. 

Is it possible to enhance the dependency (`fsspec >= 2023.1.0`) and add this modification in `tensorboard/compat/tensorflow_stub/io/gfile.py`?

Error message before the modification:
```
$ tensorboard --inspec --logdir {sample hdfs path}
TensorFlow installation not found - running with reduced feature set.
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Traceback (most recent call last):
  File "/opt/myenv/python38/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/opt/myenv/python38/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/myenv/python38/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/program.py", line 276, in main
    return runner(self.flags) or 0
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/program.py", line 289, in _run_serve_subcommand
    efi.inspect(flags.logdir, event_file, flags.tag)
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/backend/event_processing/event_file_inspector.py", line 430, in inspect
    inspection_units = get_inspection_units(logdir, event_file, tag)
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/backend/event_processing/event_file_inspector.py", line 384, in get_inspection_units
    field_to_obs=get_field_to_observations_map(generator, tag),
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/backend/event_processing/event_file_inspector.py", line 191, in get_field_to_observations_map
    for event in generator:
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 244, in Load
    for record in super(LegacyEventFileLoader, self).Load():
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 178, in Load
    yield next(self._iterator)
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 109, in __next__
    self._reader.GetNext()
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 207, in GetNext
    header_str = self._read(8)
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 273, in _read
    new_data = self.file_handle.read(n)
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 728, in read
    (self.buff, self.continuation_token) = self.fs.read(
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 447, in func_wrapper
    return func(self, *args, **kwargs)
  File "/opt/myenv/python38/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 526, in read
    raise errors.InvalidArgumentError(
tensorboard.compat.tensorflow_stub.errors.InvalidArgumentError: b'{sample 
 hdfs path}/events.out.tfevents.xxxxx' is not seekable
```

With `fsspec == 2023.1.0` and https://github.com/nyamashi/tensorboard/commit/ea9f6e6dd3c36b19d51563f2ab2f0ef7f87e3d40. Looks working:
```
$ tensorboard --inspec --logdir  {sample hdfs path}
TensorFlow installation not found - running with reduced feature set.
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
 {sample hdfs path}

These tags are in  {sample hdfs path}
audio -
histograms -
images -
scalars
   .....
tensor
   ....
======================================================================

Event statistics for  {sample hdfs path}
audio -
graph -
histograms -
images -
scalars
   ....
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor
   ....
======================================================================
```

**Comment by japie1235813** [comment]
Thanks for firing the issue. You're welcomed to file a PR with the patch to support seekable option of fsspec.
For now fsspec is used optionally if it's installed ([code](https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/compat/tensorflow_stub/io/gfile.py;l=39-44?q=tensorboard%2Fcompat%2Ftensorflow_stub%2Fio%2Fgfile.py&ss=tensorflow%2Ftensorboard))

However, before we accepct that PR (same or similar to @nyamashi ea9f6e6). We need to consider (and that's what you need to prove in that PR) the new option in _all cases_, including
1. It's not affect other non-HDFS file reading (e.g. passing this option but with non-HDFS file reading)
2. TB is not broken with lower version of fsspec (those versions without the seekable option fsspec)

The table illustrates the cases: 
| fsspec verion.       | HDFS |  non-HDFS
| ----------- | ----------- |----------- |
| v2023- (0.7.4 for example)     |  (A)      | (C)
| v2023+     | (B)       | (D)

from the table above, 
1. I'm not sure your error message means (A) or (B). I think that (B) is broken and it is what you need
2. (A) is out of discussion since HDFS was not properly seekable until recent fsspec change. To do things in a nicer way we can have prompt of upgrading fsspec version
3. Then, We need to make sure (C)&(D) works both _with and without_ the seekable option

A side note: we don' have fsspec version limitation. (We do have it in our tests but that depends on whether we have this covered). You should be able to use `2023.1.0` version if you have that version installed.
 
If one of (C) and (D) is broken with that patch, then we need to consider adding fsspec constraint.

**Comment by nyamashi** [comment]
@japie1235813  
Thank you for the response and detailed comments!

According to your instructions I've checked the cases in the above table:

Settings:
  - TenserBoard: 2.11.2 
  - code modification: https://github.com/tensorflow/tensorboard/commit/ea9f6e6dd3c36b19d51563f2ab2f0ef7f87e3d40
  -  running with reduced feature set (w/o TensorFlow)
  - fsspec:
    - v2023-:  0.7.4
    - v2023+:  2023.1.0
  - non-HDFS
    - local directory  like  `--logdir file:///foo/bar/tb_data` to call `FSSpecFileSystem`.

Results:
| fsspec version    |  HDFS | non-HDFS   |
| :---        |    :----:   |          ---: |
|v2023-:0.7.4 |(A):❌|(C):✅ |
|v2023+:2023.1.0|(B):✅ |(D):✅ |

Is this enough to move on to PR?
