### ISSUE TITLE
Keras graph not shown when multiple outputs of a same node are feed to another one.

### ISSUE THREAD

**Issue by nhuet** [tensorflow/tensorboard#6216]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 516a2f9433ba4f9c3a4fdb0f89735870eda054a1

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='noputer', release='5.10.0-17-amd64', version='#1 SMP Debian 5.10.136-1 (2022-08-13)', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/home/nolwen/Projects/decomon/deco_39_venv'

--- check: installed_packages
INFO: installed: tensorboard==2.11.2
INFO: installed: tensorflow==2.11.0
INFO: installed: tensorflow-estimator==2.11.0
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.11.2'

--- check: tensorflow_python_version
2023-03-03 16:19:03.841537: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-03 16:19:03.925941: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-03 16:19:03.925961: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-03 16:19:04.550426: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-03 16:19:04.550482: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-03-03 16:19:04.550490: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
INFO: tensorflow.__version__: '2.11.0'
INFO: tensorflow.__git_version__: 'v2.11.0-rc2-17-gd5b57ca93e5'

--- check: tensorboard_data_server_version
INFO: data server binary: '/home/nolwen/Projects/decomon/deco_39_venv/lib/python3.9/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/nolwen/Projects/decomon/deco_39_venv/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'noputer'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=1049406, st_dev=65024, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1677838022, st_mtime=1677839070, st_ctime=1677839070)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/nolwen/Projects/decomon/deco_39_venv/lib/python3.9/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==1.4.0
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
astunparse==1.6.3
attrs==22.2.0
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.0.1
comm==0.1.2
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.6
-e git+https://github.com/nhuet/decomon.git@2a53a93b423d68ca6ffcd0781c5933bebfe9c6c4#egg=decomon
decorator==5.1.1
defusedxml==0.7.1
executing==1.2.0
fastjsonschema==2.16.2
flatbuffers==23.1.21
fonttools==4.38.0
fqdn==1.5.1
gast==0.4.0
google-auth==2.16.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.51.1
h5py==3.8.0
idna==3.4
importlib-metadata==6.0.0
ipykernel==6.21.1
ipython==8.10.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.5.0
jupyter-events==0.6.3
jupyter_client==8.0.2
jupyter_core==5.2.0
jupyter_server==2.2.1
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
kaggle==1.5.12
keras==2.11.0
kiwisolver==1.4.4
libclang==15.0.6.1
Markdown==3.4.1
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.6
mistune==2.0.5
nbclassic==0.5.1
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.24.2
oauthlib==3.2.2
opt-einsum==3.3.0
packaging==23.0
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.4.0
pip==23.0
platformdirs==3.0.0
prometheus-client==0.16.0
prompt-toolkit==3.0.36
protobuf==3.19.6
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydot==1.4.2
Pygments==2.14.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.4
python-slugify==8.0.0
pytz==2022.7.1
PyYAML==6.0
pyzmq==25.0.0
qtconsole==5.4.0
QtPy==2.3.0
requests==2.28.2
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rsa==4.9
Send2Trash==1.8.0
setuptools==58.1.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.2
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.11.0
tensorflow-estimator==2.11.0
tensorflow-io-gcs-filesystem==0.30.0
termcolor==2.2.0
terminado==0.17.1
text-unidecode==1.3
tinycss2==1.2.1
tornado==6.2
tqdm==4.64.1
traitlets==5.9.0
typing_extensions==4.4.0
uri-template==1.2.0
urllib3==1.26.14
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==2.2.2
wheel==0.38.4
widgetsnbextension==4.0.5
wrapt==1.14.1
zipp==3.13.0

``````

</details>

## Issue description

When using tensorboard to vizualize the keras graph of a keras model involving a node whose inputs include outputs of a single node, tensorboard fails to import and show the graph. The error comes actually from the function `tensorboard.plugins.graph.keras_util.keras_model_to_graph_def()` used to import the graph.

Here is a standalone simple example reproducing the bug without having to open tensorboard.

```python
import json


import numpy as np
import tensorflow as tf
from tensorboard.plugins.graph.keras_util import keras_model_to_graph_def


class DoublingLayer(tf.keras.layers.Layer):
    """Layer doubling artificially the inputs."""

    def call(self, inputs):
        return inputs, inputs


# Model definition
input = tf.keras.Input(shape=(2,))
dbling_layer = DoublingLayer()
reducing_layer = tf.keras.layers.Add()
outputs = reducing_layer(dbling_layer(input))
model = tf.keras.Model(inputs=[input], outputs=outputs)

# Show the config
model_config_json = model.to_json(indent=2)
print("\n** json model config:\n")
print(model_config_json)

# Computation example with original model
print("** Computation with original model:")
print(model(np.array([1, 2])))

# Import the keras model from the json + computation  => valid json config
model2 = tf.keras.models.model_from_json(model_config_json, custom_objects={"DoublingLayer": DoublingLayer})
print("\n** Computation with model loaded from json:")
print(model(np.array([1, 2])))

# Try to import it with tensorboard graph plugin  => error with reducing node
print("\n** Try to convert json config to graph def\n")
print(keras_model_to_graph_def(json.loads(model_config_json)))

```

The resulting config json is:
<details>
<summary>config json</summary>

```json
{
  "class_name": "Functional",
  "config": {
    "name": "model",
    "layers": [
      {
        "class_name": "InputLayer",
        "config": {
          "batch_input_shape": [
            null,
            3,
            2
          ],
          "dtype": "float32",
          "sparse": false,
          "ragged": false,
          "name": "input_1"
        },
        "name": "input_1",
        "inbound_nodes": []
      },
      {
        "class_name": "DoublingLayer",
        "config": {
          "name": "doubling_layer",
          "trainable": true,
          "dtype": "float32"
        },
        "name": "doubling_layer",
        "inbound_nodes": [
          [
            [
              "input_1",
              0,
              0,
              {}
            ]
          ]
        ]
      },
      {
        "class_name": "Add",
        "config": {
          "name": "add",
          "trainable": true,
          "dtype": "float32"
        },
        "name": "add",
        "inbound_nodes": [
          [
            [
              "doubling_layer",
              0,
              0,
              {}
            ],
            [
              "doubling_layer",
              0,
              1,
              {}
            ]
          ]
        ]
      }
    ],
    "input_layers": [
      [
        "input_1",
        0,
        0
      ]
    ],
    "output_layers": [
      [
        "add",
        0,
        0
      ]
    ]
  },
  "keras_version": "2.11.0",
  "backend": "tensorflow"
}
```
</details>

and the error message is:

> Traceback (most recent call last):
  File "/home/nolwen/Projects/decomon/tensorboard/minimal_example.py", line 26, in <module>
    print(keras_model_to_graph_def(json.loads(model_config_json)))
  File "/home/nolwen/Projects/decomon/deco_39_venv/lib/python3.9/site-packages/tensorboard/plugins/graph/keras_util.py", line 258, in keras_model_to_graph_def
    node_def.input.append(inbound_node_names[index])
IndexError: list index out of range

Actually tensorboard graph plugin seems to have a hard time knowning what to do with the "inbound_nodes" from "add" layer:
```json
"inbound_nodes": [
  [
    [
      "doubling_layer",
      0,
      0,
      {}
    ],
    [
      "doubling_layer",
      0,
      1,
      {}
    ]
  ]
]
```
Because of the tensor index 1 in the second inbound nodes, the function tries to look for a second name in the list `inbound_node_names` (which evaluates to `["model/doubling_layer"]`) that holds only one.

*Note: the json seems valid as it can be used to reconstruct a model leading to the expected computation.*

**Comment by groszewn** [comment]
Yes, you should be able to use `bazel` directly to test if you'd like. The workflow failure was a flake, so I've [rerun it](https://github.com/tensorflow/tensorboard/actions/runs/4354544107) to generate an artifact you can test with if that's easier.

**Comment by groszewn** [comment]
Alternatively, if you wait a day this change should be available in [tb-nightly](https://pypi.org/project/tb-nightly/).

**Comment by nhuet** [comment]
Thanks, it seems to fix my issue.
