### ISSUE TITLE
Cannot start tensorboard in anaconda installation of tensorflow

### ISSUE THREAD

**Issue by wang1943** [tensorflow/tensorboard#630]
Hello, all

I've recently installed tensorflow following instructions on its website by creating a virtual environment in **anaconda3** on **Windows 7**. I can import tensorflow and run scripts but **cannot make tensorboard  work.** 

Thanks!

Below are errors I got when trying to run tensorboard.

Traceback (most recent call last):
  File "d:\programdata\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main     "__main__", mod_spec)
  File "d:\programdata\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code 
exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "d:\programdata\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\main.py", line 36, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "d:\programdata\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\plugins\audio\audio_plugin.py", line 27, in <module>
    from tensorboard import plugin_util
  File "d:\programdata\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\plugin_util.py", line 21, in <module>
    import bleach
  File "d:\programdata\anaconda3\envs\tensorflow\lib\site-packages\bleach\__init__.py", line 5, in <module>
    from bleach.linkifier import (
  File "d:\programdata\anaconda3\envs\tensorflow\lib\site-packages\bleach\linkifier.py", line 6, in <module>
    from html5lib.filters.sanitizer import allowed_protocols
ImportError: cannot import name 'allowed_protocols'

**Comment by wchargin** [comment]
Closely related to #588. I'm closing this on the suspicion that it's a duplicate; if it's not, we can re-open.
