### ISSUE TITLE
grpc error `StatusCode.RESOURCE_EXHAUSTED` on `tenserboard dev upload` makes upload way slower

### ISSUE THREAD

**Issue by Butanium** [tensorflow/tensorboard#6454]
### Diagnostics
<details>
<summary>Diagnostics output</summary>
``````
--- check: autoidentify
INFO: diagnose_tensorboard.py source unavailable
--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='clement-Legion-5-17ACH6H-kubuntu', release='5.19.0-45-generic', version='#46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20', machine='x86_64')
INFO: sys.getwindowsversion(): N/A
--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/home/clement/Documents/PIK/sb3-contrib/venv'
--- check: installed_packages
INFO: installed: tensorboard==2.13.0
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']
INFO: installed: tensorboard-data-server==0.7.1
--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.13.0'
--- check: tensorflow_python_version
Traceback (most recent call last):
  File "<ipython-input-2-e01f03e77d16>", line 511, in main
    suggestions.extend(check())
  File "<ipython-input-2-e01f03e77d16>", line 81, in wrapper
    result = fn()
  File "<ipython-input-2-e01f03e77d16>", line 267, in tensorflow_python_version
    import tensorflow as tf
  File "/home/clement/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.9161.41/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'tensorflow'
--- check: tensorboard_data_server_version
INFO: data server binary: '/home/clement/Documents/PIK/sb3-contrib/venv/lib/python3.10/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.7.1-alpha.0'
--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/clement/Documents/PIK/sb3-contrib/venv/bin/tensorboard\n'
--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]
--- check: readable_fqdn
INFO: socket.getfqdn(): 'clement-Legion-5-17ACH6H-kubuntu'
--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=5259869, st_dev=66311, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1687798113, st_mtime=1687798113, st_ctime=1687798113)
INFO: mode: 0o40777
--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/clement/Documents/PIK/sb3-contrib/venv/lib/python3.10/site-packages']; bad_roots (0): []
--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==1.4.0
ale-py==0.8.1
anyio==3.7.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==23.1.0
AutoROM==0.6.1
AutoROM.accept-rom-license==0.6.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
cachetools==5.3.1
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cloudpickle==2.2.1
cmake==3.26.4
comm==0.1.3
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.1.1
executing==1.2.0
Farama-Notifications==0.0.4
fastjsonschema==2.17.1
filelock==3.12.2
fonttools==4.40.0
fqdn==1.5.1
google-auth==2.20.0
google-auth-oauthlib==1.0.0
grpcio==1.54.2
gym-classics==1.0.0
gymnasium==0.28.1
idna==3.4
importlib-resources==5.12.0
iniconfig==2.0.0
ipykernel==6.23.2
ipython==8.14.0
ipython-genutils==0.2.0
ipywidgets==8.0.6
isoduration==20.11.0
jax-jumpy==1.0.0
jedi==0.18.2
Jinja2==3.1.2
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.6.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
kiwisolver==1.4.4
lit==16.0.5.post0
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.1
matplotlib-inline==0.1.6
mdurl==0.1.2
minigrid==2.3.0
mistune==2.0.5
mpmath==1.3.0
multiprocess==0.70.14
nbclassic==1.0.0
nbclient==0.8.0
nbconvert==7.5.0
nbformat==5.9.0
nest-asyncio==1.5.6
networkx==3.1
notebook==6.5.4
notebook_shim==0.2.3
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
oauthlib==3.2.2
opencv-python==4.7.0.72
overrides==7.3.1
packaging==23.1
pandas==2.0.2
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.5.0
pip==23.1.2
platformdirs==3.5.3
pluggy==1.0.0
pox==0.3.2
ppft==1.7.6.6
prometheus-client==0.17.0
prompt-toolkit==3.0.38
protobuf==4.23.3
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pygame==2.4.0
Pygments==2.15.1
pyparsing==3.0.9
pyrsistent==0.19.3
pytest==7.3.2
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3
PyYAML==6.0
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.3.1
requests==2.31.0
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.4.2
rsa==4.9
-e git+https://github.com/pik-gane/stable-baselines3-contrib-satisfia/@7e0908e8883c3cedccd79c97ad4be98c70e6cea3#egg=sb3_contrib
Send2Trash==1.8.2
setuptools==65.5.1
Shimmy==0.2.1
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
stable-baselines3==2.0.0a13
stack-data==0.6.2
sympy==1.12
tensorboard==2.13.0
tensorboard-data-server==0.7.1
terminado==0.17.1
tinycss2==1.2.1
tomli==2.0.1
torch==2.0.1
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
triton==2.0.0
typing_extensions==4.6.3
tzdata==2023.3
uri-template==1.2.0
urllib3==1.26.16
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.3
Werkzeug==2.3.6
wheel==0.38.4
widgetsnbextension==4.0.7
``````
</details>
### Next steps
No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

## Issue description
When trying to upload my experiment, I got this error : 
```
E0626 19:23:56.607564 140689821474816 uploader.py:564] Upload call failed with error <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Rate limit exceeded. Please try again later."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:34.95.66.171:443 {grpc_message:"Rate limit exceeded. Please try again later.", grpc_status:8, created_time:"2023-06-26T19:23:56.60685778+02:00"}"

E0626 19:24:57.312478 140689821474816 uploader.py:564] Upload call failed with error <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Rate limit exceeded. Please try again later."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:34.95.66.171:443 {grpc_message:"Rate limit exceeded. Please try again later.", grpc_status:8, created_time:"2023-06-26T19:24:57.312050186+02:00"}"

E0626 19:25:53.855873 140689821474816 uploader.py:564] Upload call failed with error <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Rate limit exceeded. Please try again later."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:34.95.66.171:443 {grpc_message:"Rate limit exceeded. Please try again later.", grpc_status:8, created_time:"2023-06-26T19:25:53.85541391+02:00"}"
```
It keeps uploading but at a slower rate. Why does that happen ?

PS here is my tensorboard usage:
![image](https://github.com/tensorflow/tensorboard/assets/55806347/835e075d-1c21-43f4-afb9-1f2bd46a57a5)

**Comment by bmd3k** [comment]
Thanks for the report. It helped us realize we had misconfigured some upload rates. We've fixed that. The good news is that you shouldn't get "Rate limit exceeded" errors any longer and your uploaded data should be whole. The bad news is that this won't make your uploads any faster and, in certain circumstances, will make them slower.

**Comment by Butanium** [comment]
Ok, thank you!

**Comment by bmd3k** [comment]
If your first uploads were before March 14th then, yes, they would have been faster. We unfortunately had to restrict upload rates around that time.
