### ISSUE TITLE
pip install 0.4.0rc1 error on Python 3.5 env

### ISSUE THREAD

**Issue by tomleader** [tensorflow/tensorboard#650]
```
python -V
Python 3.5.2

pip --version
pip 8.1.1 from /usr/local/python3.5.2/lib/python3.5/site-packages (python 3.5)
```
The server can NOT connect the Internet so I need to install tensorboard offline(you should ignore the http connection error);

I download the package **tensorflow_tensorboard-0.4.0rc1-py3-none-any.whl** from pypi.python.org and rz to the server then 
```
pip3 install tensorflow_tensorboard-0.4.0rc1-py3-none-any.whl 

Processing ./tensorflow_tensorboard-0.4.0rc1-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/local/python3.5.2/lib/python3.5/site-packages (from tensorflow-tensorboard==0.4.0rc1)
Collecting futures>=3.1.1 (from tensorflow-tensorboard==0.4.0rc1)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f08f799cb38>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/futures/
```

AFAIK the **futures** package only used in Python 2.x and Python 3.5 has concurrent.futures.

So the error means that I need to install futures>=3.1.1 on my Python 3.5 env but in fact you can not do that.

Anyone has any ideas?

**Comment by julian-carpenter** [comment]
Being an Arch Linux, which has Tensorboard in the community repo, when i try starting it it says:

```
Traceback (most recent call last):
  File "/usr/bin/tensorboard", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'futures>=3.1.1' distribution was not found and is required by tensorflow-tensorboard
```

this is not resolvable for me i guess ...

**Comment by senden9** [comment]
Link to the corresponding bug report in the Archlinux bugtracker: https://bugs.archlinux.org/task/56041

**Comment by jart** [comment]
We're going to try to get a bug fix release out tomorrow, fixing this for you guys.
