### ISSUE TITLE
Executing genrule //tensorboard/pip_package:p ip_package failed: (Exit 1): bash failed: error executing command 

### ISSUE THREAD

**Issue by alittlesir** [tensorflow/tensorboard#6526]
```shell
DEBUG: /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/external/build_bazel_rules_nodejs/index.bzl:65:14: node_repository attribute not set and no repository named 'nodejs_toolchains' exists; installing default node
DEBUG: /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
Analyzing: target //tensorboard/pip_package:extract_pip_package (0 packages loaded, 0 targets configured)
INFO: Analyzed target //tensorboard/pip_package:extract_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: /root/bbb/tensorboard-2.13.0/tensorboard/pip_package/BUILD:8:8: Executing genrule //tensorboard/pip_package:pip_package failed: (Exit 1): bash failed: error executing command 
  (cd /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/sandbox/linux-sandbox/6/execroot/org_tensorflow_tensorboard && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorboard/pip_package/build_pip_package bazel-out/aarch64-fastbuild/bin/tensorboard/pip_package/pip_packages.tar.gz')
# Configuration: 5bce98c8953c87f19e68ae5f0a86af1e1c82bf70aa46e90354fd86c5e280bd4f
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
++ uname
+ '[' Linux = Darwin ']'
+ sedi='sed -i'
+ command -v virtualenv
Target //tensorboard/pip_package:extract_pip_package failed to build
INFO: Elapsed time: 0.693s, Critical Path: 0.11s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
```
## Environment information (required)

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

```
/root/note/diagnose_tensorboard.py:32: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
### Diagnostics

<details>
<summary>Diagnostics output</summary>


--- check: autoidentify
INFO: diagnose_tensorboard.py version df7af2c6fc0e4c4a5b47aeae078bc7ad95777ffa

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='localhost.localdomain', release='4.19.90-2112.8.0.0131.oe1.aarch64', version='#1 SMP Fri Dec 31 19:53:20 UTC 2021', machine='aarch64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
WARNING: no installation among: ['tb-nightly', 'tensorboard', 'tensorflow-tensorboard']
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
Traceback (most recent call last):
  File "/root/note/diagnose_tensorboard.py", line 511, in main
    suggestions.extend(check())
                       ^^^^^^^
  File "/root/note/diagnose_tensorboard.py", line 81, in wrapper
    result = fn()
             ^^^^
  File "/root/note/diagnose_tensorboard.py", line 260, in tensorboard_python_version
    from tensorboard import version
ModuleNotFoundError: No module named 'tensorboard'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "/root/note/diagnose_tensorboard.py", line 511, in main
    suggestions.extend(check())
                       ^^^^^^^
  File "/root/note/diagnose_tensorboard.py", line 81, in wrapper
    result = fn()
             ^^^^
  File "/root/note/diagnose_tensorboard.py", line 267, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: data server binary: None
which: no tensorboard in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)

--- check: tensorboard_binary_path
INFO: which tensorboard: None

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'localhost.localdomain'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (0): []; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==1.4.0
cachetools==5.1.0
certifi==2022.9.24
charset-normalizer==3.1.0
google-auth==2.19.0
google-auth-oauthlib==0.4.6
gpg==1.21.0
grpcio==1.54.2
idna==3.4
libcomps==0.1.19
Markdown==3.4.3
MarkupSafe==2.1.2
numpy==1.24.3
oauthlib==3.2.2
pip==23.1.2
protobuf==3.19.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
requests==2.31.0
requests-oauthlib==1.3.1
rpm==4.18.1
rsa==4.9
setuptools @ file:///home/abuild/rpmbuild/BUILD/setuptools-68.0.0/dist/setuptools-68.0.0-py3-none-any.whl#sha256=ad3e10ecc836f55e277995520557359fc266a4ba94babd2c8f02f4830c3e5b87
six @ file:///home/abuild/rpmbuild/BUILD/six-1.16.0/dist/six-1.16.0-py2.py3-none-any.whl#sha256=8bdcfd7c234bf392ad82fa28825bfd4d4d67bf51dfc82551a8b8d903b70ac7d4
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
urllib3==1.26.16
Werkzeug==2.3.4
wheel==0.40.0

``````

</details>
```

## Steps to reproduce (required)

Please provide explicit commands to reproduce the problem in a fresh
environment (virtualenv, Conda environment, …). Include any necessary
configuration, such as Conda `environment.yml` files.
```
wget https://github.com/tensorflow/tensorboard/archive/refs/tags/2.13.0.tar.gz
tar zxvf 2.13.0.tar.gz
cd tensorboard-2.13.0
bazel --output_user_root=`pwd`/../output_user_root info output_base
bazel --output_user_root=`pwd`/../output_user_root build //tensorboard/pip_package:build_pip_package  --verbose_failures
```

**Comment by alittlesir** [comment]
but i use `bazel build tensorboard:tensorboard`, it build successfully

**Comment by nfelt** [comment]
As the first error message you posted mentions, can you pass `--sandbox_debug` to show why the cmmand failed?

**Comment by alittlesir** [comment]
bazel --output_user_root=`pwd`/../output_user_root run //tensorboard/pip_package:extract_pip_package -- --sandbox_debug
```
Loading: 
Loading: 0 packages loaded
DEBUG: /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/external/build_bazel_rules_nodejs/index.bzl:65:14: node_repository attribute not set and no repository named 'nodejs_toolchains' exists; installing default node
DEBUG: /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
Analyzing: target //tensorboard/pip_package:extract_pip_package (0 packages loaded, 0 targets configured)
INFO: Analyzed target //tensorboard/pip_package:extract_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: /root/bbb/tensorboard-2.13.0/tensorboard/pip_package/BUILD:8:8: Executing genrule //tensorboard/pip_package:pip_package failed: (Exit 1): linux-sandbox failed: error executing command 
  (cd /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/sandbox/linux-sandbox/5/execroot/org_tensorflow_tensorboard && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /root/bbb/output_user_root/install/db37af126640724c35b138d37f6c780b/linux-sandbox -t 15 -w /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/sandbox/linux-sandbox/5/execroot/org_tensorflow_tensorboard -w /tmp -w /dev/shm -D -- /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorboard/pip_package/build_pip_package bazel-out/aarch64-fastbuild/bin/tensorboard/pip_package/pip_packages.tar.gz')
1691492746.463058406: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1691492746.463092116: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1691492746.463352228: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 104575
1691492746.463387558: src/main/tools/linux-sandbox-pid1.cc:641: Pid1Main started
1691492746.463443269: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1691492746.463527459: src/main/tools/linux-sandbox-pid1.cc:260: working dir: /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/sandbox/linux-sandbox/5/execroot/org_tensorflow_tensorboard
1691492746.463556439: src/main/tools/linux-sandbox-pid1.cc:292: writable: /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/sandbox/linux-sandbox/5/execroot/org_tensorflow_tensorboard
1691492746.463568150: src/main/tools/linux-sandbox-pid1.cc:292: writable: /tmp
1691492746.463575730: src/main/tools/linux-sandbox-pid1.cc:292: writable: /dev/shm
1691492746.463628550: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /
1691492746.463640850: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc
1691492746.463648920: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev
1691492746.463656650: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/pts
1691492746.463666660: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/mqueue
1691492746.463676890: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1691492746.463683010: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/console
1691492746.463690910: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys
1691492746.463698231: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup
1691492746.463740901: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/systemd
1691492746.463751561: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpu,cpuacct
1691492746.463760281: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/perf_event
1691492746.463768931: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/devices
1691492746.463778791: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/freezer
1691492746.463788621: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/net_cls,net_prio
1691492746.463796881: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/pids
1691492746.463805001: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/memory
1691492746.463813051: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpuset
1691492746.463821061: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/blkio
1691492746.463829062: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/rdma
1691492746.463837072: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/files
1691492746.463845232: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/hugetlb
1691492746.463864952: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /home
1691492746.463872912: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /etc/resolv.conf
1691492746.463880182: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /etc/hostname
1691492746.463887202: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /etc/hosts
1691492746.463895422: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/sandbox/linux-sandbox/5/execroot/org_tensorflow_tensorboard
1691492746.463909982: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/bbb/output_user_root/2daf5eb5b17fb287bbad8cb1dbf025a3/sandbox/linux-sandbox/5/execroot/org_tensorflow_tensorboard
1691492746.463918942: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /tmp
1691492746.463924332: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1691492746.463943712: src/main/tools/linux-sandbox-pid1.cc:451: calling fork...
1691492746.464043593: src/main/tools/linux-sandbox-pid1.cc:481: child started with PID 2
++ uname
+ '[' Linux = Darwin ']'
+ sedi='sed -i'
+ command -v virtualenv
1691492746.470535504: src/main/tools/linux-sandbox-pid1.cc:498: wait returned pid=2, status=0x100
1691492746.470542624: src/main/tools/linux-sandbox-pid1.cc:516: child exited normally with code 1
1691492746.496451057: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //tensorboard/pip_package:extract_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.617s, Critical Path: 0.07s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
```

**Comment by nfelt** [comment]
It looks like the script is failing with `command -v virtualenv`. Could you try installing virtualenv?

**Comment by alittlesir** [comment]
yes, after virtualenv be installed, and it build ok, thanks @nfelt
