### ISSUE TITLE
ImportError: cannot import name 'PROJECTOR_FILENAME'

### ISSUE THREAD

**Issue by GaneshSaiKumar** [tensorflow/tensorboard#653]
`(Demo_ve) C:\Users\Ganesh\Documents\nn-handson>tensorboard --logdir tb_log
Traceback (most recent call last):
  File "C:\Users\Ganesh\Anaconda3\envs\Demo_ve\Scripts\tensorboard-script.py", line 3, in <module>
    import tensorflow.tensorboard.tensorboard
  File "C:\Users\Ganesh\Anaconda3\envs\Demo_ve\lib\site-packages\tensorflow\tensorboard\tensorboard.py", line 34, in <module>
    from tensorflow.tensorboard.backend import server
  File "C:\Users\Ganesh\Anaconda3\envs\Demo_ve\lib\site-packages\tensorflow\tensorboard\backend\server.py", line 38, in <module>
    from tensorflow.tensorboard.plugins.projector import plugin as projector_plugin
  File "C:\Users\Ganesh\Anaconda3\envs\Demo_ve\lib\site-packages\tensorflow\tensorboard\plugins\projector\plugin.py", line 27, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
ImportError: cannot import name 'PROJECTOR_FILENAME'
`

**Comment by chihuahua** [comment]
Could you please instead try

```python
from tensorboard.plugins.projector.projector_plugin import PROJECTOR_FILENAME
```
?
