### ISSUE TITLE
File path encoding

### ISSUE THREAD

**Issue by WindSnowLi** [tensorflow/tensorboard#6533]
When there are other Chinese subfolders or files in the folder. `tensorboard -- inspect -- logdir` will prompt`_ Pywrap_ File_ IO. IsDirectory (compat. path_to bytes (path)) 'utf-8' code can't decode byte 0xc7 `. The feeling here can be handled specially.

**Comment by WindSnowLi** [comment]
The following outputs contain Chinese characters in the path:
```
Exception in thread ProjectorPluginIsActiveThread:
Traceback (most recent call last):
  File "C:\Users\goyuj\miniconda3\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\goyuj\miniconda3\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\goyuj\miniconda3\lib\site-packages\tensorboard\plugins\projector\projector_plugin.py", line 331, in _determine_is_active
    self._update_configs()
  File "C:\Users\goyuj\miniconda3\lib\site-packages\tensorboard\plugins\projector\projector_plugin.py", line 362, in _update_configs
    self._configs, self.config_fpaths = self._read_latest_config_files(
  File "C:\Users\goyuj\miniconda3\lib\site-packages\tensorboard\plugins\projector\projector_plugin.py", line 458, in _read_latest_config_files
    ckpt_path = _find_latest_checkpoint(logdir)
  File "C:\Users\goyuj\miniconda3\lib\site-packages\tensorboard\plugins\projector\projector_plugin.py", line 798, in _find_latest_checkpoint
    ckpt_path = tf.train.latest_checkpoint(dir_path)
  File "C:\Users\goyuj\miniconda3\lib\site-packages\tensorflow\python\checkpoint\checkpoint_management.py", line 350, in latest_checkpoint
    ckpt = get_checkpoint_state(checkpoint_dir, latest_filename)
  File "C:\Users\goyuj\miniconda3\lib\site-packages\tensorflow\python\checkpoint\checkpoint_management.py", line 277, in get_checkpoint_state
    file_content = file_io.read_file_to_string(
  File "C:\Users\goyuj\miniconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 351, in read_file_to_string
    return f.read()
  File "C:\Users\goyuj\miniconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "C:\Users\goyuj\miniconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 77, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 58: invalid start byte
```

**Comment by groszewn** [comment]
Sorry for the delay here. TensorBoard relies on [tensorflow-io](https://github.com/tensorflow/io) for IO operations if it's installed. Can you check if you have the most up-to-date installation of `tensorflow-io` in your environment and try again? If that doesn't work, I would suggest you open up an issue with them for this support.

**Comment by WindSnowLi** [comment]
This doesn't seem to work. However, this does not affect usage, just pay attention to folder naming.
