### ISSUE TITLE
ImportError: dlopen(/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 2): no suitable image found.  Did find:

### ISSUE THREAD

**Issue by DamianZayne** [tensorflow/tensorboard#6557]
Traceback (most recent call last):
  File "/Users/zhaochaole/opt/anaconda3/envs/py40/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/tensorboard/default.py", line 32, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 25, in <module>
    from tensorboard.data import provider
  File "/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/tensorboard/data/__init__.py", line 17, in <module>
    from tensorboard.data import experimental  # noqa: F401
  File "/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/tensorboard/data/experimental/__init__.py", line 17, in <module>
    from tensorboard.data.experimental.experiment_from_dev import (  # noqa: F401
  File "/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/tensorboard/data/experimental/experiment_from_dev.py", line 21, in <module>
    import grpc
  File "/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 2): no suitable image found.  Did find:
        /Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so: mach-o, but wrong architecture
        /Users/zhaochaole/opt/anaconda3/envs/py40/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so: mach-o, but wrong architecture

**Comment by rileyajones** [comment]
What exactly are you trying to do? With just a stack trace it's hard to help.
- This seems like an issue with a pip package, have you ever gotten tensorboard running on this machine before?
- Can you provide more information about your environment?
