### ISSUE TITLE
900+ versions of tb_nightly fail with the same Error

### ISSUE THREAD

**Issue by profPlum** [tensorflow/tensorboard#6647]
To report a problem with TensorBoard itself, please fill out the
remainder of this template.

## Environment information (required)

`diagnose_tensorboard.py` output:
[tb_diagnostics.log](https://github.com/tensorflow/tensorboard/files/13032968/tb_diagnostics.log)

## Issue description

**I've tried now 900+ different versions of tb_nightly** (I have a script which brute force tests different pip package versions), and it seems that every one of them is failing with (approximately) this error when I try to use tensorboard after installing tb_nightly.
Additionally I can find no information about this error related to tensorboard on the internet (6 hits with google, all wrong).

```
Traceback (most recent call last):
  File "/home/dwyerdei/.local/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/home/dwyerdei/.local/lib/python3.8/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/home/dwyerdei/.local/lib/python3.8/site-packages/tensorboard/default.py", line 33, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/home/dwyerdei/.local/lib/python3.8/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 23, in <module>
    from tensorboard import plugin_util
  File "/home/dwyerdei/.local/lib/python3.8/site-packages/tensorboard/plugin_util.py", line 24, in <module>
    import markdown
  File "/home/dwyerdei/.local/lib/python3.8/site-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "/home/dwyerdei/.local/lib/python3.8/site-packages/markdown/core.py", line 26, in <module>
    from . import util
  File "/home/dwyerdei/.local/lib/python3.8/site-packages/markdown/util.py", line 88, in <module>
    INSTALLED_EXTENSIONS = metadata.entry_points(group='markdown.extensions')
TypeError: entry_points() got an unexpected keyword argument 'group'
```

**P.S. I just got this same error when trying to use the regular tensorboard version: 2.14.1**, something really fishy is going on...

**Comment by arcra** [comment]
It seems like you're using python 3.8, but TensorBoard [no longer supports that version](http://github.com/tensorflow/tensorboard/blob/master/tensorboard/pip_package/setup.py#L67) (although the error seems to be more related to the `markdown` dependency... admittedly, I expected a different error from that restriction).

I found this other issue: Python-Markdown/markdown#1196, and from what I can gather, this is more related to using a newer version of markdown with an older version of python. You could try pinning the version of markdown in your system to `markdown==3.3.4`, or using a newer version of python and see if that resolves the issue.
