### ISSUE TITLE
tensorboard dev export gRPC error

### ISSUE THREAD

**Issue by gml16** [tensorflow/tensorboard#6661]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version df7af2c6fc0e4c4a5b47aeae078bc7ad95777ffa

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='[REDACTED]', release='5.15.90.1-microsoft-standard-WSL2', version='#1 SMP Fri Jan 27 02:56:13 UTC 2023', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.15.0
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']
INFO: installed: tensorboard-data-server==0.7.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.15.0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "/home/gml16/tb_analyse.py", line 511, in main
    suggestions.extend(check())
  File "/home/gml16/tb_analyse.py", line 81, in wrapper
    result = fn()
  File "/home/gml16/tb_analyse.py", line 267, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: data server binary: '/home/gml16/.local/lib/python3.10/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.7.1-alpha.0'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/gml16/.local/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): '[REDACTED].'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/gml16/.local/lib/python3.10/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
abagen==0.1.3
absl-py==1.4.0
appdirs==1.4.4
astor==0.8.1
audioread==3.0.0
bids-validator==1.12.0
blinker==1.4
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
cloudpickle==2.2.1
command-not-found==0.3
contourpy==1.1.0
cryptography==3.4.8
cycler==0.11.0
dbus-python==1.2.18
decorator==5.1.1
distro==1.7.0
distro-info===1.1build1
docopt==0.6.2
exceptiongroup==1.1.2
fonttools==4.42.0
formulaic==0.5.2
google-auth==2.22.0
google-auth-oauthlib==1.0.0
greenlet==2.0.2
grpcio==1.56.2
gym==0.26.2
gym-notices==0.0.8
httplib2==0.20.2
idna==3.4
importlib-metadata==4.6.4
iniconfig==2.0.0
interface-meta==1.3.0
jeepney==0.7.1
joblib==1.3.1
keyring==23.5.0
kiwisolver==1.4.4
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy_loader==0.3
librosa==0.10.0.post2
llvmlite==0.40.1
Markdown==3.4.4
MarkupSafe==2.1.3
matplotlib==3.7.2
more-itertools==8.10.0
mrivis==0.3.8
msgpack==1.0.5
netifaces==0.11.0
networkx==3.1
nibabel==5.1.0
num2words==0.5.12
numba==0.57.1
numpy==1.24.3
oauthlib==3.2.0
opencv-python==4.8.0.74
packaging==23.1
pandas==1.4.3
Pillow==10.0.0
pip==23.2.1
platformdirs==3.10.0
playsound==1.3.0
pluggy==1.2.0
pooch==1.6.0
protobuf==4.23.4
pyasn1==0.5.0
pyasn1-modules==0.3.0
PyAudio==0.2.11
pybids==0.16.2
pycairo==1.23.0
pycparser==2.21
pydub==0.25.1
pygame==2.3.0
pyglet==1.5.11
PyGObject==3.42.1
PyJWT==2.3.0
pyopencl==2023.1.1
pyparsing==2.4.7
pytest==7.4.0
python-apt==2.4.0+ubuntu1
python-dateutil==2.8.2
pytools==2023.1.1
pytz==2023.3
PyYAML==5.4.1
regex==2023.6.3
requests==2.31.0
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn==1.3.0
scipy==1.10.1
SecretStorage==3.3.1
setuptools==59.6.0
SimpleITK==2.2.1
six==1.16.0
soundfile==0.12.1
soxr==0.3.5
SQLAlchemy==2.0.20
systemd-python==234
tensorboard==2.15.0
tensorboard-data-server==0.7.1
threadpoolctl==3.2.0
tiktoken==0.4.0
-e git+https://github.com/tinygrad/tinygrad.git@ab9e4a2e936aaca450dc48cb6e85d39062c4d4e4#egg=tinygrad
tomli==2.0.1
torch==1.13.1+cu117
torchaudio==0.13.1+cu117
torchvision==0.14.1+cu117
tqdm==4.65.0
typing_extensions==4.7.1
ubuntu-advantage-tools==8001
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.16
VisualQC==0.6.6
wadllib==1.3.6
Werkzeug==2.3.6
wheel==0.37.1
wrapt==1.15.0
zipp==1.0.0

``````

</details>

## Issue description

I have run the command `tensorboard dev export` a couple of times and it always crashes when downloading the second experiment (ID `Iwhg460QQpG0j7Y4F3t53w`). Thank you for your help with this :)

```
$ tensorboard dev export --outdir ./tbdev_export
TensorFlow installation not found - running with reduced feature set.

****************************************************************
****************************************************************
****************************************************************

NOTICE - ACTION REQUIRED: TensorBoard.dev is shutting down.

Please export your experiments by Dec 31, 2023.

See the FAQ at https://tensorboard.dev.

****************************************************************
****************************************************************
****************************************************************

Downloaded experiment K9Jd3yAlSaqQhAtxiMx6oQ
Traceback (most recent call last):
  File "/home/gml16/.local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/home/gml16/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/gml16/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/program.py", line 276, in main
    return runner(self.flags) or 0
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/uploader_subcommand.py", line 691, in run
    return _run(flags, self._experiment_url_callback)
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/uploader_subcommand.py", line 124, in _run
    intent.execute(server_info, channel)
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/uploader_subcommand.py", line 545, in execute
    for experiment_id in exporter.export():
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/exporter.py", line 184, in export
    for block, filename in data:
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/exporter.py", line 228, in _request_json_data
    for response in stream:
  File "/home/gml16/.local/lib/python3.10/site-packages/grpc/_channel.py", line 475, in __next__
    return self._next()
  File "/home/gml16/.local/lib/python3.10/site-packages/grpc/_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Received RST_STREAM with error code 2"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:34.95.66.171:443 {created_time:"2023-10-21T21:55:39.280960514+01:00", grpc_status:13, grpc_message:"Received RST_STREAM with error code 2"}"
>
```

**Comment by bmd3k** [comment]
Hi, thanks for reaching out.
I investigated and we believe this is caused by a server-side configuration issue on our side. Requests time out after 300 seconds. Your experiment is large enough that the requests surpass the 300s threshold.
I'll let you know when we think we have this fixed (hopefully later this week or sometime next week).

**Comment by bmd3k** [comment]
Hi, I believe this should be addressed. We pushed the server-side configuration yesterday. Could you attempt the export again and let us know whether it worked for you?

**Comment by gml16** [comment]
Thank you for looking into it. I'm not sure if this is related but I now get the following traceback:
```
Traceback (most recent call last):
  File "/home/gml16/.local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/home/gml16/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/gml16/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/program.py", line 276, in main
    return runner(self.flags) or 0
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/uploader_subcommand.py", line 611, in run
    return _run(flags, self._experiment_url_callback)
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/uploader_subcommand.py", line 146, in _run
    intent.execute(server_info, channel)
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/uploader_subcommand.py", line 477, in execute
    for experiment_id in exporter.export():
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/exporter.py", line 149, in export
    for experiment in experiments:
  File "/home/gml16/.local/lib/python3.10/site-packages/tensorboard/uploader/exporter.py", line 454, in list_experiments
    for response in stream:
  File "/home/gml16/.local/lib/python3.10/site-packages/grpc/_channel.py", line 475, in __next__
    return self._next()
  File "/home/gml16/.local/lib/python3.10/site-packages/grpc/_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Internal error. Please report this and specify reference code 9cce95cb-60ff-46be-b1ac-711088cd91bb."
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-11-10T21:04:14.291837393+00:00", grpc_status:13, grpc_message:"Internal error. Please report this and specify reference code 9cce95cb-60ff-46be-b1ac-711088cd91bb."}"
>
```
