### ISSUE TITLE
Exception when debugging in pycharm

### ISSUE THREAD

**Issue by lostinplace** [tensorflow/tensorboard#6750]
## Environment information (required)

win amd64

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

```
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version df7af2c6fc0e4c4a5b47aeae078bc7ad95777ffa

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=12, micro=1, releaselevel='final', serial=0)
INFO: os.name: nt
INFO: os.uname(): N/A
INFO: sys.getwindowsversion(): sys.getwindowsversion(major=10, minor=0, build=22631, platform=2, service_pack='')

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: 'C:\\Users\\CMWhe\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\gnot-cKTlZDKu-py3.12'

--- check: installed_packages
INFO: installed: tensorboard==2.15.2
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']
INFO: installed: tensorboard-data-server==0.7.2

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.15.2'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "C:\code\GNOT\diagnose_tensorboard.py", line 511, in main
    suggestions.extend(check())
                       ^^^^^^^
  File "C:\code\GNOT\diagnose_tensorboard.py", line 81, in wrapper
    result = fn()
             ^^^^
  File "C:\code\GNOT\diagnose_tensorboard.py", line 267, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: data server binary: None

--- check: tensorboard_binary_path
INFO: which tensorboard: b'C:\\Users\\CMWhe\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\gnot-cKTlZDKu-py3.12\\Scripts\\tensorboard.exe\r\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'Box2'

--- check: stat_tensorboardinfo
INFO: directory: C:\Users\CMWhe\AppData\Local\Temp\.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['C:\\Users\\CMWhe\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\gnot-cKTlZDKu-py3.12\\Lib\\site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==2.1.0

cachetools==5.3.2

certifi==2024.2.2

charset-normalizer==3.3.2

colorama==0.4.6

contourpy==1.2.0

cycler==0.12.1

dgl @ file:///C:/code/GNOT/lib/dgl-2.1-cp312-cp312-win_amd64.whl

einops==0.7.0

filelock==3.13.1

fonttools==4.48.1

fsspec==2024.2.0

google-auth==2.27.0

google-auth-oauthlib==1.2.0

grpcio==1.60.1

idna==3.6

Jinja2==3.1.3

joblib==1.3.2

kiwisolver==1.4.5

Markdown==3.5.2

MarkupSafe==2.1.5

matplotlib==3.8.2

mpmath==1.3.0

networkx==3.2.1

numpy==1.26.4

oauthlib==3.2.2

packaging==23.2

pillow==10.2.0

pip==23.3.1

protobuf==4.25.2

psutil==5.9.8

pyasn1==0.5.1

pyasn1-modules==0.3.0

pyparsing==3.1.1

python-dateutil==2.8.2

requests==2.31.0

requests-oauthlib==1.3.1

rsa==4.9

scikit-learn==1.4.0

scipy==1.12.0

setuptools==69.1.0

six==1.16.0

sympy==1.12

tensorboard==2.15.2

tensorboard-data-server==0.7.2

threadpoolctl==3.2.0

torch==2.2.0

torchdata==0.7.1

tqdm==4.66.2

typing_extensions==4.9.0

urllib3==2.2.0

Werkzeug==3.0.1

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.
```


For browser-related issues, please additionally specify:

  - Browser type and version (e.g., Chrome 64.0.3282.140):
  - Screenshot, if it’s a visual issue:

## Issue description

when attempting to debug a script using tensorboard in pycharm, an exception is thrown preventing progress:

```
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\CMWhe\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CMWhe\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\code\GNOT\train.py", line 18, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\torch\utils\tensorboard\writer.py", line 15, in <module>
    from tensorboard.summary.writer.event_file_writer import EventFileWriter
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\summary\__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\summary\v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\plugins\histogram\summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\plugins\histogram\summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\util\tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\compat\tensorflow_stub\__init__.py", line 25, in <module>
    from . import app  # noqa
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\compat\tensorflow_stub\app.py", line 21, in <module>
    from . import flags
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\compat\tensorflow_stub\flags.py", line 123, in <module>
    FLAGS = _FlagValuesWrapper(FLAGS)  # pylint: disable=used-before-assignment
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\compat\tensorflow_stub\flags.py", line 75, in __getattribute__
    return self.__dict__["__wrapped"].__getattribute__(name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '__wrapped'
python-BaseException
Traceback (most recent call last):
  File "C:\Users\CMWhe\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_xml.py", line 177, in _get_type
    if isinstance(o, t[0]):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CMWhe\AppData\Local\pypoetry\Cache\virtualenvs\gnot-cKTlZDKu-py3.12\Lib\site-packages\tensorboard\compat\tensorflow_stub\flags.py", line 75, in __getattribute__
    return self.__dict__["__wrapped"].__getattribute__(name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '__wrapped'
```

**Comment by tonyspumoni** [comment]
I manually made this change (as it's not in a release yet) but end up hitting another issue after when trying to use pycharm debugger:

```
Traceback (most recent call last):
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'notf' from 'tensorboard.compat' (C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.3.3\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2022.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\mikes\code\dungeon-sprint\dungeon_crawl_vision.py", line 22, in <module>
    from stable_baselines3 import PPO
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\stable_baselines3\__init__.py", line 3, in <module>
    from stable_baselines3.a2c import A2C
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\stable_baselines3\a2c\__init__.py", line 1, in <module>
    from stable_baselines3.a2c.a2c import A2C
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\stable_baselines3\a2c\a2c.py", line 7, in <module>
    from stable_baselines3.common.buffers import RolloutBuffer
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\stable_baselines3\common\buffers.py", line 16, in <module>
    from stable_baselines3.common.utils import get_device
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\stable_baselines3\common\utils.py", line 20, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\torch\utils\tensorboard\writer.py", line 18, in <module>
    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\torch\utils\tensorboard\_embedding.py", line 8, in <module>
    if hasattr(tf, 'io'):
       ^^^^^^^^^^^^^^^^^
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
                   ^^^^^^^^^^^^^^^
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorboard\lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
                 ^^^^^^
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorboard\lazy.py", line 50, in load_once
    module = load_fn()
             ^^^^^^^^^
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorboard\compat\__init__.py", line 45, in tf
    import tensorflow
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\__init__.py", line 45, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module>
    from tensorflow._api.v2.__internal__ import distribute
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__.distribute import combinations
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module>
    from tensorflow.python.distribute.combinations import env # line: 456
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\distribute\combinations.py", line 33, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\distribute\collective_all_reduce_strategy.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\distribute\cross_device_ops.py", line 28, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\distribute\cross_device_utils.py", line 22, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\distribute\values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 205, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\data\util\structure.py", line 32, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\ragged\__init__.py", line 28, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor.py", line 3149, in <module>
    from tensorflow.python.ops.ragged import ragged_ops  # pylint: disable=unused-import, g-bad-import-order, g-import-not-at-top
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\ragged\ragged_ops.py", line 41, in <module>
    from tensorflow.python.ops.ragged import ragged_image_ops
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\ragged\ragged_image_ops.py", line 24, in <module>
    from tensorflow.python.ops import image_ops
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\image_ops.py", line 159, in <module>
    from tensorflow.python.ops.image_ops_impl import *
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 40, in <module>
    from tensorflow.python.ops import nn_impl
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\nn_impl.py", line 26, in <module>
    from tensorflow.python.ops import ctc_ops  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\ctc_ops.py", line 32, in <module>
    from tensorflow.python.ops import custom_gradient
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\custom_gradient.py", line 17, in <module>
    from tensorflow.python.eager import backprop
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\eager\backprop.py", line 47, in <module>
    from tensorflow.python.ops.parallel_for import control_flow_ops as pfor_ops
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 37, in <module>
    from tensorflow.python.ops.parallel_for.pfor import PFor
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\ops\parallel_for\pfor.py", line 71, in <module>
    from tensorflow.python.platform import flags
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\platform\flags.py", line 121, in <module>
    FLAGS = _FlagValuesWrapper(FLAGS)  # pylint: disable=used-before-assignment
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
  File "C:\Users\mikes\code\dungeon-sprint\venv\Lib\site-packages\tensorflow\python\platform\flags.py", line 73, in __getattribute__
    return self.__dict__['__wrapped'].__getattribute__(name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '__wrapped'
```

I've spent a lot of time trying to solve this (mostly focusing on the first error: `ImportError: cannot import name 'notf' from 'tensorboard.compat`, but nothing I've found seems to clearly describe the root cause. I've tried upgrading/downgrading tensorflow, torch, and a bunch of other stuff and can't seem to get past this.

here's my venv:

```
absl-py==2.1.0
asttokens==2.4.1
astunparse==1.6.3
attrs==23.2.0
autobahn==23.6.2
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
colorama==0.4.6
comtypes==1.3.1
contourpy==1.2.0
cryptography==42.0.5
cycler==0.12.1
executing==2.0.1
Farama-Notifications==0.0.4
filelock==3.13.3
flatbuffers==24.3.25
fonttools==4.50.0
fsspec==2024.3.1
gast==0.5.4
google-pasta==0.2.0
grpcio==1.62.1
gym==0.26.2
gym-notices==0.0.8
gymnasium==0.29.1
h11==0.14.0
h5py==3.10.0
hyperlink==21.0.0
icecream==2.1.3
idna==3.6
intel-openmp==2021.4.0
jax-jumpy==1.0.0
Jinja2==3.1.3
json5==0.9.24
keras==3.1.1
kiwisolver==1.4.5
libclang==18.1.1
loguru==0.7.2
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.3
mdurl==0.1.2
mkl==2021.4.0
ml-dtypes==0.3.2
mpmath==1.3.0
namex==0.0.7
nested-lookup==0.2.25
networkx==3.2.1
numpy==1.26.4
opencv-python==4.9.0.80
opt-einsum==3.3.0
optree==0.11.0
outcome==1.3.0.post0
packaging==24.0
pandas==2.2.1
pillow==10.3.0
pipdeptree==2.17.0
protobuf==4.25.3
psutil==5.9.8
pycparser==2.22
pygame==2.5.2
Pygments==2.17.2
pyparsing==3.1.2
PySocks==1.7.1
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==306
pywinauto==0.6.8
requests==2.31.0
rich==13.7.1
scipy==1.13.0
selenium==4.19.0
setuptools==69.2.0
six==1.16.0
sniffio==1.3.1
sortedcontainers==2.4.0
stable_baselines3==2.3.0
sympy==1.12
tbb==2021.11.0
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.1
tensorflow-intel==2.16.1
termcolor==2.4.0
torch==2.2.0+cu121
torchaudio==2.2.0+cu121
torchvision==0.17.0+cu121
tqdm==4.66.2
trio==0.25.0
trio-websocket==0.11.1
txaio==23.1.1
typing_extensions==4.10.0
tzdata==2024.1
urllib3==2.2.1
websockets==12.0
Werkzeug==3.0.2
wheel==0.43.0
win32-setctime==1.1.0
wrapt==1.16.0
wsaccel==0.6.6
wsproto==1.2.0
```

Happy to try and provide more context if needed

**Comment by tonyspumoni** [comment]
ok this might have been an issue in PyCharm - I just upgraded to PY-241.14494.241 and the problem is gone
