### ISSUE TITLE
Fast data loading feedback (--load_fast=true; “RustBoard”)

### ISSUE THREAD

**Issue by moghadas76** [tensorflow/tensorboard#6844]
E0429 10:53:15.660596 137725360838464 application.py:125] Failed to load plugin WhatIfToolPluginLoader.load; ignoring it.
Traceback (most recent call last):
  File "/home/seyed/miniconda3/lib/python3.10/site-packages/tensorboard/backend/application.py", line 123, in TensorBoardWSGIApp
    plugin = loader.load(context)
  File "/home/seyed/miniconda3/lib/python3.10/site-packages/tensorboard_plugin_wit/wit_plugin_loader.py", line 57, in load
    from tensorboard_plugin_wit.wit_plugin import WhatIfToolPlugin
  File "/home/seyed/miniconda3/lib/python3.10/site-packages/tensorboard_plugin_wit/wit_plugin.py", line 40, in <module>
    from tensorboard_plugin_wit._utils import common_utils
  File "/home/seyed/miniconda3/lib/python3.10/site-packages/tensorboard_plugin_wit/_utils/common_utils.py", line 17, in <module>
    from tensorboard_plugin_wit._vendor.tensorflow_serving.apis import classification_pb2
  File "/home/seyed/miniconda3/lib/python3.10/site-packages/tensorboard_plugin_wit/_vendor/tensorflow_serving/apis/classification_pb2.py", line 15, in <module>
    from tensorboard_plugin_wit._vendor.tensorflow_serving.apis import input_pb2 as tensorflow__serving_dot_apis_dot_input__pb2
  File "/home/seyed/miniconda3/lib/python3.10/site-packages/tensorboard_plugin_wit/_vendor/tensorflow_serving/apis/input_pb2.py", line 37, in <module>
    _descriptor.FieldDescriptor(
  File "/home/seyed/miniconda3/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by groszewn** [comment]
What version of tensorboard are you currently running? We've been [redirecting](https://github.com/tensorflow/tensorboard/pull/6343) the what-if tool to the learning interpretability tool since version [2.12.3](https://github.com/tensorflow/tensorboard/blob/master/RELEASE.md#release-2123) since the what if tool was no longer maintained.

**Comment by groszewn** [comment]
Closing since the referenced plugin is no longer included as part of newer releases, feel free to reopen if you have other comments.
