### ISSUE TITLE
TensorBoard can’t find your event files.Log directory: hdfs://tensorboard_log

### ISSUE THREAD

**Issue by weAreFriendYo** [tensorflow/tensorboard#6872]
TensorBoard 2.11.2 at http://wedata3:6006/ (Press CTRL+C to quit)
Exception in thread Reloader:
Traceback (most recent call last):
  File "/opt/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/python/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python/lib/python3.7/site-packages/tensorboard/backend/event_processing/data_ingester.py", line 104, in _reload
    self._multiplexer.AddRunsFromDirectory(path, name)
  File "/opt/python/lib/python3.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 204, in AddRunsFromDirectory
    for subdir in io_wrapper.GetLogdirSubdirectories(path):
  File "/opt/python/lib/python3.7/site-packages/tensorboard/backend/event_processing/io_wrapper.py", line 195, in GetLogdirSubdirectories
    if not tf.io.gfile.exists(path):
  File "/opt/python/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 290, in file_exists_v2
    _pywrap_file_io.FileExists(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.InternalError: HadoopFileSystem is not initialized correctly

**Comment by groszewn** [comment]
Can you please provide your environment specific information? Copying from the issue template:

> ## Environment information (required)
>
> Please run `diagnose_tensorboard.py` (link below) in the same environment from which you normally run TensorFlow/TensorBoard, and paste the output here:
>
> https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

TensorBoard itself doesn't natively support cloud filesystems as of version 2.9 ([release notes](https://github.com/tensorflow/tensorboard/blob/b163c5df852f08468013fb292bff854e5f49add0/RELEASE.md#features-6)), you'd need to separately install `tensorflow-io`.
