### ISSUE TITLE
Tensorboard fails in python 3.13 because `imghdr` module is absent

### ISSUE THREAD

**Issue by Bichidian** [tensorflow/tensorboard#6964]
Running `tensorboard --logdir .` under python 3.13 leads to the following error:
```
Traceback (most recent call last):
  File ".venv/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File ".venv/lib64/python3.13/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File ".venv/lib64/python3.13/site-packages/tensorboard/default.py", line 40, in <module>
    from tensorboard.plugins.image import images_plugin
  File ".venv/lib64/python3.13/site-packages/tensorboard/plugins/image/images_plugin.py", line 18, in <module>
    import imghdr
ModuleNotFoundError: No module named 'imghdr'
```
It seems that `imghdr` is [no longer part of the Python standard library](https://docs.python.org/3/library/imghdr.html) in 3.13.

**Comment by arcra** [comment]
Thanks for reporting. We'll look for a replacement for this library.

AFAICT, we only use it to get MIME types, which I expect should be somewhat easily replaceable, but we can't guarantee when we'll address this. In the meantime, Python < 3.13 would be required.

**Comment by hzhangxyz** [comment]
You can install [`standard-imghdr`](https://pypi.org/project/standard-imghdr/) for temporary fix

**Comment by E1k3** [comment]
Any news on this?
If no work on this has been done, would you be open to one of the following solutions?
1. Taking on https://github.com/h2non/filetype.py as a dependency to replace the two calls to imagehdr.what
2. Copying the bmp, gif, jpeg and png matchers from filetype.py (MIT licensed so should be fine) to replace the two calls to imagehdr.what

If one of these is fine, I can submit a PR.

**Comment by foxik** [comment]
Given that the `imghdr.py` from the standard library has <4kB and has only trivial dependencies (os, warnings), I would just add a copy to the TensorBoard codebase? The code is simple, I would expect zero maintenance cost.

**Comment by E1k3** [comment]
Fine by me, as long as I can use tensorboard with 3.13 without pushing standard-imghdr everywhere.

**Comment by arcra** [comment]
Quick update:

Last week I prepared PR #7009 as suggested by @Zamanhuseyinli in #7008, but I need to do a few things to ensure it works well with our internal repo. Last week was a short work week in the US, so I didn't have time to complete this work. I'll try to finish it this week.

However, I learned we need to do a bit more work after this to make TB work with python 3.12+. I filed #7010 to track this.

**Comment by arcra** [comment]
Hey folks! Today I [published the release 2.20.0](https://pypi.org/project/tensorboard/2.20.0/), which includes the chances from above. This version _should_ be compatible with python 3.13, but please let me know if you still find any issues with this.
