### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'make_tensor_proto

### ISSUE THREAD

**Issue by zafarali** [tensorflow/tensorboard#743]
Hi there, I have tensorflow 1.0.0 and tensorboard 0.1.8.

**Note that I have to use tf 1.0.0 since I need it to run on some shared hardware**

This is the output of my `--inspect` command

```
python3 -m tensorboard.main --logdir=checkpoints/StructuredEmbeddingtrain_summaries/ --inspect
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
checkpoints/StructuredEmbeddingtrain_summaries/

These tags are in checkpoints/StructuredEmbeddingtrain_summaries/:
audio -
histograms
   individual_loss
   neg_score_dist
   pos_score_dist
images -
scalars
   objective_1
   score_loss
tensor -
======================================================================

Event statistics for checkpoints/StructuredEmbeddingtrain_summaries/:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
images -
scalars
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================

```

However, when I run Tensorboard to visualize the scalars I get the following error and the notice that no data was found. Note that I can visualize the graph and projections!:

```
TensorBoard 0.1.8 at http://jc-10:6006 (Press CTRL+C to quit)
Exception in thread Reloader:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ml/zahmed8/.local/lib/python3.5/site-packages/tensorboard/backend/application.py", line 327, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/home/ml/zahmed8/.local/lib/python3.5/site-packages/tensorboard/backend/application.py", line 301, in reload_multiplexer
    multiplexer.Reload()
  File "/home/ml/zahmed8/.local/lib/python3.5/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 195, in Reload
    accumulator.Reload()
  File "/home/ml/zahmed8/.local/lib/python3.5/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 189, in Reload
    self._ProcessEvent(event)
  File "/home/ml/zahmed8/.local/lib/python3.5/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 335, in _ProcessEvent
    value = data_compat.migrate_value(value)
  File "/home/ml/zahmed8/.local/lib/python3.5/site-packages/tensorboard/data_compat.py", line 57, in migrate_value
    return handler(value) if handler else value
  File "/home/ml/zahmed8/.local/lib/python3.5/site-packages/tensorboard/data_compat.py", line 106, in _migrate_scalar_value
    tensor_proto = tf.make_tensor_proto(scalar_value)
AttributeError: module 'tensorflow' has no attribute 'make_tensor_proto'

```

![image](https://user-images.githubusercontent.com/6295292/32871655-60eb3304-ca50-11e7-92b2-37e6e64d7074.png)

**Comment by jart** [comment]
Try reinstalling the tensorflow 1.0 pip package. Back then, tensorboard came included and hadn't been broken out into a separate pip package.

**Comment by jart** [comment]
If that doesn't fix things, let me know and I'll reopen this issue.

**Comment by zafarali** [comment]
It worked great! Thanks

**Comment by ofhippo** [comment]
I had a very similar issue and reinstalling tensorflow fixed it. Thanks!

**Comment by zkl99999** [comment]
reinstalling tensorflow fixed it

**Comment by meenaparam** [comment]
Downgrading tensorflow from 1.1.0 to 1.0.0 also fixed this issue for me.
