### ISSUE TITLE
How to use tensorboard to watch the tensorflow source internal variables such as LSTM

### ISSUE THREAD

**Issue by liangzhenlin123** [tensorflow/tensorboard#761]
I was doing a project need to rewrite lstm code convlstm, I rewritten the call function inside tensorflow source code, but the recognition of handwritten numbers are very poor. I want to use tensorboard to observe a variable in the call function, but I get the following error:
![image](https://user-images.githubusercontent.com/29907023/33072406-6210308c-cefa-11e7-9347-80fe3a2fd6b4.png)

2017-11-21 11:58:43.897293: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
2017-11-21 11:58:43.897371: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
2017-11-21 11:58:43.897633: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
2017-11-21 11:58:43.897870: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.897594: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.897349: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
2017-11-21 11:58:43.898570: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
2017-11-21 11:58:43.897662: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.899196: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.897804: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.897562: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.897978: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
2017-11-21 11:58:43.898276: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
2017-11-21 11:58:43.901228: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.898902: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.897770: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
2017-11-21 11:58:43.899582: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
2017-11-21 11:58:43.899899: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.900258: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.898755: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.904101: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.901754: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.902256: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.902690: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.903175: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.903613: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.901475: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
2017-11-21 11:58:43.904301: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Internal: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]
Traceback (most recent call last):
File "C:\Users\liangzhenlin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
return fn(*args)
File "C:\Users\liangzhenlin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
status, run_metadata)
File "C:\Users\liangzhenlin\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in exit
next(self.gen)
File "C:\Users\liangzhenlin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:/Users/liangzhenlin/PycharmProjects/untitled3/test5.py", line 1042, in 
merge_write=sess.run(merge,feed_dict={lstm.X:teX,lstm.Y:teY,lstm.keep_pro:1.0})
File "C:\Users\liangzhenlin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
run_metadata_ptr)
File "C:\Users\liangzhenlin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
feed_dict_tensor, options, run_metadata)
File "C:\Users\liangzhenlin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
options, run_metadata)
File "C:\Users\liangzhenlin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Retval[0] has already been set.
[[Node: _retval_Merge/MergeSummary_0_0 = _RetvalT=DT_STRING, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"]]

so how to deal with it？

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
