### ISSUE TITLE
Error in tensorflow serving not able to build using bazel 0.7, tensorflow 1.4

### ISSUE THREAD

**Issue by AKhilGarg91** [tensorflow/tensorboard#769]
C:\serving>bazel build //tensorflow_serving/example:mnist_saved_model
ERROR: error loading package 'tensorflow_serving/example': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_archive//': Traceback (most recent call last):
        File "C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/org_tensorflow/tensorflow/workspace.bzl", line 119
                _apply_patch(repo_ctx, repo_ctx.attr.patch_file)
        File "C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/org_tensorflow/tensorflow/workspace.bzl", line 111, in _apply_patch
                _execute_and_check_ret_code(repo_ctx, cmd)
        File "C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/org_tensorflow/tensorflow/workspace.bzl", line 92, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/protobuf_archive -i C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/org_tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
.
INFO: Elapsed time: 42.062s

**Comment by AKhilGarg91** [comment]
its tensorflow issue.
