### ISSUE TITLE
Cannot build with most recent Bazel version

### ISSUE THREAD

**Issue by cblichmann** [tensorflow/tensorboard#929]
See title, I have
```bash
$ bazel version
Build label: 0.10.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Nov 9 04:43:10 +50056 (1517474666590)
Build timestamp: 1517474666590
Build timestamp as int: 1517474666590
```

Running `bazel build tensorboard`, like suggested, gives me:
```
$ bazel build tensorboard
ERROR: /usr/local/google/home/cblichmann/devel/tensorboard/WORKSPACE:35:1: Traceback (most recent call last):
        File "/usr/local/google/home/cblichmann/devel/tensorboard/WORKSPACE", line 35          
                closure_repositories()        
        File "/usr/local/google/home/cblichmann/.cache/bazel/_bazel_cblichmann/01f39ec27eededc038eda174c157aac1/external/io_bazel_rules_closure/closure/repositories.bzl", line
69, in closure_repositories                                                                           
                _check_bazel_version("Closure Rules", "0.4.5")                   
        File "/usr/local/google/home/cblichmann/.cache/bazel/_bazel_cblichmann/01f39ec27eededc038eda174c157aac1/external/io_bazel_rules_closure/closure/repositories.bzl", line
172, in _check_bazel_version                   
                fail(("%s requires Bazel >=%s but was...)))                      
Closure Rules requires Bazel >=0.4.5 but was 0.10.0                
ERROR: Error evaluating WORKSPACE file         
ERROR: /usr/local/google/home/cblichmann/devel/tensorboard/WORKSPACE:43:1: Traceback (most recent call last):
        File "/usr/local/google/home/cblichmann/devel/tensorboard/WORKSPACE", line 43
                web_test_repositories(omit_com_google_code_findbugs_js..., <5 more arguments>)
        File "/usr/local/google/home/cblichmann/.cache/bazel/_bazel_cblichmann/01f39ec27eededc038eda174c157aac1/external/io_bazel_rules_webtesting/web/repositories.bzl", line 6
2, in web_test_repositories                                        
                _check_bazel_version("Web Testing Rules", "0.4.2")
        File "/usr/local/google/home/cblichmann/.cache/bazel/_bazel_cblichmann/01f39ec27eededc038eda174c157aac1/external/io_bazel_rules_webtesting/web/repositories.bzl", line 5
58, in _check_bazel_version                           
                fail(("%s requires Bazel >=%s but was...)))          
Web Testing Rules requires Bazel >=0.4.2 but was 0.10.0          
ERROR: Error evaluating WORKSPACE file        
ERROR: Skipping 'tensorboard': error loading package 'external': Package 'external' contains errors
WARNING: Target pattern parsing failed.       
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.101s                 
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Workaround: Using Bazel 0.5.4, like in `.travis-ci.yml`, works fine.

**Comment by nfelt** [comment]
Thanks for the report.  We're working on updating our deps to fix this issue.  #883 is most of the way, then we just need #931 that's in flight now.
