### ISSUE TITLE
Can't run tensorboard after successful bazel build

### ISSUE THREAD

**Issue by xiaohk** [tensorflow/tensorboard#932]
I downloaded the tensorboard-1.5.0 release, and `bazel build tensorboard:tensorboard`. After installing tensorboard, I got the following error when running `tensorboard`.

```
JayWong tensorboard $ tensorboard
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 11, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/site-packages/tensorboard/main.py", line 36, in run_main
    tf.app.run(main)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.6/site-packages/tensorboard/main.py", line 45, in main
    default.get_assets_zip_provider())
  File "/usr/local/lib/python3.6/site-packages/tensorboard/program.py", line 165, in main
    tb = create_tb_app(plugins, assets_zip_provider)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/program.py", line 189, in create_tb_app
    raise ValueError('A logdir must be specified when db is not specified. '
ValueError: A logdir must be specified when db is not specified. Run `tensorboard --help` for details and examples.
```

**Comment by nfelt** [comment]
```
A logdir must be specified when db is not specified. Run `tensorboard --help` for details and examples.
```

You need to invoke tensorboard with `--logdir path/to/your/tensorflow/logdir`.
