### ISSUE TITLE
Tensorboard throws "AttributeError: module 'bleach' has no attribute 'clean'"

### ISSUE THREAD

**Issue by tastyminerals** [tensorflow/tensorboard#978]
The model was trained and saved successfully to `output` dir.

OS: Linux 4.14.16-1-MANJARO
tensorboard: 1.6.0
tensorflow-gpu: 1.5.0
tensorflow-tensorboard: 1.5.1
bleach: 1.5.0

Running tensorboard to investigate the model `tensorboard --logdir=output` throws:
```
TensorBoard 1.5.1 at http://pavel-pc:6006 (Press CTRL+C to quit)
W0216 13:04:50.579611 Thread-1 application.py:273] path /[[_dataImageSrc]] not found, sending 404
E0216 13:04:52.764234 Thread-4 _internal.py:88] Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/tensorboard/backend/application.py", line 271, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/usr/lib/python3.6/site-packages/werkzeug/wrappers.py", line 308, in application
    resp = f(*args[:-2] + (request,))
  File "/usr/lib/python3.6/site-packages/tensorboard/backend/application.py", line 242, in _serve_plugins_listing
    response[plugin.plugin_name] = plugin.is_active()
  File "/usr/lib/python3.6/site-packages/tensorboard/plugins/distribution/distributions_plugin.py", line 65, in is_active
    return self._histograms_plugin.is_active()
  File "/usr/lib/python3.6/site-packages/tensorboard/plugins/histogram/histograms_plugin.py", line 64, in is_active
    return bool(self._multiplexer) and any(self.index_impl().values())
  File "/usr/lib/python3.6/site-packages/tensorboard/plugins/histogram/histograms_plugin.py", line 78, in index_impl
    summary_metadata.summary_description)}
  File "/usr/lib/python3.6/site-packages/tensorboard/plugin_util.py", line 85, in markdown_to_safe_html
    string_sanitized = bleach.clean(
AttributeError: module 'bleach' has no attribute 'clean'
```

The browser page displays and freezes:

![2018-02-16-130801_728x292_scrot](https://user-images.githubusercontent.com/7676160/36307010-6ed95f28-131a-11e8-8ff1-af666d3f8260.png)

**Comment by nfelt** [comment]
Are you sure your `bleach 1.5.0` is properly installed?  Maybe try uninstalling and reinstalling it?  That version of bleach should have `bleach.clean`, e.g. on my machine:

```text
$ virtualenv bleachtest
$ source bleachtest/bin/activate
$ pip install bleach==1.5.0
$ python -c 'import bleach; print bleach.clean'
<function clean at 0x102b15f50>
```

**Comment by tastyminerals** [comment]
Indeed. Reinstalling bleach via pip resolved this issue. I have also found `.virtualenvs` dir which contained bleach packages, guess a proper clean up was needed.
