### ISSUE TITLE
Exception when loading tensorboard

### ISSUE THREAD

**Issue by GeoffreySmythe** [tensorflow/tensorboard#992]
Hey all!
I keep getting this exception when I try to load tensorboard (I am loading a graph, scalars and an image).
I've tried using different code from other people, but I still keep on getting the same error.
Do you know where the problem might be?

Exception in thread Reloader:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 361, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 335, in reload_multiplexer
    multiplexer.Reload()
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 195, in Reload
    accumulator.Reload()
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 186, in Reload
    self._ProcessEvent(event)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 332, in _ProcessEvent
    value = data_compat.migrate_value(value)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/data_compat.py", line 57, in migrate_value
    return handler(value) if handler else value
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/data_compat.py", line 108, in _migrate_scalar_value
    display_name=value.metadata.display_name or value.tag,
AttributeError: 'Value' object has no attribute 'metadata'

**Comment by nfelt** [comment]
This error would mean that the log files you're using have some unexpected missing fields.  Is there any way you can share the log files or the code used to generate the log files?  (These would be the `events.out.tfevents.*` files in the directory you're passing to `--logdir`.)

Also, if you could provide the following, that would be helpful:
- TensorBoard version (printed out when you launch `tensorboard`)
- OS platform and version

**Comment by GeoffreySmythe** [comment]
The code that I am using is a code used in TensorBoard Dev Summit. Link to the code:
https://github.com/dandelionmane/tf-dev-summit-tensorboard-tutorial#tensorboard-dev-summit-tutorial

Python 3.5.2
Tensorflow 1.4.1
TensorBoard 1.6.0
Ubuntu 16.04

**Comment by GeoffreySmythe** [comment]
Updating tensorflow to 1.5 solved all issues.
Thanks anyways!

**Comment by nfelt** [comment]
Glad to hear it!

**Comment by Imorton-zd** [comment]
@GeoffreySmythe @nfelt  Hi, I also meet this error. However, I just used the same code yesterday, which has no errors. Why do I meet this error today? If possible, please give me some suggestions. Thanks!

**Comment by nfelt** [comment]
@Imorton-zd This error is data-dependent so it might depend on the log directory you're using.  Can you provide the version of TensorFlow and TensorBoard you're using?  If you aren't on 1.5.0+, could you try upgrading?  If you're still seeing the issue then it'd be helpful to have a sample of the TF code you're executing and/or the logfiles being produced.

**Comment by GeoffreySmythe** [comment]
@Imorton-zd Can you post the version of tensorflow, python, tensorboard that you have? At least for me the problem was solved by installing a newer tensorflow version to 1.6. Posting an error that you have would really help a lot.

**Comment by fatterZhang** [comment]
@GeoffreySmythe Thank you. I met this error, too. And follow your advice, solved the problem.
Environment: ubuntu14.04 + cuda8.0 + py2.7 + anaconda
former: tensorflow 1.2   tensorflow-tenboard 0.4,   now:tensorflow1.6.0 and tensorboard 1.6.0
